### ISSUE TITLE
[Bug]: NPE running UnitTest with invalid test

### ISSUE THREAD

**Issue by nadment** [apache/hop#1905]
### Apache Hop version?

2.2.0

### Java version?

11

### Operating system

Windows

### What happened?

Run a workflow with a pipeline unit test transformation that has an invalid test (which does not exist) throw an NPE, the workflow should terminate with an error.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by uraychang** [comment]
sorry, misclick on "close"
