### ISSUE TITLE
[Bug]: Dimension Update/Lookup - Dialog erases TK field each time transform is opened.

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#2021]
### Apache Hop version?

2.2, 2.3

### Java version?

11

### Operating system

Linux

### What happened?

![2022-12-07_19-55-54 - Dimension Update Erases TK in dialog when opening](https://user-images.githubusercontent.com/1233654/206337469-fcd2b073-9225-49c5-87fa-ffbbc4791310.gif)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by nadment** [comment]
Another bug, some "Type of dimension update" are lost when dialog is closed
![image](https://user-images.githubusercontent.com/39568358/206558961-5f5acd2e-d24e-40a5-b57c-ea7966ed2ba9.png)

**Comment by hansva** [comment]
Related ticket #2047
