### ISSUE TITLE
[Bug]: Null If transform does not "nullify" empty fields

### ISSUE THREAD

**Issue by campen** [apache/hop#2024]
[NullIfTransform.txt](https://github.com/apache/hop/files/10186985/NullIfTransform.txt)
[NullIfTransform.zip](https://github.com/apache/hop/files/10186955/NullIfTransform.zip)
### Apache Hop version?

2.2, 2.3

### Java version?

11.0.15 (aarch64 java)

### Operating system

macOS, Linux

### What happened?

Prior to 2.2, the null If steps converted empty strings to null, but in 2.2 it does not work anymore. See attached .hpl with example.  It works without issue in 2.1 and will not work properly in 2.2

### Issue Priority

Priority: 1

### Issue Component

Component: Transforms

**Comment by nadment** [comment]
Under Windows, everything works as expected? 
![image](https://user-images.githubusercontent.com/39568358/206558145-d031fbf7-be7b-4351-9bd0-1c7d82a2eaa7.png)

Do you have other results ?

**Comment by campen** [comment]
<img width="1717" alt="Screen Shot 2022-12-08 at 2 19 11 PM" src="https://user-images.githubusercontent.com/8354072/206559243-55da8a56-b0d6-47dc-98b6-9164bca7bacc.png">

Here are my results

**Comment by campen** [comment]
Note: this is a blocker for me to move beyond 2.1

**Comment by nadment** [comment]
@campen what is the value of the variable HOP_EMPTY_STRING_DIFFERS_FROM_NULL, this could explain the difference ?

**Comment by campen** [comment]
@nadment  - it is set to "Y" for both versions (2.1 and 2.2/3)

**Comment by nadment** [comment]
If you think about it, this variable HOP_EMPTY_STRING_DIFFERS_FROM_NULL has no meaning in this transformation. The only useful case is to replace an empty string by a null. I try a fix without this variable.

**Comment by campen** [comment]
Thanks! Let me know and I am happy to test it out. I agree about that variable having no impact on this transform.  I have different projects that look at empty and null as different (which is by my design).
