### ISSUE TITLE
[Bug]: Microsoft Excel Input removes files in 2.2

### ISSUE THREAD

**Issue by campen** [apache/hop#2025]
### Apache Hop version?

2.2

### Java version?

11.0.15 (aarch64 java)

### Operating system

macOS

### What happened?

When I have multiple selected files in the file list, and I open the transform in Hop 2.2, only the first line is shown, then if I select OK (without making any changes, it removes the hidden additional filenames.

Also you cannot select multiple rows in the filename list at once in the plugin.

### Issue Priority

Priority: 1

### Issue Component

Component: Plugins
[ExcelMultipleFilesIssue-before.hpl.zip](https://github.com/apache/hop/files/10188037/ExcelMultipleFilesIssue-before.hpl.zip)
[ExcelMultipleFilesIssue-after.hpl.zip](https://github.com/apache/hop/files/10188038/ExcelMultipleFilesIssue-after.hpl.zip)

**Comment by mattcasters** [comment]
So this is a user interface issue?  The transform doesn't really delete files?

**Comment by campen** [comment]
all I did was open the Excel Input transform and files 2-4 were missing, then when I clicked the OK button on the transform, they were gone from the xml

**Comment by campen** [comment]
so maybe yes...but I hadn't opened the pipeline when it ran and I noticed that only the first file had processed, so I think it is bigger than just the interface

**Comment by campen** [comment]
<img width="1806" alt="Screen Shot 2022-12-09 at 7 19 55 AM" src="https://user-images.githubusercontent.com/8354072/206724389-a084152a-3098-40f8-9ac1-cb95667f4f52.png">
This is how it looks running in a pipeline in 2.1

**Comment by campen** [comment]
<img width="1723" alt="Screen Shot 2022-12-09 at 8 28 03 AM" src="https://user-images.githubusercontent.com/8354072/206724524-b88cfc83-a95a-4738-9fcf-ccaa117e8c97.png">
This is how it looks in 2.2/2.3. Notice that only file1 is being processed

**Comment by campen** [comment]
[HopIssues.zip](https://github.com/apache/hop/files/10195665/HopIssues.zip)
I have attached the whole project - if you run the ExcelWorkflow.hwf, it is the same workflow as shown in the screenshots above

**Comment by hansva** [comment]
I can confirm the xml generation is no longer correct

**Comment by hansva** [comment]
It boils down to the previous XML being invalid...
The original XML for the files in the excel input is
```
    <file>
      <name>${PROJECT_HOME}/datasets/file1.xlsx</name>
      <filemask/>
      <exclude_filemask/>
      <file_required>N</file_required>
      <include_subfolders>N</include_subfolders>
      <name>${PROJECT_HOME}/datasets/file2.xlsx</name>
      <filemask/>
      <exclude_filemask/>
      <file_required>N</file_required>
      <include_subfolders>N</include_subfolders>
      <name>${PROJECT_HOME}/datasets/file3.xlsx</name>
      <filemask/>
      <exclude_filemask/>
      <file_required>N</file_required>
      <include_subfolders>N</include_subfolders>
      <name>${PROJECT_HOME}/datasets/file4.xlsx</name>
      <filemask/>
      <exclude_filemask/>
      <file_required>N</file_required>
      <include_subfolders>N</include_subfolders>
    </file>
```

We are now generating the following xml:
```
    <file>
      <name>${PROJECT_HOME}/datasets/file1.xlsx</name>
      <filemask/>
      <exclude_filemask/>
      <file_required>N</file_required>
      <include_subfolders>N</include_subfolders>
    </file>
      <name>${PROJECT_HOME}/datasets/file2.xlsx</name>
      <filemask/>
      <exclude_filemask/>
      <file_required>N</file_required>
      <include_subfolders>N</include_subfolders>
    </file>
      <name>${PROJECT_HOME}/datasets/file3.xlsx</name>
      <filemask/>
      <exclude_filemask/>
      <file_required>N</file_required>
      <include_subfolders>N</include_subfolders>
    </file>
      <name>${PROJECT_HOME}/datasets/file4.xlsx</name>
      <filemask/>
      <exclude_filemask/>
      <file_required>N</file_required>
      <include_subfolders>N</include_subfolders>
    </file>
```
I tried matching the original output with following configuration:
```
  @HopMetadataProperty(
      groupKey = "file",
      key = "file",
      inline = true,
      injectionGroupKey = "FILENAME_LINES",
      injectionGroupDescription = "ExcelInput.Injection.FILENAME_LINES")
  private List<EIFile> files;
```
but then the serialiser is unable to read the xml back in...
@mattcasters any idea if we can hack that format back in? Or should we spread an upgrade notice/warning
