### ISSUE TITLE
[Bug]: Dimension lookup/update

### ISSUE THREAD

**Issue by gugoan** [apache/hop#2047]
### Apache Hop version?

apache-hop-client-2.2.0

### Java version?

java 11.0.17 2022-10-18 LTS - Java(TM) SE Runtime Environment 18.9

### Operating system

Windows

### What happened?

In the "Dimension lookup/update" plugin, the column used in the "Fields" > "Dimensional field" tab is saved in the database as DATETIME type, and it should be saved as TEXT.

Here are some prints to explain better and my file "Carga-Dim-Departamento.hpl"

![image](https://user-images.githubusercontent.com/1585443/206929508-d9320bb2-1877-4cc7-affe-f39e6076490c.png)

![image](https://user-images.githubusercontent.com/1585443/206929537-38d06e7c-69bd-42c2-a8d5-196a61e0201a.png)

I immediately tested it on the **Apache Hop Client 2.1.0** version, this problem does not occur.

My dev specs:
Windows 10
PostgreSQL 14
[Carga-Dim-Departamento.zip](https://github.com/apache/hop/files/10203325/Carga-Dim-Departamento.zip)

Apache-hop-client-2.2.0
JAVA --version
java 11.0.17 2022-10-18 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.17+10-LTS-269)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.17+10-LTS-269, mixed mode)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
should be resolved, you can test with a latest version from [here](https://repository.apache.org/content/repositories/snapshots/org/apache/hop/hop-client/2.3.0-SNAPSHOT/)
