### ISSUE TITLE
[Feature Request]: Enable multipart/form-entity File Upload and Body Params with HTTP Post transform

### ISSUE THREAD

**Issue by iavasquez** [apache/hop#2048]
### What would you like to happen?

Most APIs expect binary files to be uploaded via multipart/form-data POST with boundaries encasing the file data (this is how Postman automatically Posts a file, for example).  

If using the "Post a file" flag in the current HTTP Post transform, it merely posts the binary data with no boundary or descriptors in the raw HTTP and it discards any Body Parameters that may have been configured on the Fields tab.  See screenshot for example. 

A solution is to use org.apache.http.entity.mime.MultipartEntityBuilder to build the request entity using the addBinaryBody method for a file upload and addTextBody for body parameters.  This would allow proper upload of binary files and the ability to post both a binary file and body parameters rather than the current limitation to one or the other. 

![Screen Shot 2022-12-11 at 3 01 05 PM](https://user-images.githubusercontent.com/8596173/206932244-2cc88cd5-d3ad-4d99-ac9f-e93780f58a20.jpg)

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
Hi @iavasquez, could you give the PR I made a go to see if it works? I did some tests against a mock server and it looks OK but I have no real API to test against.

Kr,
Hans

**Comment by iavasquez** [comment]
Hans, 

I tested and have two issues.  I'll DM you with a more detailed description on both.  

1) Lines 125-143 (pasted below) from HttpPost.java set a default Content-Type of XML if none is specified in the user-defined configurations.  This causes an issue because content-type must be`Content-Type: multipart/form-data; boundary=...` where the "boundary" is set dynamically at runtime.  If in the settings I set a header element for Content-Type=multipart/form-data it will set that and nothing else (no dynamic boundary).  It needs to be left blank so that the MultipartEntityBuilder can be allowed to set the Content-Type header as needed.  But it cannot do so because if I do not set a Content-Type header in the configuration, the hard-coded value is defaulting it to XML.  I think a more elegant solution is to remove those lines so as to not hard-code a default.  If the absence of a Content-Type setting causes an issue at runtime this would allow the User to see the error and adjust settings accordingly.  

2) I suggest creating a single MultipartEntityBuilder object and using it also for the file entity object and the Body Parameters.  Right now the entity for the post is set either to the Body Parameters or the MultipartEntity object if isPostAFile is checked.  Ideally, these don't have to be mutually exclusive.  You should be able to use the same MultipartEntityBuilder object for both Body Parameters and a file and send it in the same HTTP message. 

`if (!data.contentTypeHeaderOverwrite) { // can be overwritten now
        if (Utils.isEmpty(data.realEncoding)) {
          post.setHeader(CONTENT_TYPE, CONTENT_TYPE_TEXT_XML);
          if (isDebug()) {
            logDebug(
                BaseMessages.getString(PKG, PKG_HEADER_VALUE, CONTENT_TYPE, CONTENT_TYPE_TEXT_XML));
          }
        } else {
          post.setHeader(CONTENT_TYPE, CONTENT_TYPE_TEXT_XML + "; " + data.realEncoding);
          if (isDebug()) {
            logDebug(
                BaseMessages.getString(
                    PKG,
                    PKG_HEADER_VALUE,
                    CONTENT_TYPE,
                    CONTENT_TYPE_TEXT_XML + "; " + data.realEncoding));
          }
        }
      }`

**Comment by hansva** [comment]
Hi @iavasquez ,

It should now have the required result for you.
The second part, however, has not been implemented, the transform actually needs a complete overhaul so we might do a complete rewrite and a new version of this transform in the near future.

Feel free to test it out and provide feedback.
