### ISSUE TITLE
[Feature Request]: concatenate multiple json objects and output an array of them as result 

### ISSUE THREAD

**Issue by morteza-nouri** [apache/hop#2050]
### What would you like to happen?

I used data grid to create some Json object records(assume the field name is `request`).
`{"name":"a"}
{"name":"b"}`
I need some transform to give me the below result: 
`[{"name":"a"}, {"name":"b"}]`
I used Enhanced Json Output but It didn't work.(we want to create json object with only the value field, but it considers also the fieldname)

Here are my results with different configs:
![Screenshot from 2022-12-12 12-46-36](https://user-images.githubusercontent.com/88918241/207022471-8fb65322-09f1-4d4f-8547-f33631841765.png)

the same pipeline with `Json Fragment = Y`
![Screenshot from 2022-12-12 12-49-18](https://user-images.githubusercontent.com/88918241/207022388-00321c15-135c-49ed-aac9-c8a6d3913e85.png)

Here is the pipeline:
[pipeline.zip](https://github.com/apache/hop/files/10207002/pipeline.zip)

### Issue Priority

Priority: 1

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
Feel free to test the new feature and provide feedback.

Kr,
Hans

**Comment by morteza-nouri** [comment]
Hi Hans. Thanks it works!
Also it will be very nice to have an option to indicate the maximum number of objects in array for batch purposes. Consider the below scenario:
I produce JSON records then I want to create arrays of objects each with N size and post every array using HttpClient.

**Comment by hansva** [comment]
I like the idea, could you open an additional feature request for that please as it is not related to this.

**Comment by morteza-nouri** [comment]
Sure.
[https://github.com/apache/hop/issues/2119](https://github.com/apache/hop/issues/2119)
