### ISSUE TITLE
Filter retuns Unexpected error evaluation condition

### ISSUE THREAD

**Issue by duursma** [apache/hop#2063]
After using hop 2.2 for a few days I run into a situation that a FilterRows seemed to be unable to handle a straight-forward condition.  The result was always an exception.  I replaced it with a Java Filter and I could continue.

Now again I run into the same problem with an unrelated pipeline and spent a little more time on it.  At first it seemed that the condition was somehow corrupted and not shown in the gui as it was stored in the pipeline file.  After a lot of attempts I now have to pipelines with a syntactically identical version of the filter working on identical data.  One giving the exception.  The other working.  So it seems something else in the pipeline is causing this.

**Comment by hansva** [comment]
https://github.com/apache/hop/issues/2060
