### ISSUE TITLE
[BUG] PARSEDATE in Formula not implemented

### ISSUE THREAD

**Issue by plcruise** [apache/hop#2077]
Using Apache Hop 
I try to parse a Date using the Formula Transform in a Pipeline.
My Formula looks like this:
`PARSEDATE([date],"yyyyMMddHHmmss")`
On running the Pipeline I get the following error message:
`2022/12/17 10:35:10 - Formula.0 - ERROR: Unexpected error
2022/12/17 10:35:10 - Formula.0 - ERROR: org.apache.poi.ss.formula.eval.NotImplementedException: Error evaluating cell Sheet0!A1
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.poi.ss.formula.WorkbookEvaluator.addExceptionInfo(WorkbookEvaluator.java:344)
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateAny(WorkbookEvaluator.java:285)
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.poi.ss.formula.WorkbookEvaluator.evaluate(WorkbookEvaluator.java:216)
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.poi.xssf.usermodel.BaseXSSFFormulaEvaluator.evaluateFormulaCellValue(BaseXSSFFormulaEvaluator.java:56)
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.poi.ss.formula.BaseFormulaEvaluator.evaluate(BaseFormulaEvaluator.java:110)
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.hop.pipeline.transforms.formula.util.FormulaParser.getFormulaValue(FormulaParser.java:98)
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.hop.pipeline.transforms.formula.Formula.processRow(Formula.java:123)
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:51)
2022/12/17 10:35:10 - Formula.0 - 	at java.base/java.lang.Thread.run(Thread.java:831)
2022/12/17 10:35:10 - Formula.0 - Caused by: org.apache.poi.ss.formula.eval.NotImplementedFunctionException: PARSEDATE
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.poi.ss.formula.UserDefinedFunction.evaluate(UserDefinedFunction.java:56)
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.poi.ss.formula.OperationEvaluatorFactory.evaluate(OperationEvaluatorFactory.java:155)
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateFormula(WorkbookEvaluator.java:541)
2022/12/17 10:35:10 - Formula.0 - 	at org.apache.poi.ss.formula.WorkbookEvaluator.evaluateAny(WorkbookEvaluator.java:275)
2022/12/17 10:35:10 - Formula.0 - 	... 7 more`
which to me indicates that the function I want to call is not implemented. 
As the string defining the format to be parsed is not in the examples I assumed that maybe this special format is not Implemented and changed my formula to the example 
`PARSEDATE("2004/12/25 12:56:45.878";"yyyy/MM/dd HH:mm:ss.SSS")`
taken from the official [website](https://hop.apache.org/manual/latest/pipeline/transforms/formula.html#_datetime) . 
This example has an easy to fix syntax error. The semicolon needs to be replaced with a comma. Nontheless, the errormessage still stays the same, indicating to me, that the PARSEDATE function is not implemented.
Maybe I am missing something here, in that case I would be happy about being pointed towards that issue on my side.

**Comment by bamaer** [comment]
the error `org.apache.poi.ss.formula.eval.NotImplementedFunctionException: PARSEDATE` is thrown by Apache POI, the library that is used in the Formula transform, which does not support the PARSEDATE function. 

We aim to support all row-level functions from the list of [supported functions](https://poi.apache.org/components/spreadsheet/eval-devguide.html#appendixA). Functions that work across multiple rows are not supported by the formula transform (yet).

**Comment by hansva** [comment]
.add-labels bug,Transforms,Documentation,P2
