### ISSUE TITLE
[Bug]: Get variables, when setting trim shows as !ValueMeta.TrimType.Both!

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#2087]
### Apache Hop version?

2.3

### Java version?

11

### Operating system

Linux

### What happened?

![image](https://user-images.githubusercontent.com/1233654/208767183-51e796dd-aeaf-4ca2-a601-397fb92dc983.png)

It seems to still work.  Maybe a translation is failing?

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
.issue-take

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
Nice catch @usbrandon , I think it is a side effect of #2078

**Comment by hansva** [comment]
Not related to #2078
