### ISSUE TITLE
[Bug]: Filter Rows with multiple arguments using OR does not work

### ISSUE THREAD

**Issue by campen** [apache/hop#2093]
### Apache Hop version?

2.1 +

### Java version?

11.0.15+10-LTS

### Operating system

macOS

### What happened?

I have a pipeline that has a filter rows transform and if I use the same file field in the same transform using OR, the result does not filter any rows out. If I choose XOR, it filters the rows...I think this is working opposite.

My example shows 2 flows - 1 flow with separate single filters for each status that work for each status and the combined filter option that does not work.

[filterIssue.hpl.zip](https://github.com/apache/hop/files/10279486/filterIssue.hpl.zip)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
.issue-take

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
Hi @campen 

The filter is working as expected, the condition is wrong I'm afraid.
If your goal is to only have "new" and "changed" it has to be <> identical AND <> deleted.

Even Identical status rows will evaluate as "True" agains <> deleted and other way around

**Comment by campen** [comment]
I guess sometimes I get stuck in and/or logic spirals. Thanks
