### ISSUE TITLE
[Bug]: configuration perspective is undocumented

### ISSUE THREAD

**Issue by bamaer** [apache/hop#2094]
### Apache Hop version?

2.2.0

### Java version?

11

### Operating system

Other

### What happened?

the configuration perspective is undocumented in 2.2.0: 
https://hop.apache.org/manual/latest/hop-gui/perspectives.html

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by hansva** [comment]
.remove-label bug

**Comment by hansva** [comment]
.add-label task

**Comment by hansva** [comment]
ok, guess those commands don't work yet 😂
