### ISSUE TITLE
[Feature Request]: Add additionnals options for java 

### ISSUE THREAD

**Issue by Jerem59** [apache/hop#2095]
### What would you like to happen?

Hi
in batch script to start on Windows, i add this :  "-Dfile.encoding=UTF-8" "-Djava.io.tmpdir=C:\temp\Hop_Temp"

The best way would be an environment file containing override parameters to start Hop with specific parameters

Thx

### Issue Priority

Priority: 3

### Issue Component

Component: Infrastructure

**Comment by hansva** [comment]
Hi @Jerem59 ,

you can use the HOP_OPTIONS environment variable for this.
make sure to add "-Xmx2048m" to it too then

I can see we are missing Documentation on this so I'll leave this open to add some more information to the docs

**Comment by hansva** [comment]
Has been done along the way
