### ISSUE TITLE
[Bug]: Can't inject "Group field" field in "Row denormaliser" transform

### ISSUE THREAD

**Issue by enricomariam42** [apache/hop#2102]
### Apache Hop version?

SNAPSHOT-20221221

### Java version?

openjdk version "11.0.9.1" 2020-11-04 OpenJDK Runtime Environment (build 11.0.9.1+1-post-Uos-1deb10u2) OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Uos-1deb10u2, mixed mode, sharing)

### Operating system

Linux

### What happened?

Injecting "Group field" with a constant value in "Row denormaliser" transform has no effect and the group is missing in the injected transform.

Workaround: define the group in a field (e.g. in a "Add constants" transform) and select that in the metadata injection transform.

(Migrated from https://issues.apache.org/jira/browse/HOP-3860)

[injection.zip](https://github.com/apache/hop/files/10287743/injection.zip)

The attached pipeline `denormalizer_template.hpl` containing a "Row denormaliser" is injected in the two ways:
- with a constant value `inject_denormalizer_not_working.hpl` produce `injected_denormalizer_no_group.hpl` 
- with the group in a field `inject_denormalizer_working.hpl` produce `injected_denormalizer_with_group.hpl` 

Obtained (output of injected_denormalizer_no_group.hpl):
group | SNS | SERVIZI SAN | RicaviSan
-- | -- | -- | --
3A120 | -13576,2 | -322,8 | 3,5

Espected (output of injected_denormalizer_with_group.hpl): 
group | SNS | SERVIZI SAN | RicaviSan
-- | -- | -- | --
3A120 |   |   | 3,5
2G112 | -13576,2 | -322,8 |

### Issue Priority

Priority: 3

### Issue Component

Component: Metadata

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
Bit of an annoying issue, for lists it expects data rows as it does not really know how many fields to add when using a constant. I'm leaning towards "works as intended". Though I understand the edge case when you only need 1 value

**Comment by enricomariam42** [comment]
I understand. Letting input a constant value lead to an unexpected behavior, though. 
So, block the use of a constant filed if lists expected, or map a constant to a single value list, or split it to a list of fields based on special char can be possible?
I don't think document it is enough, even if there is a way around.
