### ISSUE TITLE
[Bug]: dimensionlookup is broken in 2.2

### ISSUE THREAD

**Issue by tilda-zz** [apache/hop#2107]
### Apache Hop version?

2.2

### Java version?

java 11

### Operating system

Linux

### What happened?

De 'dimensionlookup' works under version 2.1 and is broken in 2.2:

ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : (stderr)  at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.processRow(DimensionLookup.java:152)
2022/12/27 16:52:59 - opstart BI_SnelleFOD_CURRENT.sh - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : (stderr)  at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2022/12/27 16:52:59 - opstart BI_SnelleFOD_CURRENT.sh - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : (stderr)  at java.base/java.lang.Thread.run(Thread.java:833)
2022/12/27 16:52:59 - opstart BI_SnelleFOD_CURRENT.sh - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : (stderr) org.apache.hop.core.exception.HopTransformException:
2022/12/27 16:52:59 - opstart BI_SnelleFOD_CURRENT.sh - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : (stderr) Key field [null] couldn't be found!
2022/12/27 16:52:59 - opstart BI_SnelleFOD_CURRENT.sh - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : (stderr)
2022/12/27 16:52:59 - opstart BI_SnelleFOD_CURRENT.sh - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : (stderr)  at org.apache.hop.pipeline.transforms.dimensionlookup.DimensionLookup.processRow(DimensionLookup.java:152)
2022/12/27 16:52:59 - opstart BI_SnelleFOD_CURRENT.sh - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : (stderr)  at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2022/12/27 16:52:59 - opstart BI_SnelleFOD_CURRENT.sh - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : (stderr)  at java.base/java.lang.Thread.run(Thread.java:833)
2022/12/27 16:52:59 - opstart BI_SnelleFOD_CURRENT.sh - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : (stderr) org.apache.hop.core.exception.HopTransformException:
2022/12/27 16:52:59 - opstart BI_SnelleFOD_CURRENT.sh - ERROR (version 8.1.0.0-365, build 8.1.0.0-365 from 2018-04-30 09.42.24 by buildguy) : **(stderr) Key field [null] couldn't be found!**

Also in de gui, the key can not be selected! You can select it but it does not show:
![image](https://user-images.githubusercontent.com/5698326/209779679-e51e291d-3a45-4b77-b87a-f1750241d025.png)

Something is very wrong, we have to downgrade back to the 2.1 ...

### Issue Priority

Priority: 1

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
Relates to #2021

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
should be resolved, you can test with a latest version from [here](https://repository.apache.org/content/repositories/snapshots/org/apache/hop/hop-client/2.3.0-SNAPSHOT/)
