### ISSUE TITLE
[Bug]: Unexpected error evaluation condition on Filter Rows transform

### ISSUE THREAD

**Issue by sramazzina** [apache/hop#2110]
### Apache Hop version?

Just got a pull today from the main repository and rebuilt the sources

### Java version?

OpenJDK 64-Bit Server VM Temurin-11.0.17+8

### Operating system

Linux

### What happened?

By executing the very simple sample pipeline I attached, we are getting a java.lang.RuntimeException: Unexpected error evaluation condition. Same issue also on Win 10

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by sramazzina** [comment]
Anyone knows how to attache a raw .hpl file? Github is preventing me to upload that file. For this reason I uploaded my sample by compressing it

[filterrow-failing.zip](https://github.com/apache/hop/files/10320980/filterrow-failing.zip)

**Comment by hansva** [comment]
Zip is the only way that works, GitHub has some crazy restrictions...

https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/attaching-files

**Comment by sramazzina** [comment]
Just a little hint on my issue. I discovered that seems to happen whenever you set a condition by setting only the left and right side but without specifying the operator. If you set the operator too the issue didn't happen. For example if must set a condition like A = "B", the equal operator is already specified by default (so no need to set it) so you can set only the field A and the value "B"

**Comment by hansva** [comment]
So the error is actually correct ?

**Comment by sramazzina** [comment]
In my opinion no. I mean, it works if someone remember to re-set the = operator (that is set by default so this operation is not needed). Therefore in my opinion we must fix this weird behavior.
