### ISSUE TITLE
[Bug]: Unable to stop hop-server from command-line

### ISSUE THREAD

**Issue by duursma** [apache/hop#2115]
### Apache Hop version?

2.2

### Java version?

19.0.1

### Operating system

Windows

### What happened?

I started a hop-server on the localhost on port 8181.  If I try to kill it from the command line it reports that it can't find the server.

./hop-server.bat -kill  -u cluster -p cluster localhost 8181
org.apache.hop.www.HopServer$HopServerCommandException: "No Hop Server Server found at localhost:8181

If I query the status however I get a list of recently run pipelines
./hop-server.bat -gs -u cluster -p cluster localhost 8181

Pipelines: 2 found.

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Server

**Comment by gmitter-ef** [comment]
Hi! I am using 2.9.0 for a hop server using port 8080 for starting and the shutdown port 8079, via configuration file. No matter which command I use, when trying to kill it, the Hop server keeps saying: "No Hop Server Server found at ...".  I
Tried specifiying only 8080, only 8079, or both 8080 8079 in the --kill command.
E.g.:
hop-server.sh <servername> 8080 --kill --userName cluster --password <password>
hop-server.sh <servername> 8080 8079 --kill --userName cluster --password <password>

Other hop-server.sh commands using same hostname, port 8080 and same credentials work, however, only the "kill" seems to produce the "No hop server found" error.

Under Windows the same problem is present.

**Comment by hansva** [comment]
This feature was removed again because anyone could stop the server without credentials. The only way now is to kill the process

**Comment by bamaer** [comment]
reopened because the `--kill` option is still in the docs and in the CLI options.

**Comment by bamaer** [comment]
.take-issue

**Comment by hansva** [comment]
Or a new high prio ticket

**Comment by bamaer** [comment]
will be fixed in #4420
