### ISSUE TITLE
[Bug]: Action Email Validator missing

### ISSUE THREAD

**Issue by data-vader** [apache/hop#2117]
### Apache Hop version?

2.2

### Java version?

openjdk version "18.0.2-ea" 2022-07-19

### Operating system

Linux

### What happened?

The Action for validating Emails (https://hop.apache.org/manual/latest/workflow/actions/mailvalidator.html) can't be found.

1. Trying to select Action in a Workflow
![image](https://user-images.githubusercontent.com/33227772/210090675-afe6b91b-4f8c-4310-9298-f9c39b89bf20.png)

2. Trying to select Action in a Pipeline
![image](https://user-images.githubusercontent.com/33227772/210090789-60082036-5641-4e2a-80cb-e653f2ee6851.png)

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by hansva** [comment]
.take-issue

**Comment by sramazzina** [comment]
This action seems not to be present in actions' plugins directories. Wasn't that action ever migrated from PDI to Hop?

**Comment by hansva** [comment]
It's in our other plugin repository I'm going to migrate everything that we can from there to the main repository.
