### ISSUE TITLE
import pentaho ktr to apache hop 'TypeExitExcelWriterTransform' transform [Bug]: 

### ISSUE THREAD

**Issue by tilda-zz** [apache/hop#2142]
### Apache Hop version?

2.1

### Java version?

java 11

### Operating system

Windows

### What happened?

In pentaho data integration the output type excel was set to xlsx (Excel 2007 and above) 
After import into apache hop the <extension>xlsx</extension> was dropped. So the default xls was used. 

### Issue Priority

Priority: 1

### Issue Component

Component: Actions

**Comment by hansva** [comment]
.add-labels Import

**Comment by hansva** [comment]
@sramazzina , the PR has not been included in the code so this ticket is not resolved.
