### ISSUE TITLE
[Bug]: Target Field Name in Concat Fields transform can't be directly accessed

### ISSUE THREAD

**Issue by KBoersch** [apache/hop#2146]
### Apache Hop version?

2.2.0 & SNAPSHOT-20221202.082749-1

### Java version?

OpenJDK 11.0.16.1

### Operating system

Windows

### What happened?

The window of the "Concat Fields" tansform doesn't show up right (Image below).

It seems that the input fields for transform name and length of target field are stacked over the target field name field. So you can't directly click into the field or see what's in there. 

Problem occurs on hop web as well (pic 2)

![image](https://user-images.githubusercontent.com/111113919/212012329-fae5cb52-6895-4c95-882c-2a3c4cc28366.png)

![image](https://user-images.githubusercontent.com/111113919/212012832-88894c96-11e9-4df3-b6e0-9e50086dd1c3.png)

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
has been resolved with #2109

**Comment by KBoersch** [comment]
oh yeah, sry, could've searched in the closed section and missed to watch for new snapshots in 2.3.0 - my bad!
