### ISSUE TITLE
[Bug]: Null timestamps returned from Table Input transform

### ISSUE THREAD

**Issue by gustavomzina** [apache/hop#2169]
### Apache Hop version?

2.2

### Java version?

11.0.2

### Operating system

Windows

### What happened?

When selecting a timestamp column from any table on a postgresql database, null values are returned. Observed this behavior while using Table Input and Database Lookup transforms.

![Capturar](https://user-images.githubusercontent.com/11248706/213466385-3ee5247e-ec15-4c59-928c-2a550520edc6.PNG)

### Issue Priority

Priority: 1

### Issue Component

Component: Transforms

**Comment by nadment** [comment]
Work if supports Timestamp data type is enabled
![image](https://user-images.githubusercontent.com/39568358/214140848-fd63addf-629f-403f-9bf8-023aeae277de.png)
These options are reset when the database type is changed

**Comment by gustavomzina** [comment]
Thanks @nadment!
