### ISSUE TITLE
[Feature Request]: Allow JSR-223 scripting in a transform

### ISSUE THREAD

**Issue by mattcasters** [apache/hop#2190]
### What would you like to happen?

Matt Burgess wrote the "SuperScript" step over a decade ago and (as an ASF committer/PMC at Apache NiFi) has gracefully given permission to port this to Apache Hop:

https://github.com/mattyb149/pdi-scriptengine-plugin

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by terefang** [comment]
could this also be used as a row generator ?

**Comment by mattcasters** [comment]
Absolutely, we'll create an example.
