### ISSUE TITLE
[Bug]: Dimension lookup/update does not load/store "type of return field" in read only mode

### ISSUE THREAD

**Issue by matze42** [apache/hop#2221]
### Apache Hop version?

2.3

### Java version?

19.0.2

### Operating system

macOS

### What happened?

Cannot set the "type of return field" in dimension lookup/update node. 
Whatever I chose after closing and reopening the dialogue, "none" will be displayed. 
Upon running I get the error ... Please specify an update type for field nr 1 :  

Pls See below the screenshot from a pipeline where I tried to isolate the issue.
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/3817057/216381609-9e5c8948-a73e-46ce-8254-4ffb34973e28.png">

I have these issue sind Hop 2.2
In Hop 1.1. the same pipeline works without a problem

I am happy to support further troubleshooting. pls. let me know if/when more information is needed.

### Issue Priority

Priority: 2

### Issue Component

Component: Pipelines

**Comment by nadment** [comment]
The bug was introduced in version 2.2 with the XML cleanup.
But the "type of return field" information seems to be never used.
