### ISSUE TITLE
[Feature Request]: Default Open/Save Directory

### ISSUE THREAD

**Issue by stangwm** [apache/hop#2222]
### What would you like to happen?

Currently, the open and save file dialog default to the root default project instead of the current/most recent directory worked in. Would be nice for it to default in most recent directory or the directory the active pipeline/workflow

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
- It would also be nice to remember the sorting applied (sort on filename/date/...)
- We should also remember size/position of the window when closing and restarting HOP

**Comment by hansva** [comment]
.take-issue
