### ISSUE TITLE
Out how to make the right settings jdbc:clickhouse

### ISSUE THREAD

**Issue by suharevA** [apache/hop#2223]
Apache Hop version 2.0.0
Out how to make the right settings. Tables are not fully imported. For normal work on the part of dbeaver, and dataGrip made these settings
send_timeout=3600
receive_timeout=3600. And everything works. How can I make such settings in the driver properties in hop?
jdbc:clickhouse://url:port/default?socket_timeout=300000

Or similar to these settings

**Comment by hansva** [comment]
Hi @suharevA,

You can add extra options to the database connection in the options tab of the connection.
These will be added to the jdbc url.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/1140235/216548136-5c4c93e7-4e8a-401b-a0bd-faad12a1a4fe.png">
