### ISSUE TITLE
[Bug]: Cannot use encrypted passwords in environment for mongodb connections

### ISSUE THREAD

**Issue by gijoe88** [apache/hop#2241]
### Apache Hop version?

SNAPSHOT-20230206

### Java version?

11.0.18

### Operating system

Docker

### What happened?

```BASH
./hop-encrypt.sh -hop password
# Returns Encrypted 2be98afc86aa7f2e4bb18bd63c99dbdde
```

Create an environment DEV, with variable "MONGODB_PASSWORD" and value "Encrypted 2be98afc86aa7f2e4bb18bd63c99dbdde"

Create a connection to a MongoDB instance using this variable `${MONGODB_PASSWORD}` in the password field.

Launch a pipeline using the connection, see that the pipeline does not work, authentication failed.

I have tried putting unencrypted password in the environment, it does work.

It seems like the mechanism to use passwords in mongodb is not the same as relational databases, because in those the functionality of encrypted passwords inside environments is working (I did not try unencrypted passwords for those).

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by gijoe88** [comment]
My bad, relaunching the project did the trick.

**Comment by gijoe88** [comment]
Edit: unencrypted passwords in environment work. But encrypted passwords do not.

**Comment by hansva** [comment]
.take-issue
