### ISSUE TITLE
[Bug]: Call DB procedure transform doesn't allow variables in field 'connection'

### ISSUE THREAD

**Issue by KBoersch** [apache/hop#2255]
### Apache Hop version?

2.3.0

### Java version?

OpenJDK 11.0.16.1

### Operating system

Windows

### What happened?

When I'm trying to insert a variable in the field connection, I get the popup-message 'Please select a valid connection!' in the moment I try to click on 'OK'.

After opening the transform again, the field stays empty.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
Can you specify the transform the connection field has not been made variable aware in all of them.

**Comment by hansva** [comment]
I totally missed the transform name in the title, my bad

**Comment by KBoersch** [comment]
![image](https://user-images.githubusercontent.com/111113919/217766029-8c939330-d67f-4294-a9fa-0603cc976730.png)

**Comment by hansva** [comment]
@nadment was less blind than me and has already fixed it for this transform...
There are a couple of others that do not work (yet) I migrated the tickets for those from Jira to here now.
#2259, #2260, #2261, #2262, #2263, #2264, #2265, #2266
