### ISSUE TITLE
[Bug]: Microsoft excel input can't load heavy file

### ISSUE THREAD

**Issue by gwenael-mahe** [apache/hop#2307]
### Apache Hop version?

2.3.0

### Java version?

16.0.1

### Operating system

Windows

### What happened?

When opening an excel file with 5 sheet and around 90k rows each.
I tried loading only 1 sheet and limiting the number of rows to load but I alwyas have the error:
 Caused by: org.apache.poi.util.RecordFormatException: Tried to allocate an array of length 256,059,344, but the maximum length for this record type is 100,000,000.
If the file is not corrupt and not large, please open an issue on bugzilla to request 
increasing the maximum allowable size for this record type.
You can set a higher override value with IOUtils.setByteArrayMaxOverride()

I went on https://chat.project-hop.org/hop/channels/town-square and have been told to open an issue here and that it might be a regression from HOP or POI

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by hansva** [comment]
.take-issue
