### ISSUE TITLE
[Feature Request]: More intuitive zoom in / out navigation

### ISSUE THREAD

**Issue by harrisward** [apache/hop#2309]
### What would you like to happen?

When the user uses the scroll wheel to zoom in and out it looks like the focus point is fixed to a position on the canvas. Other tools allow you to zoom out move the mouse and then zoom in on the focal point of the mouse. This would allow people to navigate in and out (around) the canvas more easily.

Sample below

https://user-images.githubusercontent.com/6827832/218143945-c3a843b5-49a1-435b-b537-e905a600c54a.mp4

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by hansva** [comment]
.take-issue
