### ISSUE TITLE
[Task]: Simple pipeline logging sample/directions

### ISSUE THREAD

**Issue by hansva** [apache/hop#2332]
### What needs to happen?

Migration: https://issues.apache.org/jira/browse/HOP-4467

It would be ideal to have a simple pipeline logging setup example / or setup help guide to better understand how to make use of this for logging/reflection.

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by bamaer** [comment]
the pipeline logging transform is undocumented. 
the `documentationUrl` property in `src/main/java/org/apache/hop/reflection/pipeline/transform/PipelineLoggingMeta.java` points to `/logging/logging-reflection.html`. This is the documentation for the Pipeline Logging metadata type, not the Pipeline Logging transform.
