### ISSUE TITLE
[Bug]: Error trying to Explore MS SQL in docker hop-web:latest

### ISSUE THREAD

**Issue by hansva** [apache/hop#2346]
### Apache Hop version?

2.3

### Java version?

11

### Operating system

Windows

### What happened?

Migration: https://issues.apache.org/jira/browse/HOP-4195

When defining a connection to MS SQL (native) and click on test I get the following screen shot:
![image](https://user-images.githubusercontent.com/1140235/218984225-012d9cfb-89af-4b17-a1f9-51716d6a58e3.png)

But when I click on the explore button I get the following:
![image](https://user-images.githubusercontent.com/1140235/218984273-c5d202f3-b918-4fb9-add6-15a2d27abf3f.png)

An when I click the Cancel button:
![image](https://user-images.githubusercontent.com/1140235/218984301-f4f611bd-a350-499c-9ba9-e8356c4ed67b.png)

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Web

**Comment by bamaer** [comment]
confirmed in latest development SNAPSHOT-20230308
