### ISSUE TITLE
[Feature Request]: Drill down to running pipelines/workflows

### ISSUE THREAD

**Issue by hansva** [apache/hop#2360]
### What would you like to happen?

Migration: https://issues.apache.org/jira/browse/HOP-4166

As a data engineer I constantly need to create pipelines that are orchestrated by workflows. During the design process, it is important to visualize the execution of artifacts in small data samples, which is perfectly possible when we are working directly in the pipeline, but when I run through a workflow, with the pipeline still running, when I open the pipeline from the workflow it is not possible to view log, metrics or execution notation of transforms in pipelines.
This feature would be of great help to monitor the execution of workflow pipelines during the design process. The idea came to me from a group of Brazilian professionals who are implementing Hop in the companies they work for and everyone agrees that this functionality is needed.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by mattcasters** [comment]
This is the point of having an execution location active during execution which allows you to do exactly what is requested.

**Comment by mattcasters** [comment]
I suggest to close as "implemented".

**Comment by hansva** [comment]
you are right copied this one over a bit too fast
