### ISSUE TITLE
[Bug]: Workflow action - run_configuration xml entry present twice

### ISSUE THREAD

**Issue by hansva** [apache/hop#2361]
### Apache Hop version?

2.3

### Java version?

11

### Operating system

Windows

### What happened?

Migration: https://issues.apache.org/jira/browse/HOP-4160

In the hwf xml file, for actions of type "WORKFLOW", the "run_configuration" element is present twice.

### Issue Priority

Priority: 2

### Issue Component

Component: Actions

**Comment by nadment** [comment]
Issue will be fixed with  #2002
