### ISSUE TITLE
[Task]: Pass parameter in Hop Run

### ISSUE THREAD

**Issue by gugoan** [apache/hop#2374]
### What needs to happen?

Hi, I would like to validate the right way to pass a parameter in Hop Run, in the windows environment. 
I tried as instructed on the site and it did not work.

*: In Hop gui it works normally passing the value "2023-02" for the parameter "anomes"

`.\hop-run.bat -j ROTINA_SUPERA -r local -e PROD_ROTINA_SUPERA -f "C:\Apache Hop\Pipelines\ROTINA_SUPERA\ATUALIZACAO_SUPERA.hwf" -p anomes=2023-02`

![image](https://user-images.githubusercontent.com/1585443/219022461-fe1eb9cd-84ec-468c-898e-6b36779fbe26.png)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Run

**Comment by DAJGIT** [comment]
Hi, try with double quotes around the parameters, like this

.\hop-run.bat -j ROTINA_SUPERA -r local -e PROD_ROTINA_SUPERA -f "C:\Apache Hop\Pipelines\ROTINA_SUPERA\ATUALIZACAO_SUPERA.hwf" -p "anomes=2023-02"

**Comment by gugoan** [comment]
Don t work
I tried in the following ways:

`-p anomes=2023-02`
`-p "anomes=2023-02"`
`-p "anomes"="2023-02"`

**Comment by hansva** [comment]
In the [docs](https://hop.apache.org/manual/latest/hop-run/index.html) we specify the following 
`--parameters=key1="This value contains spaces",key2=value2`

**Comment by DAJGIT** [comment]
Sorry, I solved a similar case with hop-conf.bat and worked like this:

hop-conf.bat --config-file "C:\<YOUR_ENV_FILE_PATH>\env-variables.json" --config-file-set-variables "DB_HOSTNAME=localhost,DB_PASSWORD=abcd"

but it seems not the same for hop-run.bat

**Comment by gugoan** [comment]
@DAJGIT @hansva 
I don't understand very well, can you give me an example of how the syntax would look in my example?  I tried in countless ways

`.\hop-run.bat -j ROTINA_SUPERA -r local -e PROD_ROTINA_SUPERA -f "C:\Apache Hop\Pipelines\ROTINA_SUPERA\SUP_PROCESSAR_CHAVE.hpl" --parameters="anomes=2023-02"`

**Comment by DAJGIT** [comment]
Hi look at this example:
![image](https://user-images.githubusercontent.com/25872532/219082795-2dcd215e-c7fa-4514-91db-c1b6eb033aa3.png)

![image](https://user-images.githubusercontent.com/25872532/219082854-5387f603-b1c6-49f5-b5df-14c6ba487e22.png)

![image](https://user-images.githubusercontent.com/25872532/219083058-e2b76a0e-393c-4269-8f73-405531195577.png)

hop-run.bat -j Default -f TESTP1.hwf -p="P1=2023-02" works OK.

**Comment by DAJGIT** [comment]
In your case should be: 
.\hop-run.bat -j ROTINA_SUPERA -r local -e PROD_ROTINA_SUPERA -f "C:\Apache Hop\Pipelines\ROTINA_SUPERA\SUP_PROCESSAR_CHAVE.hpl" -p="anomes=2023-02"

**Comment by gugoan** [comment]
Did not work.
I forgot to mention that the parameter is for Worflow (which in turn is passed to each Pipeline).

![image](https://user-images.githubusercontent.com/1585443/219094918-47820980-d07e-40a2-9806-d5af76c33f3c.png)


![image](https://user-images.githubusercontent.com/1585443/219095091-52e16b34-52c8-4f14-bbb9-ecaf832ba25b.png)

**Comment by gugoan** [comment]
I realized that in my case, the command is 'breaking' the value=key of the parameter, and ends up being separated as if it were another argument passed. 

Could this be the cause of the problem?

![image](https://user-images.githubusercontent.com/1585443/219097149-b221cb24-d1ba-4dc6-8369-a6afe9984fb5.png)

**Comment by DAJGIT** [comment]
Look in command to start hop, PowerShell is erasing the double quotes:
![image](https://user-images.githubusercontent.com/25872532/219097525-39a069ac-e7cc-4d23-823e-687539d28ed6.png)

The problem is in PowerShell,  open a CMD console and it will work  ( %windir%\system32\cmd.exe)

**Comment by hansva** [comment]
I would indeed test if it works in CMD first. if it does there you might have to escape the " in powershell and turn it into `-p=\"anomes=2023-02\"`

**Comment by gugoan** [comment]
Very good! 
It worked like this and it also worked with single quotes followed by double quotes:

`.\hop-run.bat -j ROTINA_SUPERA -r local -e PROD_ROTINA_SUPERA -f "C:\Apache Hop\Pipelines\ROTINA_SUPERA\ATUALIZACAO_SUPERA.hwf" -p=\"anomes=2023-02\"`

`.\hop-run.bat -j ROTINA_SUPERA -r local -e PROD_ROTINA_SUPERA -f "C:\Apache Hop\Pipelines\ROTINA_SUPERA\ATUALIZACAO_SUPERA.hwf" -p='"anomes=2023-02"'`

Thanks so much ^^
