### ISSUE TITLE
[Bug]: Top tool bar is break

### ISSUE THREAD

**Issue by openinbigdata** [apache/hop#2390]
### Apache Hop version?

2.4

### Java version?

11

### Operating system

macOS

### What happened?

The top toolbar always appears broken as you can see in the attached image.

I have a 13.3-inch MacBook Air M1 and the hop-gui interface doesn't seem to automatically match my resolution.

<img width="1280" alt="13 3-inch" src="https://user-images.githubusercontent.com/43577679/219353752-1f076159-6bdb-49f6-8a70-ca48ec4d45c6.png">

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by openinbigdata** [comment]
The same happened in versions that I test: 2.3, 2.2 and 2.1

**Comment by hansva** [comment]
which java version are you using? is this an ARM java or is it using rosetta?

**Comment by openinbigdata** [comment]
There is no problem with Hop, the reason for the breakage is because I have multiple monitors, when turned off, the bar is normal
