### ISSUE TITLE
[Feature Request]: allow additional file operations in the file explorer perspective

### ISSUE THREAD

**Issue by bamaer** [apache/hop#2437]
### What would you like to happen?

the file explorer perspective should have more "real" file explorer functionalities: 
- drag and drop to move between folders 
- rename, copy, delete a file
- show/edit properties
- create a hop-run command for the selected file

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
Allow the selection of several files

**Comment by nadment** [comment]
Add F3 shortcut to open selected file in explorer
Add context menu
![image](https://github.com/user-attachments/assets/8dc4475c-e784-4e8f-a1d8-955818fb8d12)
