### ISSUE TITLE
[Bug]: Hop is shipped with jdbc driver of mssqlnative. Should it?

### ISSUE THREAD

**Issue by gijoe88** [apache/hop#2445]
### Apache Hop version?

2.3.0 and Development

### Java version?

11.0.18

### Operating system

Windows

### What happened?

In the zip downloaded
![image](https://user-images.githubusercontent.com/963155/220071244-16616eec-9884-4fb7-8144-3ffb034e17c4.png)

In the docker for hop-web
```BASH
docker run --rm --name hop-mssql apache/hop-web:Development ls -al --color /usr/local/tomcat/plugins/databases/mssqlnative/lib
# total 1192
# drwxr-xr-x 2 root root    4096 Feb 17 09:02 .
# drwxr-xr-x 3 root root    4096 Feb 17 09:02 ..
# -rw-r--r-- 1 root root 1209660 Nov 14  2019 mssql-jdbc-7.4.1.jre8.jar
```

In the docker for hop-server
```BASH
docker run -d --rm --name hop-mssql apache/hop:Development
docker exec -it hop-mssql ls -al --color /opt/hop/hop/plugins/databases/mssqlnative/lib
# total 1192
# drwxr-xr-x    2 hop      hop           4096 Feb 17 09:02 .
# drwxr-xr-x    3 hop      hop           4096 Feb 17 09:02 ..
# -rw-r--r--    1 hop      hop        1209660 Nov 14  2019 mssql-jdbc-7.4.1.jre8.jar
```

The packages all come with a JDBC driver for mssqlnative shipped inside. According to the [help page](https://hop.apache.org/manual/latest/database/databases/mssqlnative.html), this should not be the case, and a download link is provided.

### Issue Priority

Priority: 3

### Issue Component

Component: Other

**Comment by bamaer** [comment]
shipping with the MS SQL native JDBC driver is not a problem, as this driver is distributed with the MIT license. 
we could definitely upgrade to a [newer](https://mvnrepository.com/artifact/com.microsoft.sqlserver/mssql-jdbc/12.2.0.jre11) driver version.
