### ISSUE TITLE
[Bug]: Can't select Y/N from the combo box in "Replace in string" transform

### ISSUE THREAD

**Issue by enricomariam42** [apache/hop#2463]
### Apache Hop version?

2.3.0

### Java version?

openjdk version "11.0.9.1" 2020-11-04 OpenJDK Runtime Environment (build 11.0.9.1+1-post-Uos-1deb10u2) OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Uos-1deb10u2, mixed mode, sharing)

### Operating system

Linux

### What happened?

In "Replace in string" transform from the combo box I get the values:
!System.Combo.YES!
!System.Combo.NO!

and always results in "N"

![Screenshot_seleziona-area_20230223142925](https://user-images.githubusercontent.com/4611287/220922655-47ffb7ff-410a-4de9-b4c7-2807f7f43d34.jpg)

Typing "Y" works.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
Already fixed #2240 thanks for reporting!

**Comment by pauloricardoferreira** [comment]
thanks
