### ISSUE TITLE
[Feature Request]: Configurable colors on the metrics panel / log panel - in pipline/workflow dialog

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#2477]
### What would you like to happen?

![image](https://user-images.githubusercontent.com/1233654/221370807-880ea919-3edf-4c4e-8e42-126e22896796.png)

The latest bright orange and black hurt my eyes.  I need this to be configurable and would prefer by default it matched with the rest of the UX.

However, I do see a use for setting the color on a per execution engine basis "local pipeline", "local workflow", "remote pipeline", "remote workflow" etc.   I may have different files that I want to work on locally and then test remotely within the same project.  It would be nice to see a color for the metrics and log tabs at the runner level so it shows in the main UX when we run it.

Minimum: Picking a background color.
Best: Let me pick background and foreground.  (I would create enough contrast to be pleasing to the eyes.)

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by nadment** [comment]
It's a debugging residue, I'll fix it because probably my fault.
