### ISSUE TITLE
[Bug]: i18n tooltip show/hide execution result on workflow

### ISSUE THREAD

**Issue by nadment** [apache/hop#2479]
### Apache Hop version?

2.4.0-SNAPSHOT

### Java version?

11

### Operating system

Windows

### What happened?

![image](https://user-images.githubusercontent.com/39568358/221384632-ba9a72d4-cb81-41c7-8444-0fc63a5cf38d.png)

### Issue Priority

Priority: 3

### Issue Component

Component: Workflows

**Comment by hansva** [comment]
.take-issue
