### ISSUE TITLE
[Bug]: hop-run.bat: Option for Shared_JDBC_Folder incorrect

### ISSUE THREAD

**Issue by ggrohmann** [apache/hop#2492]
### Apache Hop version?

2.3

### Java version?

11

### Operating system

Windows

### What happened?

![grafik](https://user-images.githubusercontent.com/22274758/222144803-3b17e193-2dc3-4d06-8321-a07d42a155d2.png)

There is a typo: Instead of %HOP_SHARED_JDBC_FOLDER% there is written %**D**HOP_SHARED_JDBC_FOLDER%

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
Nice catch, thank you for reporting!
