### ISSUE TITLE
Concat Fields panel Target Field Name is obscured [Bug]: 

### ISSUE THREAD

**Issue by davepgenxvs** [apache/hop#2495]
### Apache Hop version?

2.2.0

### Java version?

openjdk 19.0.1

### Operating system

Windows

### What happened?

In the Concat Fields panel, the Target Field Name field name is obscured. There should be five? text fields and five labels, but there are four labels and five fields with one field obscured. (I can tab to it as a workaround :)  )

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by hansva** [comment]
can we get a screenshot? I'm not sure what you mean. It might also be related to the Java version our target version is Java 11

**Comment by davepgenxvs** [comment]
Please close. I didn't realize 2.3 was released and it's fixed there. Thank you!

**Comment by davepgenxvs** [comment]
Fixed in 2.3

**Comment by hansva** [comment]
even better! I love it when problems are already solved ;)
