### ISSUE TITLE
[Bug]: The Jdbc driver provided for Intersystems Caché is bad.

### ISSUE THREAD

**Issue by nadment** [apache/hop#2496]
### Apache Hop version?

2.3

### Java version?

Java 11

### Operating system

Windows

### What happened?

Something is wrong with the intersystems-jdbc-3.0.0.jar file provided with Hop, only 1K and no class inside
https://community.intersystems.com/post/why-not-update-jdbc-driver-mvnrepository

It is necessary to remove the JDBC driver that is currently provided.

See #2515 

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by hansva** [comment]
.take-issue
