### ISSUE TITLE
[Bug]: Hop Server inaccessible after Jetty upgrade 

### ISSUE THREAD

**Issue by bamaer** [apache/hop#2521]
### Apache Hop version?

SNAPSHOT-20230307

### Java version?

openjdk version "11.0.18" 2023-01-17

### Operating system

Linux

### What happened?

after the [Jetty upgrade](https://github.com/apache/hop/pull/2508/files#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8) in PR 2508

Issue disappeared after building with a reverted Jetty version, back to `9.4.35.v20201120`. 

curl -u cluster   http://localhost:8998
Enter host password for user 'cluster':
```
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 403 Forbidden</title>
</head>
<body><h2>HTTP ERROR 403 Forbidden</h2>
<table>
<tr><th>URI:</th><td>/</td></tr>
<tr><th>STATUS:</th><td>403</td></tr>
<tr><th>MESSAGE:</th><td>Forbidden</td></tr>
<tr><th>SERVLET:</th><td>-</td></tr>
</table>
<hr/><a href="https://eclipse.org/jetty">Powered by Jetty:// 9.4.51.v20230217</a><hr/>
</body>
</html>
```

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by usbrandon** [comment]
Fantastic sleuthing!
