### ISSUE TITLE
[Bug]: Step Replace String

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#2522]
### Apache Hop version?

2.3.0

### Java version?

java 11.0.15 2022-04-19 LTS

### Operating system

Windows

### What happened?

Hello, I found a Bug in Step Replace String.

The bug is in the selection of Use Regexp or Not.

If you put the letters Y or N, the error does not appear, but in the selection of options it is like the image below, then it does not save

![image](https://user-images.githubusercontent.com/70301866/223566636-5c3cb038-0e16-4a24-98e4-a268e209a41a.png)

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
Fixed with #2463
