### ISSUE TITLE
[Bug]: SQL Transform: Inserted variable disappears after click on OK

### ISSUE THREAD

**Issue by KBoersch** [apache/hop#2542]
### Apache Hop version?

SNAPSHOT 2.4.0-20230309.141645-1

### Java version?

open jdk 11.0.16.1

### Operating system

Windows

### What happened?

After inserting a variabel in the field "Connection" everything seems to be OK.

When I click on "OK" and open the transform again, the field is empty. No Errormessage, no warning.

I know that I've done that before, so the field should be allowed to receive variables.

Before OK
![image](https://user-images.githubusercontent.com/111113919/224272874-555d29a4-b4b2-444d-a235-425f3dbe2f95.png)

After OK - just went away
![image](https://user-images.githubusercontent.com/111113919/224272940-7c638b4a-2773-4303-9a99-a00d90ba84c4.png)

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
confirmed, not all actions and transforms support variable substitution yet on the database connections. The SQL action is one of them.
