### ISSUE TITLE
[Bug]: Apache Hop Web docker image runs with root privileges and it can write into external volumes shared with another docker compose services with the risk it involves...

### ISSUE THREAD

**Issue by pablo-fernandez-cuadros** [apache/hop#2561]
### Apache Hop version?

latest at this report

### Java version?

latest at this report

### Operating system

Docker

### What happened?

[Bug]: Apache Hop Web docker image runs with root privileges and it can write into external volumes shared with another docker compose services with the risk it involves...

### Issue Priority

Priority: 0

### Issue Component

Component: Hop Web

**Comment by paulogomes** [comment]
I saw that in "Dockerfile" has a adduser command but on Dockerfile.web there isn't...

I think that this is the problem.

**Comment by paulogomes** [comment]
I add some lines in the 'Dockerfile.web' to create and use a non-root user.

```
RUN groupadd -r hop -g 501
RUN useradd -d /home/hop -u 501 -m -s /bin/bash -g hop hop
RUN chown -R hop:hop /usr/local/tomcat
USER hop
```

Do you think this is a good approach to solve this issue?

if so, i can create a pull request for this issue.

**Comment by hansva** [comment]
I made a PR feel free to take a look #3070
