### ISSUE TITLE
[Task]: Document Hop internal variables

### ISSUE THREAD

**Issue by hansva** [apache/hop#2642]
### What needs to happen?

Migration: https://issues.apache.org/jira/browse/HOP-3850

Variables like ${Internal.Transform.CopyNr} are not yet documented.

I would add a section here: https://hop.apache.org/manual/latest/variables.html

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by Adalennis** [comment]
.take-issue

**Comment by Adalennis** [comment]
Check and update internal variables references:
https://hop.apache.org/manual/latest/workflow/actions/workflow.html
https://hop.apache.org/manual/latest/workflow/actions/pipeline.html
https://hop.apache.org/manual/next/pipeline/transforms/pipeline-executor.html
