### ISSUE TITLE
[Feature Request]: Option to change a transform's label background color

### ISSUE THREAD

**Issue by hansva** [apache/hop#2646]
### What would you like to happen?

Migration: https://issues.apache.org/jira/browse/HOP-3856

Please add an option to change a transform's label background color / set it to transparent / change its opacity.
A hop's symbol is barely visible if two transforms are very close to each other. Also, I find that the GUI appears clearer and less cluttered when the label is "transparent" (compare hop vs. spoon).
 
 
 

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
With the new ui to mimic a hyperlink #3335, this request is obsolete.
