### ISSUE TITLE
[Task]: Enable the Google Analytics transform to connect the GA4 API

### ISSUE THREAD

**Issue by hansva** [apache/hop#2657]
### What needs to happen?

Migration: https://issues.apache.org/jira/browse/HOP-3982

The Google Analytics transformation currently connects Google Analytics Universal version 3, however there is a new version of GA, GA4 (4 does not mean version 4, in fact this new API is in version 1) that the transformation does not read and that's why it needs a refactoring to allow reading this new version of GA.

Below the error when you try to connect a GA4
IOException: User does not have sufficient permissions for this profile.
Root cause: GoogleJsonResponseException: 403 Forbidden
GET https://www.googleapis.com/analytics/v3/data/ga?dimensions=ga:browser&end-date=2022-05-04&ids=ga:211279119&max-results=1&metrics=ga:visits&samplingLevel=FASTER&sort=ga:visits&start-date=2022-05-04
{
  "code" : 403,
  "errors" : [

{     "domain" : "global",     "message" : "User does not have sufficient permissions for this profile.",     "reason" : "insufficientPermissions"   }

],
  "message" : "User does not have sufficient permissions for this profile."
}

Here is a reference to the documentation of this new API
https://developers.google.com/analytics/devguides/reporting/data/v1/rest

ATTENTION: Your GA account needs to be migrated to GA4

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by bamaer** [comment]
the GA4 is a complete rewrite, there is no upgrade path from GA3. this will be a new transform.
