### ISSUE TITLE
[Bug]: Cannot connect to mysql on hop-web

### ISSUE THREAD

**Issue by hungnguyen259** [apache/hop#2685]
### Apache Hop version?

2.2.0

### Java version?

11.0.16

### Operating system

Linux

### What happened?

I'm using Hop web. I'm trying to connect to mysql on local. 
I move mysql-connector-java-8.0.13 to usr/local/tomcat/plugins/databases/mysql/lib. When i choose Test button, the connection is successful but when i choose Explore, i get  an error. It runs non stop (Apache Hop is running a long running task),  and then show errors: InvocationTargetException: Problem encountered getting information from the database: java.lang.IllegalStateException: Invalid thread access. 
![image](https://user-images.githubusercontent.com/83303113/226278735-be752c0b-801c-447a-9a85-8a967c204e4c.png)
![image](https://user-images.githubusercontent.com/83303113/226278933-c111c142-7710-44ee-addc-2263ed154743.png)

### Issue Priority

Priority: 3

### Issue Component

Component: Database, Component: Hop Web

**Comment by hansva** [comment]
Could you try with hop-web:Development container it should have been resolved with #2346 and is part of the 2.4 release

**Comment by hansva** [comment]
confirmed it was a bug in 2.3, confirmed it was fixed in 2.4
