### ISSUE TITLE
[Bug]: Beam direct runner JUnit tests fail on windows

### ISSUE THREAD

**Issue by hansva** [apache/hop#2688]
### Apache Hop version?

2.4

### Java version?

11

### Operating system

Windows

### What happened?

Migration: https://issues.apache.org/jira/browse/HOP-4462

For some reason the Direct runner tests fail on Windows.

This is perhaps caused by a path error.

I suggest to move everything to integration tests.  We do need to test somehow that the pipelines do work on Windows though.

### Issue Priority

Priority: 3

### Issue Component

Component: Beam

**Comment by gvdutra** [comment]
Hello @hansva, I tried to reproduce this issue but I couldn't. Could you please give me more information? I tried running BeamDirectPipelineEngineTest.java and worked ok.

**Comment by hansva** [comment]
I just copied over the original ticket, if you can't reproduce on your system in Windows we can close this and see if it ever comes back 😄
