### ISSUE TITLE
[Task]: BigQuery JDBC: document which libs are needed from the Simba Driver

### ISSUE THREAD

**Issue by hansva** [apache/hop#2739]
### What needs to happen?

Migration: https://issues.apache.org/jira/browse/HOP-3678

The Simba driver comes with a bunch of extra libs.

We should document which libs are needed to get it working in Hop

### Issue Priority

Priority: 3

### Issue Component

Component: Database, Component: Documentation

**Comment by gitmstoute** [comment]
While troubleshooting Relational Database Connection with Google Bigquery I saw errors like:
`Error in the Hop GUI : io.grpc.ManagedChannelProvider: io.grpc.netty.NettyChannelProvider not a subtype
java.util.ServiceConfigurationError: io.grpc.ManagedChannelProvider: io.grpc.netty.NettyChannelProvider not a subtype
    at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)`


These were resolved by removing these jars packaged with with the simba drivers:
```
grpc-alts-1.54.0.jar
grpc-api-1.54.0.jar
grpc-core-1.54.0.jar
grpc-netty-shaded-1.54.0.jar
```

**Comment by gitmstoute** [comment]
From the latest SimbaJDBC driver (1.3.3.1004 at this moment) it looks to be working with this set of jars:
```
api-common-2.9.0.jar
gax-2.26.0.jar
gax-grpc-2.26.0.jar
google-api-services-bigquery-v2-rev20230422-2.0.0.jar
GoogleBigQueryJDBC42.jar
google-cloud-bigquerystorage-2.36.1.jar
grpc-google-cloud-bigquerystorage-v1-2.36.1.jar
grpc-google-cloud-bigquerystorage-v1beta1-0.160.1.jar
grpc-google-cloud-bigquerystorage-v1beta2-0.160.1.jar
proto-google-cloud-bigquerystorage-v1-2.36.1.jar
proto-google-cloud-bigquerystorage-v1beta1-0.160.1.jar
proto-google-cloud-bigquerystorage-v1beta2-0.160.1.jar
threetenbp-1.6.8.jar
```
I haven't tested all authentication methods.

**Comment by gitmstoute** [comment]
Here is a PR to resolve this issue.
https://github.com/apache/hop/pull/3030/commits/73849659b079c7413919806c642b3535d3372735

**Comment by gitmstoute** [comment]
@hansva Sorry looks like I missed one jar in my `include` list somehow. 
Is there a way I can add it to the list? `json-<VERSION>.jar`

**Comment by hansva** [comment]
in the include or exclude section?

**Comment by gitmstoute** [comment]
Include section please!

**Comment by hansva** [comment]
done!
