### ISSUE TITLE
[Bug]: DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true

### ISSUE THREAD

**Issue by hansva** [apache/hop#2744]
### Apache Hop version?

2.3

### Java version?

11

### Operating system

Windows

### What happened?

Migration: https://issues.apache.org/jira/browse/HOP-4004

I was trying to read an XMl file in Apache hop but got following error :

2022/06/18 12:11:58 - XXXXX - ERROR: Could not open file #1 : s3:///xxxx.xml --> org.apache.hop.core.exception.HopException: 2022/06/18 12:11:58 - XXXXX - org.dom4j.DocumentException: Error on line 2 of document file:///D:/Users/tbali/Downloads/apache-hop-client-2.0.0/hop/UTF-8 : DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true. 2022/06/18 12:11:58 - XXXXX - Error on line 2 of document file:///D:/Users/tbali/Downloads/apache-hop-client-2.0.0/hop/UTF-8 : DOCTYPE is disallowed when the feature "http://apache.org/xml/features/disallow-doctype-decl" set to true.

This was working fine in the version 1.2.0 but it started occurring in version 2.0.0 

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by gvdutra** [comment]
Hello, @hansva could you please post an example of the XML you were trying to read from?

**Comment by hansva** [comment]
Hi Gabriel,

This Issue has been migrated from Jira so I'm not the actual owner. That being said I do know where the error comes from.
This is a sample XML file that will generate the "problem" (which actually is not a problem but a well considered action on our side)
[xml-with-doctype.txt](https://github.com/apache/hop/files/11904172/xml-with-doctype.txt)

The problem probably comes from following line in our [XmlParserFactoryProducer](https://github.com/apache/hop/blob/c2ce039b38266dfa4718212e92edf6972e74afc8/core/src/main/java/org/apache/hop/core/xml/XmlParserFactoryProducer.java#L44) or from Dom4JUtil.java.

My idea for a possible solution would be to add an extra tab named "Security" next to the Fields tab in the Get data from XML transform:
<img width="988" alt="Screenshot 2023-06-29 at 11 30 55" src="https://github.com/apache/hop/assets/1140235/8345fd60-f975-4052-8e96-bb321bc9a28d">

There the user should be able to disable specific security features such as the `disallow-doctype-decl` or `load-external-dtd` It can not be a general lowering of the security measures we put in place to avoid external code execution.
