### ISSUE TITLE
[Bug]: Neo4j Output UI glitch

### ISSUE THREAD

**Issue by hansva** [apache/hop#2745]
### Apache Hop version?

2.3

### Java version?

11

### Operating system

Windows

### What happened?

Migration: https://issues.apache.org/jira/browse/HOP-4009

When you have used “Get Fields” on the Neo4J Output to pull out all the fields from a CSV… # select the top 3 fields at the same time, for example.

Right click and select “Delete selected lines”
it deletes the lines but if you click back to the first line, the first column changes back to the original field

### Issue Priority

Priority: 3

### Issue Component

Component: Neo4j

**Comment by bamaer** [comment]
can't reproduce in 2.5.0-SNAPSHOT 20230331

**Comment by hansva** [comment]
Close and see if it ever comes back....
