### ISSUE TITLE
[Bug]: Updated System Variable values from a Configuration perspective is not reflecting in Pipeline?

### ISSUE THREAD

**Issue by kirana-ks** [apache/hop#2779]
### Apache Hop version?

2.3.0

### Java version?

11.0.14

### Operating system

Windows

### What happened?

When working with System variables (HOP-GUI -> Configuration perspective) the updated values are not reflecting in the Pipeline. 
However, after restarting the HOP-GUI it works as expected.

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Config

**Comment by mattcasters** [comment]
Is this still the case in the last version of Hop?

**Comment by nadment** [comment]
Just tested with version 2.8 and it works.
