### ISSUE TITLE
[Bug]: Cartesian Product does not work on flows with the same row names

### ISSUE THREAD

**Issue by Hymmen** [apache/hop#2793]
### Apache Hop version?

2.3.0

### Java version?

11

### Operating system

Windows

### What happened?

We have created a simple pipeline to show our problem with some of our from Kettle imported transformations. We have two data flows that will be joined through a cartesian product. The pipelines that are problematic share at least one row with the same name leading to a cartesian product and later on want to remove the [row name]_1 . In the logs you can find that it cannot find [row name]_1 in the flow, so that it can't delete it. The pipeline stays in the status idle.
[test3.zip](https://github.com/apache/hop/files/11119471/test3.zip)

"Show output fields" selected on the cartesian product also ony shows one of the versions with the same name. Expected behaviour would be to find the second one with an attached _1 to the row name.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by mattcasters** [comment]
If you say "Row with the same name", do you mean "field with the same name?"

**Comment by Hymmen** [comment]
Yes, I do. Both rows contain a field with the samen name.

**Comment by mattcasters** [comment]
I don't get the error on the latest build I've tested with but I can confirm there is a discrepancy between the transform output row metadata and the actual rows being produced by the transform.

**Comment by mattcasters** [comment]
This is a result of a porting issue where Hop Metadata no longer carries a state nor variables. This requires a breaking API change (3.x), so for the time being I'll figure out a workaround.
