### ISSUE TITLE
Could you please enable pl-PL language on https://translate.project-hop.org?

### ISSUE THREAD

**Issue by gosforth** [apache/hop#2799]
Hi,

Could you please enable pl-PL language on https://translate.project-hop.org?
We'd like to contribute in translation.

Regards,

G.

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
Index is still updating on https://translate.project-hop.org/ but Polish has been added as a language

**Comment by gosforth** [comment]
Thank you!
