### ISSUE TITLE
[Bug]: Action buttons in the HOP SERVER Status Page is not rendering correctly

### ISSUE THREAD

**Issue by kirana-ks** [apache/hop#2803]
### Apache Hop version?

2.4.0

### Java version?

11.0.14

### Operating system

Windows

### What happened?

Action buttons in the HOP Status page like Run , Stop, Cleanup, View and Remove buttons are not rendering correctly. 

Please find the screenshot for more details.

![HOP Status Page](https://user-images.githubusercontent.com/31061958/229483406-94b1e524-9987-4f89-ab73-ec77b15a883f.jpg)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Server

**Comment by bamaer** [comment]
can't reproduce with a local Hop Server or through the container. 
can you provide some more details on how you start the server and the steps to reproduce?

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
Cannot reproduce with Hop Server on Windows.
Feel free to reopen with more details on how you started the server and if you are still having the issue
