### ISSUE TITLE
[Task]: Apache Hop Cluster Doubt

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#2804]
### What needs to happen?

I have a doubt.

Is it possible to create an Apache Hop Server cluster?

I read the documentation and couldn't find it.

Thanks

### Issue Priority

Priority: 3

### Issue Component

Component: Other

**Comment by hansva** [comment]
there is no clustering with load balancing available. That being said we do have transforms to query the workload on multiple hop servers and you could use that information to launch a pipeline on a different server.
https://hop.apache.org//manual/latest/pipeline/transforms/serverstatus.html

So you could create one master server that checks the loads on multiple servers and redirect the execution to the other server. Depending on where (cloud?) you are running the servers you could also leverage the load balancers of the vendor to distribute load.

**Comment by pauloricardoferreira** [comment]
Tks
