### ISSUE TITLE
[Bug]: Properties Input crashes when you try to edit in the GUI or during pipeline run

### ISSUE THREAD

**Issue by ricozen** [apache/hop#2825]
### Apache Hop version?

2.4

### Java version?

openjdk version "11.0.16.1" 2022-08-12 LTS

### Operating system

Windows

### What happened?

Download the last release 2.4 and unzip Hop
Launch the gui.bat
Add a new pipeline in default project  
Add a Properties Input step in the pipeline
Try to edit the step

Result : 
The GUI show a modal "unable to open dialog for this transform"
Detailed error : IllegalArgumentException: Argument cannot be null
Root cause: IllegalArgumentException: Argument cannot be null

Expected Result : we should have the Property Input gui to edit the action (last version ok was 2.1)
This step is important to read environnement variables as they were before in Pentaho...
Regards

### Issue Priority

Priority: 1

### Issue Component

Component: Transforms

**Comment by bamaer** [comment]
confirmed in latest build
