### ISSUE TITLE
[Bug]: Salesforce upsert transform: selection of single stream field is not working

### ISSUE THREAD

**Issue by liosc** [apache/hop#2830]
### Apache Hop version?

2.3.0

### Java version?

jdk-11.0.15.10

### Operating system

Windows

### What happened?

The selection of a single stream field in the fields table (second column) is not working, as if there was no input stream but the "Edit mapping" and "Get fields" are working (showing correctly all the fields) and the "Show input fileds" function gives back all the fields in the stream.

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by sramazzina** [comment]
Tested on Hop 2.5 and everything works. I'm going to close the issue.
