### ISSUE TITLE
[Bug]: ETL metadata Injection into Data Grid truncates string at comma

### ISSUE THREAD

**Issue by fraserward** [apache/hop#2831]
### Apache Hop version?

2.3.0

### Java version?

opernjdk 11.0.16.1

### Operating system

Windows

### What happened?

I have queries that included commas in their structure.  When these are metadata injected into the Data Grid transform the they become truncated at the first instance of a comma.  

I have got around this by injecting instead into a Generate Rows transform.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
The data grid receives all its data fields in 1 column. by default "," is used to split the fields. You can specify the delimiter used. https://hop.apache.org//manual/latest/pipeline/transforms/datagrid.html#_metadata_injection_support

**Comment by fraserward** [comment]
Its in the docs... https://hop.apache.org//manual/latest/pipeline/transforms/datagrid.html#_metadata_injection_support
