### ISSUE TITLE
[Bug]: JSON Output step only consumes rows equal to its bloc size setting or greater

### ISSUE THREAD

**Issue by bobcortera** [apache/hop#2839]
### Apache Hop version?

2.4 Release

### Java version?

OJDK 11

### Operating system

Windows

### What happened?

While trying to feed a web service with batches of JSON formatted rows and the bloc size set to 500 the pipeline transformation only processed batches of rows where the number of rows left were >= to the bloc size.  Thus for an input of 600 blocks to above JSON Output step, only 500 were processed, the rest were ignored.  The transform works fine as long as the number of input rows is a multiple of the bloc size (such as the default of 1).

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by bobcortera** [comment]
I've also found that it won't write any data if the number of input rows is less than the bloc size.

**Comment by bobcortera** [comment]
[broken_json_output.txt](https://github.com/apache/hop/files/11298789/broken_json_output.txt)

**Comment by hansva** [comment]
.take-issue
