### ISSUE TITLE
[Bug]: Can't pipes be used separately with the Hop remote workflow engine?

### ISSUE THREAD

**Issue by liurulin1993** [apache/hop#2866]
### Apache Hop version?

2.0.0

### Java version?

java 11

### Operating system

Windows

### What happened?

I did not respond to the Hop remote workflow engine when executing the pipeline separately. The server did not find any dependent files in the component, only a zip package, which was not included. How did the Hop server obtain these dependent files?

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Config

**Comment by bamaer** [comment]
you can run individual pipelines or workflows on a remote hop server. 
the remote run configurations have an option to [export linked resources](https://hop.apache.org/manual/latest/workflow/workflow-run-configurations/native-remote-workflow-engine.html#_export_linked_resources_to_server) to export child worfklows/pipelines etc to the server. 

this is not a bug, feel free to join the [chat](https://chat.project-hop.org) to ask questions.
