### ISSUE TITLE
[Bug]: Auth error on git push/pull from Hop Gui

### ISSUE THREAD

**Issue by bamaer** [apache/hop#2869]
### Apache Hop version?

2.4.0

### Java version?

openjdk version "11.0.18" 2023-01-17

### Operating system

Windows

### What happened?

https://lists.apache.org/thread/kdcdb2bq8y59h86dxkq7k35bxq0srwhs

![image001](https://user-images.githubusercontent.com/948257/234764068-b8fde819-6c33-47ba-be11-0b1bdd9083b1.png)

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by ssssaaamm** [comment]
Confirming these bug, However, I couldn't see the detailed log (with the stack trace).

I'm using Apache Hop version 2.4.0 and java version "11.0.18" 2023-01-17 LTS, in a Windows computer. Added git remotes through git bash, but when I try to push/pull I'm being asked for git username and password in an infinite loop and it doesn't push or pull.

**Comment by hansva** [comment]
Going to close this one and keep #3485
