### ISSUE TITLE
[Task]: Updating dependencies

### ISSUE THREAD

**Issue by KBoersch** [apache/hop#2957]
### What needs to happen?

It's an update to issue the following issue: https://github.com/apache/hop/issues/2250 

I know that the majority of vulnerabilities is caused by other libraries like beam and you can't do much about that, but there are some dependencies you can update - I guess.

[Trivy scan 2.4.0.xlsx](https://github.com/apache/hop/files/11540718/Trivy.scan.2.4.0.xlsx)

Thanks for the great work.

### Issue Priority

Priority: 2

### Issue Component

Component: Other

**Comment by hansva** [comment]
Thanks @KBoersch , maybe we should take a look to include Trivy scans in our daily process so we at least get the overview.

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
Follow up ticket for next release:
https://github.com/apache/hop/issues/2973

**Comment by hansva** [comment]
I have updated the dependencies we have control over.
With Hop 2.6 (not current but next release) I will be focussing on making a couple of flavors of our images.
This way you can also use a container that doesn't include Beam which would contain less libraries.
