### ISSUE TITLE
[Bug]: incorrect tooltip at JSON input, YAML input and get data from XML

### ISSUE THREAD

**Issue by dkuehn85** [apache/hop#2968]
### Apache Hop version?

2.4.0

### Java version?

17.0.7.7

### Operating system

Windows

### What happened?

For the transformations JSON input, YAML input and get data from XML, the tooltip for the checkbox "Use field as file names" is wrong. The displayed tooltip is "Check this option if source if a filename[...]". The correct message should be "Check this option if source is a filename[...]".

This image is an example of the JSON input transformation. It is the same for YAML input and get data from XML.
![image](https://github.com/apache/hop/assets/133791598/1f7f0d1d-129d-480b-a7fe-a9ac62cf3990)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
.take-issue
