### ISSUE TITLE
[Task]: upgrade the Apache Beam dependencies to 2.48.0

### ISSUE THREAD

**Issue by bamaer** [apache/hop#2981]
### What needs to happen?

upgrade the Apache Beam dependencies to 2.48.0

### Issue Priority

Priority: 2

### Issue Component

Component: Beam

**Comment by mkhludnev** [comment]
Hi, @bamaer . I've found one issue. Documentation still references Flink 1.13. I've got NoSuchMethodError with Hop 2.4 and Flink 1.13, which is gone after I switched to Flink 1.15. Is it worth to bother about PR for doc change? Or is there a way to automate it somehow?
