### ISSUE TITLE
[Task]: While editing a Pipeline Action on a workflow, the “play icon” is used with flyout “Edit this metadata element” such that it is non-intuitive

### ISSUE THREAD

**Issue by Mattang-Dan** [apache/hop#2991]
### What needs to happen?

While editing a Pipeline Action on a workflow, the “play icon” is used with flyout “Edit this metadata element” such that it is non-intuitive

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by mattcasters** [comment]
It's the icon for the "Run Configuration" metadata element, which you can edit.
