### ISSUE TITLE
[Task]: Fix last missing italian translations in configuration perspective

### ISSUE THREAD

**Issue by sramazzina** [apache/hop#2998]
### What needs to happen?

.

### Issue Priority

Priority: 3

### Issue Component

Component: Translations

**Comment by sramazzina** [comment]
My bad, I assigned the wrong milestone tag :-(. Thanks for the correction

**Comment by hansva** [comment]
No you added the right one, but I thought this was linked to the [doc] update you did. So I changed it to 2.5 and wanted to close this issue. Unless that was what you wanted to do then we still need to close this and link it to 2.5
