### ISSUE TITLE
[Bug]: empty dropdown fields in the Rest client component

### ISSUE THREAD

**Issue by kielegat** [apache/hop#3011]
### Apache Hop version?

2.5.0 (2023-06-08 07.58.35)

### Java version?

OpenJDK 64-Bit Server VM Corretto-17.0.5.8.1 (build 17.0.5+8-LTS, mixed mode, sharing)

### Operating system

Windows

### What happened?

Wanted to configure the 'rest client' with fields from previous steps. However, cannot select the fields, the dropdown does not show the fields from the previous step. The dropdown is empty (see screenshot below). This error shows up for the url, the method and the body.  Tried this also with the older version (apache hop version 2.4.0) No issue. dropdown show the fields from the previous step. 

![image](https://github.com/apache/hop/assets/388662/26877eef-3f30-4eac-94fc-a10fab99066a)

simple transform:
![image](https://github.com/apache/hop/assets/388662/e9a5f34c-05df-4fd7-b8b8-32f456708fab)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
Can you try it with Java11 and see what "Show input field" looks like on the REST client tranfo?

**Comment by nadment** [comment]
I can reproduce it, it's a problem introduced in 2.5
