### ISSUE TITLE
[Bug]: HTTP Post

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#3018]
### Apache Hop version?

2.5.0

### Java version?

11

### Operating system

Windows

### What happened?

When Selecting the URL that is coming from the pipeline, the below error occurs

![image](https://github.com/apache/hop/assets/70301866/212e828a-f6f3-41c0-bfd8-fc2cd0cd883a)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
.take-issue

**Comment by pauloricardoferreira** [comment]
tks
