### ISSUE TITLE
[Bug]: Changing project's home path is not possible

### ISSUE THREAD

**Issue by sramazzina** [apache/hop#3041]
### Apache Hop version?

2.5.0

### Java version?

openjdk-11

### Operating system

Linux

### What happened?

Whenever we define a new project, If we mistakenly define a wrong home directory's path and we save the project with the erroneous path it is impossible to update the path to a correct one because the project's path doesn't open. Therefore we must manually modify the configuration file to update the project's home and let the dialog open.

### Issue Priority

Priority: 3

### Issue Component

Component: Other

**Comment by mattcasters** [comment]
Any update on this Sergio?  Still working on it?  Still an issue.  Feel free to clear the assigned field if you don't have time.

**Comment by sramazzina** [comment]
@mattcasters Just started these days to be back and work on issues so I' think I'll be able to manage some of the issues from the issues list I have

**Comment by sramazzina** [comment]
@mattcasters started working on this today.
