### ISSUE TITLE
[Task]: Redeploy helm chart to fit latest version of apache-hop

### ISSUE THREAD

**Issue by scali** [apache/hop#3047]
### What needs to happen?

When I do :

```sh
helm repo update && helm show chart apache-hop/hop
```
I still have `appVersion: 1.2.0`

We should have : `appVersion: 2.5.0` (as described [here](https://github.com/apache/hop/blob/master/helm/hop/Chart.yaml))

Is it possible to **deploy the chart to the latest version** ? I saw there is a [specific procedure](https://hop.apache.org/dev-manual/latest/apache-release/creating-a-release.html#_creating_the_helm_chart_if_needed) to create a new helm release, but does this procedure can be done by any contributors ?

Does the release of the Helm Chart have to be sync with the release of apache-hop ?

### Issue Priority

Priority: 3

### Issue Component

Component: Containers

**Comment by hansva** [comment]
we can release it independently, I'll see if I can get it done today

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
New chart has been deployed and index has been updated.
