### ISSUE TITLE
[Bug]: Table output transform creates an invalid SQL Server (Native) Create table statement

### ISSUE THREAD

**Issue by Mattang-Dan** [apache/hop#3049]
### Apache Hop version?

2.4

### Java version?

microsoft-jdk-11.0.19-windows-x64.msi

### Operating system

Windows

### What happened?

The Table output transform creates an invalid SQL Server (Native) Create table statement. 

When you click the SQL button to generate the SQL statement to create a SQL Server (Native) table, it contains double square brackets around the schema name resulting in invalid SQL if using an Azure SQL Server database (I think local SQL Server as well). It should have one set of square brackets around the schema name and one set around the table name to handle special characters.

### Issue Priority

Priority: 3

### Issue Component

Component: Database, Component: Transforms

**Comment by gertwieland** [comment]
I use that feature a lot. In 2.5, it works find on my end.
Hopefully upgrading is an option for you.

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
I think the latests issues should be resolved with the fix for #3113
