### ISSUE TITLE
[Bug]: The Table output transform creates an invalid SQL Server (Native) truncate table statement when you select "Truncate table"

### ISSUE THREAD

**Issue by Mattang-Dan** [apache/hop#3050]
### Apache Hop version?

2.4

### Java version?

microsoft-jdk-11.0.19-windows-x64.msi

### Operating system

Windows

### What happened?

The Table output transform creates an invalid SQL Server (Native) truncate table statement when you select the checkbox "Truncate table" if using an Azure SQL Server database (I think local SQL Server as well). According to logging, the Truncate table command has a double square bracket around the schema name when it should be a single square brackets around the schema and table names.

<From Log:>
2023/07/03 06:32:14 - Table output.0 - ERROR: Unexpected error
2023/07/03 06:32:14 - Table output.0 - ERROR: org.apache.hop.core.exception.HopDatabaseException: 
2023/07/03 06:32:14 - Table output.0 - Couldn't execute SQL: TRUNCATE TABLE [[test]].PAX8_Orders

### Issue Priority

Priority: 3

### Issue Component

Component: Database, Component: Transforms

**Comment by gertwieland** [comment]
On my end, it works in 2.5. Might be fixed already.

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
I think everything should be fixed now with the fix I will be adding to #3113.
We can reopen this one if the problem still persists in 2.6
