### ISSUE TITLE
[Bug]: Unable to correctly read datetime field type data

### ISSUE THREAD

**Issue by Huskey-dai** [apache/hop#3055]
### Apache Hop version?

2.6.0

### Java version?

jdk11

### Operating system

Windows

### What happened?

I want to retrieve datetime field type data from a table, but I found that all of them are returning null.
![image](https://github.com/apache/hop/assets/57424011/7e570804-d2c2-4b0b-87d4-92cc183cb253)
![image](https://github.com/apache/hop/assets/57424011/95c5fd04-4260-4e54-9221-a2ad1ff4cd56)

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by bamaer** [comment]
which database are you using. Please check if you have checked the "supports the timestamp data type" option in the Advanced tab of your relational database connection. 
 
![image](https://github.com/apache/hop/assets/948257/21ffdc87-3a1b-4950-a8ac-f6d664fc7eb4)

**Comment by Huskey-dai** [comment]
mysql8.0

**Comment by bamaer** [comment]
checking the "supports the timestamp data type" option should fix this.

**Comment by Huskey-dai** [comment]
thank you very much
