### ISSUE TITLE
[Bug]: Can't run Hop-Gui on Ubuntu Linux / GNOME Wayland - SwtSvgImageUtil / SwtUniversalImageSvg issues

### ISSUE THREAD

**Issue by fincentxyz** [apache/hop#3082]
### Apache Hop version?

2.5.0

### Java version?

openjdk 11.0.19

### Operating system

Linux

### What happened?

I'm running a Ubuntu 22.04.2 LTS 64-bit VirtualBox VM. The GNOME Version is 42.9 and it's running on the Wayland windowing system.

When running `./hop-gui.sh` I get a ton of errors all having to do with `SwtSvgImageUtil`. The actual Java error is the following:
```
Serious error detected in the Hop GUI: Could not initialize class org.apache.hop.core.SwtUniversalImageSvg
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hop.core.SwtUniversalImageSvg
	at org.apache.hop.ui.hopgui.perspective.explorer.ExplorerPerspective.loadTypeImages(ExplorerPerspective.java:306)
	at org.apache.hop.ui.hopgui.perspective.explorer.ExplorerPerspective.initialize(ExplorerPerspective.java:244)
	at org.apache.hop.ui.hopgui.HopGui.loadPerspectives(HopGui.java:514)
	at org.apache.hop.ui.hopgui.HopGui.open(HopGui.java:401)
	at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:352)
```

I found one other person with the same error. They posted something to StackOverflow two months ago:
https://stackoverflow.com/questions/76055862/cant-run-apache-hop-gui-on-linux-fedora

Fedora Linux also uses GNOME on Wayland.

Running it with sudo or restarting after installing doesn't make a difference.

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
Thanks for reporting this @fincentxyz

Let me try and reproduce this, I think most of our users are still on x11. Might be that we are assuming something there that no longer works on wayland.

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
I confirmed the issue, will see if we can find a solution.
