### ISSUE TITLE
[Feature Request]: Pipeline Executor online documentation should stress much more the capability to run a named sub pipeline from your meta table and pass in all variables

### ISSUE THREAD

**Issue by Mattang-Dan** [apache/hop#3083]
### What would you like to happen?

Just a suggestion, but in the Pipeline Executor online documentation one feature that should be stressed much more is the awesome capability that you can run a named sub pipeline from your meta table and pass in all variables...

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by bamaer** [comment]
the [pipeline executor doc page](https://hop.apache.org/manual/latest/pipeline/transforms/pipelineexecutor.html) already mentions this: 
`If you enable the "Inherit all variables from the pipeline" option, all the variables defined in the parent pipeline are passed to the pipeline.`
