### ISSUE TITLE
[Bug]: Adding a new Parameter by pressing the tab key multiple times in the Pipeline executor messes up GUI

### ISSUE THREAD

**Issue by Mattang-Dan** [apache/hop#3099]
### Apache Hop version?

2.4

### Java version?

microsoft-jdk-11.0.19-windows-x64.msi

### Operating system

Windows

### What happened?

How to reproduce error:
1. Type in a new Variable/Parameter name in a Pipeline executor transform
2. Press the tab key once (do not type anything)
3. Press the tab key again will hide the text you typed and you can no longer edit the first column in the GUI. However, you can select the other columns and select the entire row to delete.  But after you delete the row(s), the small blue variable/parameter symbol is still there in the row(s).
4. If you cancel the saving of the Pipeline executor transform and reopen it, you will now find some letters in the first column (Variable / Parameter name) that you could not see before, and can properly delete the row.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by mattcasters** [comment]
I can't reproduce this unfortunately.  Is this still an issue for you on 2.6.0?

**Comment by Mattang-Dan** [comment]
Looks like the issue is gone in 2.7 (latest build).
