### ISSUE TITLE
[Bug]: Copying and pasting notes not working

### ISSUE THREAD

**Issue by gertwieland** [apache/hop#3108]
### Apache Hop version?

2.5 Stable

### Java version?

openjdk version "11.0.9.1" 2020-11-04 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.9.1+1) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.9.1+1, mixed mode)

### Operating system

Windows

### What happened?

**Copying and pasting notes not working**

When I copy a note and try to paste it, one of two things happens:

1) If I copied some text before and it's still in the clipboard, it pastes that text (not the note).
2) If the clipboard is empty, I get a null-pointer exception

[Link to Mattermost convo.](https://chat.project-hop.org/hop/pl/m6uyzi7kgpd6iq73d8anekisbh)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
I'd like to take this opportunity to add an gui action
![image](https://github.com/apache/hop/assets/39568358/173f9c3f-9954-4772-9ea5-0c0d8d89244c)
