### ISSUE TITLE
[Feature Request]: "Save as" should point to current file

### ISSUE THREAD

**Issue by gertwieland** [apache/hop#3109]
### What would you like to happen?

When hitting "save as", the default location is the project root, and the file name is a generic file name.

Instead, I would like it to point to the existing file (folder and name). Usually, I would just want to add something like "copy" or "temp" to an existing file. With the current implementation, I need to search that file.

I'd argue this is a typical standard behaviour.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue

**Comment by gertwieland** [comment]
Thank you @hansva
