### ISSUE TITLE
[Feature Request]: Zooming with scrollwheel should zoom into pointer location

### ISSUE THREAD

**Issue by gertwieland** [apache/hop#3110]
### Zooming with scrollwheel should zoom into pointer location

When using the mouse scrollwheel to zoom into the canvas, it pushes the transforms to the bottom right corner. So after zooming in, you need to move the canvas and search the spot you are interested in.

It'd be great if instead, it would just zoom into the mouse location. So if the mouse hovers over a note, it would zoom into that note.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
Duplicate of #2309 which is planned for next release
