### ISSUE TITLE
[Feature Request]: Delete a hop with one click

### ISSUE THREAD

**Issue by gertwieland** [apache/hop#3130]
### What would you like to happen?

Ctrl-click (or middle-click) deactivates a hop.

Could we have "Shift-click (or right-click) to delete a hop?
Purpose: Reduce the overall number of clicks required during development.

Regular left-click would still open the context menu.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
Good idea, I suggest using the following combination "CONTROL + SHIFT + left click" to delete a hop.

**Comment by gertwieland** [comment]
Glad you like it, @nadment. I have no particular preference, and  CONTROL + SHIFT is a very simple combination.

**Comment by nadment** [comment]
I'm testing it out and it seems to be useful with Ctrl+Shift+left click

**Comment by gertwieland** [comment]
Thank you, @nadment
