### ISSUE TITLE
[Feature Request]: Open only one instance of an "Edit" window

### ISSUE THREAD

**Issue by gertwieland** [apache/hop#3133]
### What would you like to happen?

Currently (2.5) it is possible to open several "Edit" instances of a transform.

The risk here is that if you open it twice (or more times), then usually you would work in the last one that opened.
If you close it, but later also accidentally close (via "ok") one of the other instances, the changes you made first are lost.

I think it would make sense if we'd only allow for one "edit" instance per transform. 
Of course, we'd still need to be able to edit several transforms at the same time, i.e. we need several "edit" windows open at the same time, but only one per transform.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
I can't open the same transform more than once, how do you do it?

**Comment by gertwieland** [comment]
This is going to be embarrassing.... but....

I can't reproduce it either. I changed my Java version earlier, and I thought that might be the reason. But I just went to another machine where I have Hop running, and you are right, only one instance opens.

Then I went and checked PDI, and there it does open multiple times... maybe I mixed things up, sigh :(

Anyway, sorry for wasting your time with this request. I'll just close it.

**Comment by gertwieland** [comment]
As stated above, my bad, it's already working properly, and only one instance can be opened.

**Comment by nadment** [comment]
I remembered fixing this problem a few months ago in Apache Hop because it already annoys me in PDI.

**Comment by gertwieland** [comment]
Agreed, @nadment, it always annoyed me too. And definitely, Hop works as it should :)
