### ISSUE TITLE
[Bug]: "Sort rows" default: ascending, but "Sorted merge" default: descending

### ISSUE THREAD

**Issue by gertwieland** [apache/hop#3143]
### Apache Hop version?

2.5

### Java version?

openjdk 11.0.19 2023-04-18 OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.19+7-adhoc..jdk11u) OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 11.0.19+7-adhoc..jdk11u, mixed mode)

### Operating system

Windows

### What happened?

In a "sort rows" transform, when no sort order was specified, it picks "Ascending? Y" by default (as it should).

However, the "Sorted merge" transform picks "N" by default.

<img width="243" alt="image" src="https://github.com/apache/hop/assets/51762835/a7c58b6d-cb21-4e9e-8358-9ff2c168d611">

While that's not really a bug, I think it's very counterintuitive. Can we set the default to "Y", please?

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue
