### ISSUE TITLE
[Feature Request]: "Insert/ Update": Set column "Update" default to "Y"

### ISSUE THREAD

**Issue by gertwieland** [apache/hop#3145]
### What would you like to happen?

Currently, in the "Insert / update" transform, the default for column "Update" is set to "N".

<img width="522" alt="image" src="https://github.com/apache/hop/assets/51762835/08e3ed43-fd7d-40a0-8fc6-b42079684030">

While not a bug, I think this is very counterintuitive. After all, the very purpose of this transform is make updates.

Could we please change that default to "Y"?

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue
