### ISSUE TITLE
[Bug]: "Stream lookup": "Get lookup fields" and "Get fields" are flipped

### ISSUE THREAD

**Issue by gertwieland** [apache/hop#3157]
### Apache Hop version?

2.5

### Java version?

openjdk 11.0.19 2023-04-18 OpenJDK Runtime Environment OpenLogic-OpenJDK (build 11.0.19+7-adhoc..jdk11u) OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 11.0.19+7-adhoc..jdk11u, mixed mode)

### Operating system

Windows

### What happened?

In the "Stream Lookup" field, I would expect the "Get Lookup fields" to pull the "Lookup fields", but it doesn't. Instead, it pulls the "Fields to retrieve".

But the "Get Fields" button pulls the "Lookup fields".

I think this should be the opposite.

<img width="680" alt="image" src="https://github.com/apache/hop/assets/51762835/7c2201b7-986c-4818-974d-175374e1ffcb">

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by harrisward** [comment]
I think its right but a little confusion as the Get Lookup Fields Means "Get the fields to lookup from the Lookup Transform". Maybe the names of the buttons could be a bit better? Like "Get Key Fields" for the look up values and "Get Lookup Fields" for the fields to return to the primary transform

**Comment by hansva** [comment]
I agree that the naming is confusing.
what do you think about the following:
Get fields -> Get return fields
Get lookup fields -> get lookup key fields

?

**Comment by hansva** [comment]
.take-issue

**Comment by nadment** [comment]
My proposal:
Get fields -> Get key fields
Get lookup fields -> Get fields to retrieve

**Comment by usbrandon** [comment]
I agree with that and also adding the word 'key' "Get key fields" to let it contextualize what happens.

**Comment by usbrandon** [comment]
"Get key fields" and "Get return fields".   I would just make the case match, but it is much clearer.

**Comment by hansva** [comment]
Has been aligned:
![image](https://github.com/apache/hop/assets/1140235/1ca87a95-8c10-469c-9977-7fecdefb7643)
