### ISSUE TITLE
Kettle的转换步骤信息统计组件没有

### ISSUE THREAD

**Issue by 172151295** [apache/hop#3159]
### What would you like to happen?

希望 HOP 实现Kettle的转换步骤信息统计组件功能

### Issue Priority

Priority: 1

### Issue Component

Component: Other

**Comment by 172151295** [comment]
> Are you talking about the Weka plugins?
> 

![IMG_20230817_105635.jpg](https://github.com/apache/hop/assets/70830248/98854670-5adc-41dc-8b2d-82b057156b04)

**Comment by 172151295** [comment]
> Are you talking about the Weka plugins?
> 

output steps metrics 这个组件

**Comment by hansva** [comment]
There is a ticket to include that one, #3003 but has not yet been done.
Will close this as duplicate
