### ISSUE TITLE
[Bug]: Select Values Step - Existing fields change when other fields are removed

### ISSUE THREAD

**Issue by harrisward** [apache/hop#3170]
### Apache Hop version?

hop-client-2.6.0-20230817.192906-1

### Java version?

openjdk 11.0.16.1 2022-08-12 LTS

### Operating system

Windows

### What happened?

When you have a list of fields in the select transform under the select and alter tab and you remove fields from the list further down, the field you are left selected on will change to a different value when you click away

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by harrisward** [comment]
https://github.com/apache/hop/assets/6827832/6968f4bb-d834-415b-a309-2ac680b95aa9

**Comment by sramazzina** [comment]
Ciao @harrisward I tried to reproduce on Hop 2.7 but it seems it works! Can you try on latest Hop 2.7 and let me know?

**Comment by sramazzina** [comment]
@harrisward I as definitely able to reproduce it even if it randomly happens

**Comment by mattcasters** [comment]
Someone should create a reproduction path so we can fix the issue.

**Comment by sramazzina** [comment]
It is very hard to prepare a reproduction path @mattcasters because it randomly happens. I think that @harrisward videos are more than enough

**Comment by hansva** [comment]
It cannot be reproduced in Windows with a current Hop version.
