### ISSUE TITLE
[Bug]: Running HOP on MAC M1/M2 Arm based

### ISSUE THREAD

**Issue by gvdutra** [apache/hop#3172]
### Apache Hop version?

2.6.0-SNAPSHOT

### Java version?

openjdk version "11.0.20.1" 2023-08-24

### Operating system

macOS

### What happened?

gabrieldutra@Gabriels-Air hop % ./hop-gui.sh
Error starting the Hop GUI: Could not load SWT library. Reasons: 
hop-encrno swt-cocoa-4958r2 in java.library.path: [.]       hop-search.sh*      hop-translator.sh*  
        no swt-cocoa in java.library.path: [.]
        no swt in java.library.path: [.]
        Can't load library: /Users/gabrieldutra/.swt/lib/macosx/aarch64/libswt-cocoa-4958r2.jnilib
        Can't load library: /Users/gabrieldutra/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
        Can't load library: /Users/gabrieldutra/.swt/lib/macosx/aarch64/libswt.jnilib
        Can't load library: /Users/gabrieldutra/.swt/lib/macosx/aarch64/libswt-cocoa-4958r2.jnilib

java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
        no swt-cocoa-4958r2 in java.library.path: [.]
        no swt-cocoa in java.library.path: [.]
        no swt in java.library.path: [.]
        Can't load library: /Users/gabrieldutra/.swt/lib/macosx/aarch64/libswt-cocoa-4958r2.jnilib
        Can't load library: /Users/gabrieldutra/.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
        Can't load library: /Users/gabrieldutra/.swt/lib/macosx/aarch64/libswt.jnilib
        Can't load library: /Users/gabrieldutra/.swt/lib/macosx/aarch64/libswt-cocoa-4958r2.jnilib

        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:346)
        at org.eclipse.swt.internal.Library.loadLibrary(Library.java:255)
        at org.eclipse.swt.internal.C.<clinit>(C.java:19)
        at org.eclipse.swt.widgets.Display.<clinit>(Display.java:110)
        at org.apache.hop.ui.core.widget.OsHelper.setAppName(OsHelper.java:96)
        at org.apache.hop.ui.hopgui.HopGui.main(HopGui.java:318)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui, Component: Hop Run

**Comment by hansva** [comment]
It works fine here on my M2.
Make sure you are using an aarch64 jdk the one I am using is temurin from adoptopenjdk

**Comment by gvdutra** [comment]
crazy still didn't work for me.

I will keep trying it.

`gabrieldutra@Gabriels-Air hop % java -version
openjdk version "11.0.20" 2023-07-18
OpenJDK Runtime Environment Temurin-11.0.20+8 (build 11.0.20+8)
OpenJDK 64-Bit Server VM Temurin-11.0.20+8 (build 11.0.20+8, mixed mode)
`

**Comment by gvdutra** [comment]
Ok I found out, important thing, need to run it as sudo.

`gabrieldutra@Gabriels-Air hop % sudo ./hop-gui.sh
2023/08/29 20:59:26 - Hop - Projects enabled
2023/08/29 20:59:26 - Hop - Enabling project : 'default'
`
I will add this in the documentation.

**Comment by hansva** [comment]
that's odd. I don't have issues like that...

**Comment by tlue** [comment]
Hi - I am getting same error message using Apache 2.11.0 on Windows with Temurin's "OpenJDK17U-jdk_x64_windows_hotspot_17.0.13_11.zip"

**Comment by bamaer** [comment]
Adoptium/Temurin is mentioned on the [supported JVMs](https://hop.apache.org/manual/latest/supported-jvms.html#_unsupported_jvms) info page as the one to avoid.

**Comment by tlue** [comment]
interesting - getting same error having set system variable HOP_JAVA_HOME to "microsoft-jdk-17.0.13-windows-x64" on an oldish Win-Server-2016
But it works on my local "Windows 11 Pro" with both, Temurin and Microsoft JDK...
I will try to find out more details about this and post them here again

**Comment by hansva** [comment]
Windows server 2016 is no longer supported by the more recent SWT libraries.

**Comment by hansva** [comment]
See https://github.com/apache/hop/issues/4573 for more information
