### ISSUE TITLE
[Feature Request]: Ability to start workflows at specific actions via hop-run

### ISSUE THREAD

**Issue by harrisward** [apache/hop#3178]
### What would you like to happen?

When running workflows in the hop UI its possible to add the set the argument "Start Workflow At" where you can specify action at where to start. This option isn't available to the hop-run commandline script but it would be handy to have

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Run

**Comment by usbrandon** [comment]
[[Same feature 2154](https://github.com/apache/hop/issues/2154)](https://github.com/apache/hop/issues/2154)  - I think our ETL reached a point where this is super useful.  For example we have workflows that do a long download, and we want to be able to recover knowing the download is already complete and fine.
