### ISSUE TITLE
[Bug]: Application Type field is non editable in REST Client

### ISSUE THREAD

**Issue by pradoshsahoo2021** [apache/hop#3179]
### Apache Hop version?

2.4, 2.5

### Java version?

jdk11

### Operating system

Windows

### What happened?

In REST Client transform, Application type is disabled. Default it shows TEXT PLAIN. I am not able to change it to any other type.

![image](https://github.com/apache/hop/assets/120457193/b22e33f9-4d23-4a0e-a3cf-b6057223bc32)

### Issue Priority

Priority: 1

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
As far as I know Get requests do not require an content-type header, as they do not send any content.
For get requests you do have the optional "accept" header type, but we did not add this to the transform.
You can however add your own custom header elements in the headers tab
