### ISSUE TITLE
[Bug]: Concat Fields - Advanced tab missing

### ISSUE THREAD

**Issue by pradoshsahoo2021** [apache/hop#3189]
### Apache Hop version?

2.4,2.5

### Java version?

jdk11

### Operating system

Windows

### What happened?

As per document https://hop.apache.org/manual/latest/pipeline/transforms/concatfields.html, this transform should has Advanced TAB. It is not present.

![image](https://github.com/apache/hop/assets/120457193/2c1050a7-f990-4713-a901-b6eb0241bdb6)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by mattcasters** [comment]
Needs a documentation update.  The referenced "advanced" options never worked and so the GUI options were removed a number of versions ago.

**Comment by sramazzina** [comment]
That means that we need to update the documentation by just removing that section?
