### ISSUE TITLE
[Bug]: Filter Transform - Date filter forces long date format.  Impossible to change on the right side after entry.

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#3196]
### Apache Hop version?

2.5-GA

### Java version?

11

### Operating system

Windows

### What happened?

![image](https://github.com/apache/hop/assets/1233654/ea62ae4f-fc50-42bd-9842-0a1e68e05941)

When you set a mask on the value side for yyyy-MM-dd, once you hit enter, it reverts to yyyy-MM-dd HH:mm:SS.XXX and it is impossible to change it.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by sramazzina** [comment]
@mattcasters can I take this issue or maybe you already have implemented something?

**Comment by mattcasters** [comment]
Go ahead @sramazzina !

**Comment by usbrandon** [comment]
Reproduction video

https://www.youtube.com/watch?v=HeC9oQKygQU
