### ISSUE TITLE
[Feature Request]: Create and change git branches in Hop Web UI

### ISSUE THREAD

**Issue by avizingdbronson** [apache/hop#3207]
### What would you like to happen?

Hop Web Git client doesn't provide the ability to create or switch branches. For many development approaches, these are critical functions. Request these options to be added to the UI.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Web

**Comment by mattcasters** [comment]
Do you have any suggestions on how to display the branch name in the UI?

**Comment by avizingdbronson** [comment]
I think the function is fairly common in web based git tools. Sourcetree is popular for example. Making the git interface as similar as possible to tools already familiar to developers would be the ideal target.

**Comment by hansva** [comment]
.take-issue
