### ISSUE TITLE
[Bug]: Golden data set seems to break filter rows transform

### ISSUE THREAD

**Issue by don-philipe** [apache/hop#3210]
### Apache Hop version?

2.5.0

### Java version?

19.0.2

### Operating system

Linux

### What happened?

I'm not sure if this is intended or not. But when adding a _golden data set_ to a _filter row_ transform, the filter conditions of that transformation seem to be ignored. The filter seems to be bypassed and the input of the filter transform is being forwarded to both, the 'true' and the 'false' branch of the filter output.

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
This might need some extra explanation in the docs, when adding a golden data set to a transform what actually happens in the back is that transform is replaced by a "dummy" where the data validation happens. When you want to use it on the filter rows you usually want to check one of the paths (the true or false path). 

Usually we add the golden data set at the end of our pipeline (on an output transform) and during testing we don't want that transform to actually run.

**Comment by don-philipe** [comment]
Ok, thanks for clarification.
