### ISSUE TITLE
[Bug]: Get Data From XML step does not support ETL Metadata Injection

### ISSUE THREAD

**Issue by adbrown101** [apache/hop#3214]
### Apache Hop version?

2.5.0

### Java version?

java.version=11.0.20

### Operating system

Windows

### What happened?

Create template pipeline with Get Data From XML hop
Create injector pipeline with ETL Metadata Injection hop, link to the template in ETL Metadata Injection

The Get Data from XML is not visible at all in ETL Metadata Injection.

Also tested on http://demo.hop.apache.org/ui latest release and development version.
[etlmetadataxml.zip](https://github.com/apache/hop/files/12576253/etlmetadataxml.zip)

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by adbrown101** [comment]
I can see that it is not supported there. However I was looking at the manual for the transform, which suggests it is supported. Perhaps this page needs updating?

https://hop.apache.org//manual/latest/pipeline/transforms/getdatafromxml.html

**Comment by bamaer** [comment]
fair point, will be fixed in 2.7.0

**Comment by adbrown101** [comment]
Thanks very much
