### ISSUE TITLE
[Bug]: Variable set to "valid in JVM" not valid in a repeated pipeline

### ISSUE THREAD

**Issue by Mattang-Dan** [apache/hop#3233]
### Apache Hop version?

2.6

### Java version?

microsoft-jdk-11.0.19-windows-x64.msi

### Operating system

Windows

### What happened?

A variable set in a pipeline to "valid in JVM" is not valid or has errors in a repeated child pipeline (see files attached).

**Error is**: couldn't convert String to number : non-numeric character found at position 1 for value [${COUNTER}]

**Setup**: Set a global variable (valid in JVM) in a pipeline that calls a workfow executor that calls a Repeat transform that calls a pipeline.
[variable_scope_JVM_to_workflow.zip](https://github.com/apache/hop/files/12619037/variable_scope_JVM_to_workflow.zip)

### Issue Priority

Priority: 3

### Issue Component

Component: Pipelines

**Comment by bamaer** [comment]
`${VALID_IN_JVM}` was never set, example fails on casting to integer in repeating pipeline. 
When I move `Set vars` before write to log and set a valid variable value, the variable can be retrieved and the repeat action works correctly.

**Comment by Mattang-Dan** [comment]
VALID_IN_JVM was set as a variable in the first pipeline

**Comment by Mattang-Dan** [comment]
It is working. I think the error was misleading - I actually had to configure a Run configuration for the Repeat pipeline.
[variable_scope_JVM_to_workflow.zip](https://github.com/apache/hop/files/12621843/variable_scope_JVM_to_workflow.zip)
Attached is a better test case that works.
