### ISSUE TITLE
[Feature Request]: Remove comment string from script step 

### ISSUE THREAD

**Issue by harrisward** [apache/hop#3234]
### What would you like to happen?

When you add a script step to a pipeline the script dialog has a default 

// script here

line. This is a JS comment (an other languages im sure) but its not a python comment. When you select python as your scripting language the step throws and error because the comment is in there. Its really not needed at all so I think it should be removed. 

See the error

![image](https://github.com/apache/hop/assets/6827832/5a27e1c3-15fd-41be-984d-eb6ca7457e0c)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by mattcasters** [comment]
Thanks @harrisward
