### ISSUE TITLE
[Bug]: Snowflake Bulk Uploader always deletes staging files

### ISSUE THREAD

**Issue by iBLtz** [apache/hop#3247]
### Apache Hop version?

2.6

### Java version?

java version "1.8.0_261"

### Operating system

Windows

### What happened?

The files are always deleted, no matter if the "remove files after load" is checked or not 

![image](https://github.com/apache/hop/assets/18102227/61884ebf-75dc-4f88-8cfd-3a58248580da)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by mattcasters** [comment]
The option is not used indeed.  A variable called `SNOWFLAKE_DEBUG_MODE` is used instead.  Set it to `true` to keep the temporary files.

**Comment by mattcasters** [comment]
This option isn't enabled by default. Changing the behavior will cause temporary files to flood existing deployments, so I'll update the documentation and will continue to use the variable to prevent this scenario.
