### ISSUE TITLE
[Task]: Change AES Algorithm on AesTwoWayPasswordEncoder

### ISSUE THREAD

**Issue by hansva** [apache/hop#3271]
### What needs to happen?

Currently we are using following AES algorithm: AES/ECB/PKCS5Padding
This mode has been deemed unsafe and needs to be upgraded to use a better algorithm.

Changing this would be a breaking change for people currently using the AES strings in their configuration so clear communication will be needed

### Issue Priority

Priority: 2

### Issue Component

Component: Other

**Comment by mattcasters** [comment]
It's perhaps better to create a new plugin AES2 or something like that.  Leave deprecation warnings in the logging when using the old plugin.

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
Added a new AES2 type and deprecated the old one.
