### ISSUE TITLE
[Feature Request]: Enhance "Enhanced JSON Output" to generate Arrays

### ISSUE THREAD

**Issue by vdwals** [apache/hop#3287]
### What would you like to happen?

When using the grouping functionality of "Enhanced JSON Output", each result row gets an Array of JSON items. With an additional flag I wish to generate a single JSON item result, but the values should be arrays.

|Nr|Name|
|:----:|:----:|
|1|Feature|
|1|Request|

Current result grouped by Nr.:
|outputValue|Nr|
|:----:|:----:|
|{"result":[{"name":"Feature"}, {"name":"Request"}]}|1|

With "Force Single Item" flag active, grouped by Nr.:
|outputValue|Nr|
|:----:|:----:|
|{"result":{"name":["Feature", "Request"]}}|1|

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by vdwals** [comment]
.take-issue

**Comment by marwari8** [comment]
We have the same issue 

the result shall be
`
{"result":["Feature", "Request"]}
`
and not that one
`
{"result":{["Feature", "Request"]}}
`

**Comment by hansva** [comment]
I agree this feature should come out of the box with an extra flag on the field handling.

Currently, this result can be achieved with a bit of a workaround:
- Aggregate the strings to an array to have the [ "value1" , "value2" ...] format
- Use the JSON Fragment option on the field

I have created a simplified sample which can be found [here](https://drive.google.com/file/d/1qlJOCUE29eqZ73JHRzSVTT4FIwWKodIR/view?usp=sharing)

**Comment by hansva** [comment]
I will mark this one as completed and created a follow up #3395 I think it would still be useful to have this option on field/element level
