### ISSUE TITLE
[Feature Request]: A hotkey shortcut for quickly edit pipeline and workflow

### ISSUE THREAD

**Issue by duyvb125** [apache/hop#3288]
### What would you like to happen?

To edit a pipeline or workflow takes multiple steps: click pipeline -> click edit on popup.
Is there a faster way? For example, add a shortcut for edit, hold shift and click on a pipeline/workflow.

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
Hi there,

If you are talking about following the link from a pipeline/workflow action in a workflow you can use the ctrl + shift + click command.
If you are talking about opening the edit dialog on an action/transform you can click on the name of that action/transform.

overview of our shortcuts can be found [here](https://hop.apache.org//manual/latest/hop-gui/shortcuts.html#_general_shortcuts)

**Comment by duyvb125** [comment]
Very helpful, thank you!
