### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by WangLL98** [apache/hop#3290]
### Apache Hop version?

2.5 AND 2.4

### Java version?

jdk-11.0.1

### Operating system

Windows

### What happened?

I found that when using the table input component to read a datetime type field, if one of the values in the entire field is null, the hop will resolve the entire field value to null

### Issue Priority

Priority: 3

### Issue Component

Component: Database

**Comment by bamaer** [comment]
did you check the `supports the timestamp data type` in the `Advanced` tab for your (generic) database connection? 

Could this be related to [this question/remark](https://chat.project-hop.org/hop/pl/8mhqbbjdfiyb783wnwkst4exte) about the Da Meng database in the Apache Hop chat? Is so, feel free to create a feature request ticket to add support for Da Meng as a database type.

**Comment by WangLL98** [comment]
Thank you. I checked the supports the timestamp data typeAdvanced, which is indeed the problem here
