### ISSUE TITLE
[Bug]:Get filename: Y/N flags not working properly when language is not English

### ISSUE THREAD

**Issue by sramazzina** [apache/hop#3294]
### Apache Hop version?

2.6.0

### Java version?

openjdk-11

### Operating system

Windows

### What happened?

Trying to configure the transform with a language that is not English, the flags are not working properly because they are not saved by Hop in a language independent way (Y/N different from S/N for italian). The issue seems to affect other transforms too.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by mattcasters** [comment]
I would reject this case on the ground that we never translate data or metadata and wouldn't recommend starting with it.

So IMO this is actually a feature request for proper translation of boolean options in the various tables in the Hop GUI.

**Comment by sramazzina** [comment]
I totally agree with you @mattcasters but we must to keep in mind that if we don't translate Boolean and the user uses to GUI in its own native language and not in English we will incur in malfunctions. By following your suggestion, I will open a wider issue to definitely fix this problem soon

**Comment by sramazzina** [comment]
Closing the issue in favor of a more complete solution that cover all the cases as detailed in #3428
