### ISSUE TITLE
[Bug]: Documentation - incorrect environment variable in 'Modify Startup Script' for Hop Web

### ISSUE THREAD

**Issue by kranskydog** [apache/hop#3295]
### Apache Hop version?

2.6.0

### Java version?

N/A

### Operating system

Other

### What happened?

In the documentaion descibing how to set up your own Hop Web instance, in Modify Startup Script (https://hop.apache.org/dev-manual/latest/hopweb/index.html#_modify_startup_script) it gives 

export HOP_SHARED_JDBC_FOLDERS=

when it should be 

export HOP_SHARED_JDBC_FOLDER=

Similarly, the "export CATALINA_OPTS..." has

-DHOP_SHARED_JDBC_FOLDERS="${HOP_SHARED_JDBC_FOLDERS}"

which should be 

-DHOP_SHARED_JDBC_FOLDER="${HOP_SHARED_JDBC_FOLDER}"

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by hansva** [comment]
nice catch, the docs on the development manual already reflect the upcoming version.
These variables will be changed in 2.7 with ticket #2129 it will be a breaking change
I'll add the other versions of the docs to the website and point latest to the current released version.

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
If you refresh the pages the issues should be resolved.
