### ISSUE TITLE
[Feature Request]: Ability to store encrypted passwords as variables

### ISSUE THREAD

**Issue by kranskydog** [apache/hop#3309]
### What would you like to happen?

I can have an RDBMS connection defined, and use variables defined in project environments for the db name and the db host etc. 
If I input the password for the RDBMS connection, that password is stored encrypted in the corresponding metadata file. 

If I have different passwords in different environments, while I can specify a variable and store the different passwords against that variable in the environment files, and use that variable for the password in the RDBMS connection info, the passwords get stored in clear text in the environment files.

So, there should be a way of telling Hop that the value for a variable needs to be stored encrypted in the environment file.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Config

**Comment by kranskydog** [comment]
I am aware that it can be achieved by using hop-encrypt and manually updating the enviroment's .json file, but it would be nice to simply have it happen through the gui

**Comment by hansva** [comment]
great request @kranskydog, 
An extra UI option to generate the string would be helpful indeed.

**Comment by mattcasters** [comment]
Before:
![image](https://github.com/apache/hop/assets/1724620/d20ec793-db63-43f5-afa7-288ace9ab386)

After:
![image](https://github.com/apache/hop/assets/1724620/28907141-fc03-48ef-a5df-628d309f0e3f)

It uses the password encoder that is configured, including the AES plugin.
