### ISSUE TITLE
[Task]: improve documentation on Set Variables action 

### ISSUE THREAD

**Issue by bamaer** [apache/hop#3321]
### What needs to happen?

extend documentation on [Set Variables](https://hop.apache.org//manual/latest/workflow/actions/setvariables.html) action, especially the properties file option.  

https://lists.apache.org/thread/9w4gw04b7v9fz8o4dty2nnwfzb0vr43d

### Issue Priority

Priority: 2

### Issue Component

Component: Actions, Component: Documentation

**Comment by dsanderbi** [comment]
.take-issue

**Comment by dsanderbi** [comment]
Adding sample as suggested by @hansva : [samples.zip](https://github.com/apache/hop/files/15445173/samples.zip)

NOTE: Has also been added to PR!
