### ISSUE TITLE
[Bug]: Hop-Web built from source - CLI tools don't work

### ISSUE THREAD

**Issue by kranskydog** [apache/hop#3323]
### Apache Hop version?

2.6.0

### Java version?

openjdk version "17.0.8" 2023-07-18 LTS OpenJDK Runtime Environment (Red_Hat-17.0.8.0.7-2.0.1) (build 17.0.8+7-LTS) OpenJDK 64-Bit Server VM (Red_Hat-17.0.8.0.7-2.0.1) (build 17.0.8+7-LTS, mixed mode, sharing)

### Operating system

Linux

### What happened?

If you build and deploy Hop-Web per https://hop.apache.org/dev-manual/latest/hopweb/index.html, it includes scripts for the CLI tools. However, those tools don't work.

[apache@apchop01 webapps]$ pwd
/u01/app/tomcat/admin/webapps
[apache@apchop01 webapps]$ ls
docs  examples  hop  hop.war  host-manager  manager  ROOT
[apache@apchop01 webapps]$ ls ROOT
asf-logo-wide.svg  bg-middle.png  bg-upper.png  index.jsp          tomcat.css  WEB-INF
bg-button.png      bg-nav.png     favicon.ico   RELEASE-NOTES.txt  tomcat.svg
[apache@apchop01 webapps]$ ls hop
config           hop-encrypt.sh  hop-import.bat  hop-search.bat  hop-server.xml      LICENSE   pwd            translator.xml
hop-conf.bat     hop-gui.bat     hop-import.sh   hop-search.sh   hop-translator.bat  licenses  README.txt     WEB-INF
hop-conf.sh      hop-gui.sh      hop-run.bat     hop-server.bat  hop-translator.sh   META-INF  rwt-resources
hop-encrypt.bat  hop.ico         hop-run.sh      hop-server.sh   index.jsp           NOTICE    static
[apache@apchop01 webapps]$ sh hop/hop-run.sh -h
Error: Could not find or load main class org.apache.hop.run.HopRun
Caused by: java.lang.ClassNotFoundException: org.apache.hop.run.HopRun
[apache@apchop01 webapps]$ 

to start with, they are setting CLASSPATH to the wrong place

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Web

**Comment by bamaer** [comment]
good catch, the docs should be made in sync with what happens in [Dockerfile.web](https://github.com/apache/hop/blob/master/docker/Dockerfile.web)
