### ISSUE TITLE
[Bug]: Javascript Action fails to find field when referenced in Start Script

### ISSUE THREAD

**Issue by harrisward** [apache/hop#3326]
### Apache Hop version?

2.5

### Java version?

openjdk version "11.0.16.1" 2022-08-12 LTS

### Operating system

Windows

### What happened?

The javascript step fails to find referenced fields in when used in the START Script.

![image](https://github.com/apache/hop/assets/6827832/bf418b75-7ef5-4321-b0c0-c3225199d98d)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by bamaer** [comment]
start scripts don't know about any data fields in the stream. 
Set Start Script - Specify the script to execute before processing the first row.

https://chat.project-hop.org/hop/pl/n7ger8aaubn7ufmx4z7ibnkeor

https://chat.project-hop.org/hop/pl/n7ger8aaubn7ufmx4z7ibnkeor
