### ISSUE TITLE
[Bug]: Translator cannot be started

### ISSUE THREAD

**Issue by jefersonnavarro** [apache/hop#3327]
### Apache Hop version?

2.7.0-SNAPSHOT (2023-10-28 02.25.57)

### Java version?

openjdk version "11.0.20.1"

### Operating system

Linux

### What happened?

The translator cannot be started and the following error occurs:

Hop translator - Scanning source directories and Java source files for i18n keys...
Suspect key found: [; ] in file [file:///hop/plugins/transforms/httppost/src/main/java/org/apache/hop/pipeline/transforms/httppost/HttpPost.java]
Suspect key found: [; ] in file [file:///hop/plugins/transforms/httppost/src/main/java/org/apache/hop/pipeline/transforms/httppost/HttpPost.java]
2023/10/27 22:37:16 - GUI - ERROR: Create widgets: no GUI toolbar items found for root: TableView-Toolbar
2023/10/27 22:37:17 - Hop translator - ERROR: An unexpected error occurred : null
2023/10/27 22:37:17 - Hop translator - ERROR: java.lang.NullPointerException
2023/10/27 22:37:17 - Hop translator -  at org.apache.hop.ui.i18n.editor.Translator.refreshPackages(Translator.java:1313)
2023/10/27 22:37:17 - Hop translator -  at org.apache.hop.ui.i18n.editor.Translator.refreshGrid(Translator.java:1174)
2023/10/27 22:37:17 - Hop translator -  at org.apache.hop.ui.i18n.editor.Translator$5.widgetSelected(Translator.java:508)
2023/10/27 22:37:17 - Hop translator -  at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
2023/10/27 22:37:17 - Hop translator -  at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
2023/10/27 22:37:17 - Hop translator -  at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5855)
2023/10/27 22:37:17 - Hop translator -  at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
2023/10/27 22:37:17 - Hop translator -  at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:5065)
2023/10/27 22:37:17 - Hop translator -  at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4517)
2023/10/27 22:37:17 - Hop translator -  at org.apache.hop.ui.i18n.editor.Translator.main(Translator.java:1428)
Exception in thread "Thread-5" java.lang.NullPointerException
        at org.apache.hop.ui.i18n.editor.Translator.lambda$addListeners$1(Translator.java:372)
        at org.apache.hop.ui.i18n.editor.Translator$TranslateShutdownHook.run(Translator.java:1453)

### Issue Priority

Priority: 1

### Issue Component

Component: Translations

**Comment by hansva** [comment]
We have moved translations to https://translate.project-hop.org/
We should remove the old code and references to it.
