### ISSUE TITLE
Google Sheet Output 403 Error

### ISSUE THREAD

**Issue by juice416021** [apache/hop#3333]
Version: 2.6
Operating System: Mac

I have already set up on Google Cloud:

Created a new Project
Enabled Google Drive API
Enabled Google Sheet API
Created a service account
Generated a key for the service account and downloaded the JSON file for Apache Hop's Google Sheet Output to read.
Created a new Google Sheet and granted edit permissions to the service account.
However, I'm still encountering a 403 error.

![image](https://github.com/apache/hop/assets/130071336/4790d3a6-62ac-46de-a3f8-88923e855f4d)
![image](https://github.com/apache/hop/assets/130071336/437b0f24-cde7-4c50-9b30-540edb6d71ba)
<img width="1092" alt="image" src="https://github.com/apache/hop/assets/130071336/917391f5-7fb8-4c2c-8fab-ef2f04dcd314">
<img width="484" alt="image" src="https://github.com/apache/hop/assets/130071336/d6a0043b-ce7a-4468-bacd-4acffadf84f5">
<img width="1170" alt="image" src="https://github.com/apache/hop/assets/130071336/cf01a83b-83b5-47c0-ae09-ded28a48713c">
<img width="1215" alt="image" src="https://github.com/apache/hop/assets/130071336/76a7411c-3d5d-4041-ae50-ce5ee82db32c">

2023/10/31 17:50:17 - Hop - Projects enabled
2023/10/31 17:50:17 - Hop - Enabling project : 'gene-test'
2023/10/31 18:11:11 - final_test - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
2023/10/31 18:11:11 - final_test - Execution started for pipeline [final_test]
2023/10/31 18:11:12 - Google Sheet Output.0 - ERROR: Error: for worksheet : TEST in spreadsheet :1tRttL_J2BfalduLzTGgJAWWUmN7tO9Jj5UweOpghOPI403 Forbidden
2023/10/31 18:11:12 - Google Sheet Output.0 - GET https://www.googleapis.com/drive/v3/files?fields=nextPageToken,%20files(id,%20name)&includeItemsFromAllDrives=true&pageSize=100&q=mimeType%3D'application/vnd.google-apps.spreadsheet'&supportsAllDrives=true
2023/10/31 18:11:12 - Google Sheet Output.0 - {
2023/10/31 18:11:12 - Google Sheet Output.0 -   "code" : 403,
2023/10/31 18:11:12 - Google Sheet Output.0 -   "details" : [ {
2023/10/31 18:11:12 - Google Sheet Output.0 -     "@type" : "type.googleapis.com/google.rpc.ErrorInfo",
2023/10/31 18:11:12 - Google Sheet Output.0 -     "reason" : "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
2023/10/31 18:11:12 - Google Sheet Output.0 -     "domain" : "googleapis.com",
2023/10/31 18:11:12 - Google Sheet Output.0 -     "metadata" : {
2023/10/31 18:11:12 - Google Sheet Output.0 -       "method" : "google.apps.drive.v3.DriveFiles.List",
2023/10/31 18:11:12 - Google Sheet Output.0 -       "service" : "drive.googleapis.com"
2023/10/31 18:11:12 - Google Sheet Output.0 -     }
2023/10/31 18:11:12 - Google Sheet Output.0 -   } ],
2023/10/31 18:11:12 - Google Sheet Output.0 -   "errors" : [ {
2023/10/31 18:11:12 - Google Sheet Output.0 -     "domain" : "global",
2023/10/31 18:11:12 - Google Sheet Output.0 -     "message" : "Insufficient Permission",
2023/10/31 18:11:12 - Google Sheet Output.0 -     "reason" : "insufficientPermissions"
2023/10/31 18:11:12 - Google Sheet Output.0 -   } ],
2023/10/31 18:11:12 - Google Sheet Output.0 -   "message" : "Request had insufficient authentication scopes.",
2023/10/31 18:11:12 - Google Sheet Output.0 -   "status" : "PERMISSION_DENIED"
2023/10/31 18:11:12 - Google Sheet Output.0 - }
2023/10/31 18:11:12 - Google Sheet Output.0 - ERROR: com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
2023/10/31 18:11:12 - Google Sheet Output.0 - GET https://www.googleapis.com/drive/v3/files?fields=nextPageToken,%20files(id,%20name)&includeItemsFromAllDrives=true&pageSize=100&q=mimeType%3D'application/vnd.google-apps.spreadsheet'&supportsAllDrives=true
2023/10/31 18:11:12 - Google Sheet Output.0 - {
2023/10/31 18:11:12 - Google Sheet Output.0 -   "code" : 403,
2023/10/31 18:11:12 - Google Sheet Output.0 -   "details" : [ {
2023/10/31 18:11:12 - Google Sheet Output.0 -     "@type" : "type.googleapis.com/google.rpc.ErrorInfo",
2023/10/31 18:11:12 - Google Sheet Output.0 -     "reason" : "ACCESS_TOKEN_SCOPE_INSUFFICIENT",
2023/10/31 18:11:12 - Google Sheet Output.0 -     "domain" : "googleapis.com",
2023/10/31 18:11:12 - Google Sheet Output.0 -     "metadata" : {
2023/10/31 18:11:12 - Google Sheet Output.0 -       "method" : "google.apps.drive.v3.DriveFiles.List",
2023/10/31 18:11:12 - Google Sheet Output.0 -       "service" : "drive.googleapis.com"
2023/10/31 18:11:12 - Google Sheet Output.0 -     }
2023/10/31 18:11:12 - Google Sheet Output.0 -   } ],
2023/10/31 18:11:12 - Google Sheet Output.0 -   "errors" : [ {
2023/10/31 18:11:12 - Google Sheet Output.0 -     "domain" : "global",
2023/10/31 18:11:12 - Google Sheet Output.0 -     "message" : "Insufficient Permission",
2023/10/31 18:11:12 - Google Sheet Output.0 -     "reason" : "insufficientPermissions"
2023/10/31 18:11:12 - Google Sheet Output.0 -   } ],
2023/10/31 18:11:12 - Google Sheet Output.0 -   "message" : "Request had insufficient authentication scopes.",
2023/10/31 18:11:12 - Google Sheet Output.0 -   "status" : "PERMISSION_DENIED"
2023/10/31 18:11:12 - Google Sheet Output.0 - }
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:118)
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:37)
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$3.interceptResponse(AbstractGoogleClientRequest.java:466)
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1111)
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:552)
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:493)
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:603)
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at org.apache.hop.pipeline.transforms.googlesheets.GoogleSheetsOutput.init(GoogleSheetsOutput.java:109)
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at org.apache.hop.pipeline.transform.TransformInitThread.run(TransformInitThread.java:66)
2023/10/31 18:11:12 - Google Sheet Output.0 - 	at java.base/java.lang.Thread.run(Thread.java:1583)
2023/10/31 18:11:12 - Google Sheet Output.0 - ERROR: Error initializing transform [Google Sheet Output]
2023/10/31 18:11:12 - final_test - ERROR: Transform [Google Sheet Output.0] failed to initialize!
2023/10/31 18:11:12 - Table input.0 - Finished reading query, closing connection.
2023/10/31 18:11:12 - Table input 2.0 - Finished reading query, closing connection.

**Comment by hansva** [comment]
can you try adding the service account user as read/editor to the sheet?

**Comment by juice416021** [comment]
I have already added my service account in the sharing settings of the Google sheet I want to edit, and have set it as an editor.

**Comment by juice416021** [comment]
> can you try adding the service account user as read/editor to the sheet?
I have already added my service account in the sharing settings of the Google sheet I want to edit, and have set it as an editor.

**Comment by juice416021** [comment]
> can you try adding the service account user as read/editor to the sheet?

I have already added my service account in the sharing settings of the Google sheet I want to edit, and have set it as an editor.
