### ISSUE TITLE
[Bug]: Remote Work Configurations Won't Work Beacuse of Turkish Characters

### ISSUE THREAD

**Issue by myaspm** [apache/hop#3356]
### Apache Hop version?

2.6.0

### Java version?

11.0.16.1

### Operating system

Windows

### What happened?

Create a simple workflow with a start and a pipeline and make sure the name or the action of the pipeline contains one of many Turkish specific characters such as Ş, Ç, Ö, Ğ etc. This makes it so that Remote Run Configurations won't work with the error:

```
Invalid byte 1 of 1-byte UTF-8 sequence.
```

Tested on both Linux/Windows servers and with both Turkish locale installed and not. Maybe i'm doing some simple step wrong but couldn't find any solution.

Thanks in advance.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Server

**Comment by nadment** [comment]
Test case to repoduce the problem, work fine on local but not on remote server.

[remote-execute-with-Turkish-characters.zip](https://github.com/apache/hop/files/13299054/remote-execute-with-Turkish-characters.zip)
