### ISSUE TITLE
[Bug]: HopServer Shutdown listener requires no authentication

### ISSUE THREAD

**Issue by mgolisch** [apache/hop#3367]
### Apache Hop version?

2.4

### Java version?

openjdk version "11.0.19" 2023-04-18

### Operating system

Linux

### What happened?

The shutdown listener doesnt require any authentication, so everything that can connect to it can shutdown the server.
The shutdown listener should either require authentication or be able to be configured on another address or disabled altogether.

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Server

**Comment by mattcasters** [comment]
I can't reproduce this on 2.6.0 on Linux with

`sh hop-server.sh 127.0.0.1 8080 --kill`

I need the username and password to shutdown the Hop server.  Perhaps you can include a reproduction path?

**Comment by mgolisch** [comment]
you need to use the shutdownlistener port 8079.
It ask nothing, as soon as anything  connects to that the server dies.

**Comment by mgolisch** [comment]
Steps to reproduze:

1) docker pull apache/hop
2) docker run --name hop -p 8079:8079 -d apache/hop
3) sleep 10 # wait for server to start
4) curl localhost:8079
5) docker logs hop # log shows server is shuting down

**Comment by mattcasters** [comment]
Thank you very much Michael!

**Comment by hansva** [comment]
Disabled it for now, created a redesign/cleanup ticket for next release #3406
