### ISSUE TITLE
[Bug]: "Database Lookup" component hangs on when editing

### ISSUE THREAD

**Issue by coccoperaz83** [apache/hop#3387]
### Apache Hop version?

2.6.0

### Java version?

11.0.17

### Operating system

Windows

### What happened?

I'm developing a pipeline that reads data from a rest api and saves it to a mssql server database. The connection to the database is via VPN. By opening a "Database Lookup" step the GUI freezes and I have to wait about ten seconds before I can do anything. Every change made in the detail screen causes another GUI crash. In the Hop console I always get the same error: "Error in the Hop GUI: Failed to execute runnable..."

![image](https://github.com/apache/hop/assets/25967776/93c1b4fd-a294-40a2-b823-76e855d65e97)

![image](https://github.com/apache/hop/assets/25967776/c468e843-29dc-476b-947d-6b536c4910e3)

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
Does the connection work in Hop over VPN?
The stack trace seems to indicate that it wants to fetch metadata from the database but it can't connect to it.

**Comment by coccoperaz83** [comment]
Hi Has, 
when the GUI becomes responsive again I launch the transformation and it proceeds smoothly quickly, then the connection to the db actually works. I don't understand why it goes haywire in the editing screen. I indicated the "Database Lookup" step, but it happens with every step involving the db of course.

**Comment by mattcasters** [comment]
Code needs hardening for when the database driver loses connection and give back a null for the row metadata (fields).
It's probably a timeout or something like that, which is causing the connection drop.
