### ISSUE TITLE
[Bug]: error with support UNC Windows 

### ISSUE THREAD

**Issue by Jerem59** [apache/hop#3388]
### Apache Hop version?

2.6.0

### Java version?

OpenJDK 64-Bit Server VM Temurin-11.0.17+8 (build 11.0.17+8, mixed mode)

### Operating system

Windows

### What happened?

Hi
when i move a file with a destination like an unc path (CIFS Share), i have an error.
Same problem from pipeline or workflow
No problem with local move
During logs I saw something that makes me think a slash is missing after getting my variable from the environment file

2023/11/14 10:15:59 - Move_Files.0 - ERROR: Because of an error, this transform can't continue: Could not copy "file:///C:/Hop_Files/In/deco_comptes_.csv" to "file:////IP/Share/Deco_Archive/miscellaneous/deco_comptes__20231114_101559.csv".

Same problem if i add directly the path of UNC

Urgent, processing blocked following this bug

Thx

### Issue Priority

Priority: 1

### Issue Component

Component: Actions, Component: Pipelines, Component: Workflows

**Comment by mattcasters** [comment]
In theory, CIFS is supported through Apache VFS:  https://commons.apache.org/proper/commons-vfs/filesystems.html#CIFS

However, the smb:// protocol is not enabled and the required dependency (The cifs library) is too old to add support for it.

**Comment by Jerem59** [comment]
the problem is : overnight it no longer works

**Comment by Jerem59** [comment]
the problem is : overnight it no longer works

**Comment by Jerem59** [comment]
the problem is : overnight it no longer works

**Comment by hansva** [comment]
you mean it worked in 2.5 ?

**Comment by Jerem59** [comment]
Same problem in 2.4
Simple Pipeline with a grid for variable and process to copy file
The file is correctly copying but i have this error

2023/11/24 09:59:40 - Data grid.0 - Signaling 'output done' to 1 output rowsets.
2023/11/24 09:59:40 - Data grid.0 - Finished processing (I=0, O=0, R=0, W=1, U=0, E=0)
2023/11/24 09:59:40 - Process files.0 - ERROR: Because of an error, this transform can't continue: Could not copy "file:///d:/hop_files/test_nas.txt" to "file:////server.doamin/my_share/Temp/test_nas.txt".
2023/11/24 09:59:40 - Process files.0 - Signaling 'output done' to 0 output rowsets.
2023/11/24 09:59:40 - Process files.0 - Finished processing (I=0, O=0, R=1, W=0, U=0, E=1)

**Comment by mattcasters** [comment]
So we never had support for this, never claimed support for it and we now have a feature request to add support for CIFS in our Apache VFS plugins.

**Comment by mattcasters** [comment]
If I look around a bit, I see a library called `smbj` which might be a good starting point for the implementation of a proper `smb://` VFS driver.

**Comment by hansva** [comment]
We do have to remove it from the documentation [here](https://hop.apache.org//manual/latest/vfs.html#_apache_hop_vfs_file_systems). Theoretically, VFS supports UNC paths... But the way we sanitize file paths gets in the way.

**Comment by mattcasters** [comment]
I think it's more correct to say that `file://///` requests the file resolution of the Windows system.  This wouldn't work on another operating system.

**Comment by Jerem59** [comment]
I find my problem
it's my share is full, so  dummy bug

It's possible to optimise log

Thx
