### ISSUE TITLE
[Feature Request]: Enhance "Enhanced JSON Output" to generate Arrays on field level

### ISSUE THREAD

**Issue by hansva** [apache/hop#3395]
### What would you like to happen?

With #3287 you can now create json arrays on the top level.
It might also be interesting to add a flag on field level to produce Arrays.
This way using the grouping you can create arrays in the elements.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by vdwals** [comment]
Hi,
Good idea. I'm happy I could contribute and I might be able to continue doing so. I have issues imagening the expected outcome.

|Nr|Name|Option|
|:----:|:----:|:----:|
|1|Feature|Column|
|1|Request|Wise|

With #3287, grouped by Nr.:
|outputValue|Nr|
|:----|:----:|
|{<br/>&nbsp;&nbsp;"result":&nbsp;{<br/>&nbsp;&nbsp;&nbsp;&nbsp;"name":&nbsp;[<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Feature",<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Request"<br/>&nbsp;&nbsp;&nbsp;&nbsp;],<br/>&nbsp;&nbsp;&nbsp;&nbsp;"option":&nbsp;[<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Column",<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Wise"<br/>&nbsp;&nbsp;&nbsp;&nbsp;]<br/>&nbsp;&nbsp;}<br/>}|1|

How would it look like with mixed column specific selection, e.g. "name" in array, "option" not?Should the inner Array be replicated?
|outputValue|Nr|
|:----|:----:|
|{<br/>&nbsp;&nbsp;"result":&nbsp;[<br/>&nbsp;&nbsp;&nbsp;&nbsp;{<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"name":&nbsp;[<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Feature",<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Request"<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"option":&nbsp;"Column"<br/>&nbsp;&nbsp;&nbsp;&nbsp;},<br/>&nbsp;&nbsp;&nbsp;&nbsp;{<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"name":&nbsp;[<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Feature",<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Request"<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;],<br/>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"option":&nbsp;"Wise"<br/>&nbsp;&nbsp;&nbsp;&nbsp;}<br/>&nbsp;&nbsp;]<br/>}|1|

Best regards
Dennis

**Comment by hansva** [comment]
You are right, I think with the option you added you should be able to create all you need.
You might need some extra steps but you should be able to create whatever json you need now, using the json fragment feature and the array feature...


Fyi was thinking about something like this:

| client  | host   | options  |
| ------- | ------ | -------- |
| client1 | host 1 | option a |
| client1 | host 1 | option b |
| client1 | host 1 | option c |
| client1 | host 1 | option d |
| client1 | host 2 | option a |
| client1 | host 2 | option b |
| client1 | host 2 | option c |
| client1 | host 2 | option d |

to convert to

```
{
 "client1" : [
   {
    "host": "host 1",
    "options" : [
       "option a",
       "option b",
       "option c",
       "option d"
       ]
    },
    {
     "host" : "host2"
     ....
     }
     ]
}
