### ISSUE TITLE
[Bug]: HttpPost / Authorization does not work

### ISSUE THREAD

**Issue by roy20021** [apache/hop#3407]
### Apache Hop version?

2.6.0

### Java version?

jdk-20.0.2.9-hotspot

### Operating system

Windows

### What happened?

The httppost transfomer is ignoring the "HTTP authentication" configuration:
![image](https://github.com/apache/hop/assets/1174320/6db51397-1822-431d-8d56-713e24b50858)
but it sends:
![image](https://github.com/apache/hop/assets/1174320/d149c7f3-a1db-4932-9860-751c8eb4ba57)

Currently,  I have worked around it by setting manually a "Authorization" header.

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by roy20021** [comment]
I have also checked that "Http Client" suffer of the same issue.

On the contrary, "REST Client" is working fine; however, the preemptive flag is ignored (always set to BASIC_PREEMPTIVE).

As a note, the "Http Post" and "Http Client" transformers use Apache Http 4.5 as the underlying HTTP client, while the 'REST Client' uses Glassfish Jersey.

---

In general, these 3 http-related transformers require some attention. What is the idea behind these transformers?
As far as I have understood:

- "Http Client" is a legacy for super simple scenarios 
- "REST Client" follows the "Representational state transfer" style by making requests around resources. It supersedes 'Http Client' but does not allow multipart requests.
- "Http Post" covers, only for the POST method, the missing multipart feature of the previous transformer.

Therefore:
- "Http Client" usage should be discouraged in favor of the "REST Client" and maybe even be deprecated and removed later on
-  'Http Post' might be extended to support the PUT method and have underlying code/features aligned with "REST Client". As an example, the "Rest Client" accepts encrypted password as credentials, "Http Post" does not.

**Comment by hansva** [comment]
Hi @roy20021 ,

You are right these transforms are turning a bit into a problem and have been created at separate points in time to solve very specific problems.
We also have request around supporting other forms of authentication (eg. Oauth, Bearer token, API key).

I think we should take a look at all the functionality these 3 transforms cover and see if we can combine all features in either one of them, or create a new transform.

The REST client seems like the best suspect to combine everything in, but I think that code might also need a refactoring to be a bit more readable.

**Comment by roy20021** [comment]
.take-issue

**Comment by nadment** [comment]
For your information, deprecated transformations can be marked with the @Deprecated annotation to indicate this to users.
