### ISSUE TITLE
Hop通过什么来定时调度任务

### ISSUE THREAD

**Issue by 172151295** [apache/hop#3419]

**Comment by bjackson-ep** [comment]
许多人会使用 cron 或其他一些调度程序，例如 AWS Eventbridge。

**Comment by 172151295** [comment]
> 许多人会使用 cron 或其他一些调度程序，例如 AWS Eventbridge。

我希望在任务调度方面hop可以有自己的任务调度平台，而不是使用其他别的项目，例如CKettle那样的集成调度平台，hotput任务调度就非常不错，不用再去找其他的调度平台。希望大佬们考虑一下

**Comment by 172151295** [comment]
> 许多人会使用 cron 或其他一些调度程序，例如 AWS Eventbridge。

【【国产化Kettle】CKettle调度与监控系列 - 02Hotpot使用-哔哩哔哩】 https://b23.tv/aQ5r3mm  可以看下我觉得这种方式非常不错，如果Hop能集成这样的调度也是非常不错的

**Comment by hansva** [comment]
We as a project have decided that we would not focus on scheduling, there are so many different ways all with their pros and cons that it would be too much work and it would all depend on your architecture

**Comment by 172151295** [comment]
> We as a project have decided that we would not focus on scheduling, there are so many different ways all with their pros and cons that it would be too much work and it would all depend on your architecture

调度不重要吗？？
