### ISSUE TITLE
项目是否可以全部汉化

### ISSUE THREAD

**Issue by 172151295** [apache/hop#3420]

**Comment by usbrandon** [comment]
您可以选择使用中文作为 UI。此外，如果您发现缺少翻译，您可以使用翻译工具添加它。 https://hop.apache.org//manual/latest/getting-started/hop-tools.html#_hop_translator

**Comment by 172151295** [comment]
我希望后期可以全部汉化

**Comment by hansva** [comment]
That documentation is outdated, we have a simpler way to contribute translations: https://translate.project-hop.org/
