### ISSUE TITLE
In "Simple evaluation", when "Evaluate" "Variable" is selected, the label "Success when variable" is too short

### ISSUE THREAD

**Issue by gmitter-ef** [apache/hop#3461]
### Apache Hop version?

2.6

### Java version?

OpenJDK 11

### Operating system

Windows

### What happened?

In "Simple evaluation", when "Evaluate" "Variable" is selected, the label "Success when variable" is too short, it should be "Success when variable set", not only "Success when variable".

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui, Component: Workflows

**Comment by gmitter-ef** [comment]
![Simple_evaluation_too_short_label](https://github.com/apache/hop/assets/126489773/b7e00c5a-9993-4a66-b34b-901ef70fc1e9)

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
indeed, the text is there. make the dialog a bit bigger :)

**Comment by gmitter-ef** [comment]
OK, thanks. Perhaps the default size of the dialog then should be bigger such that the text is visible by default? Or does it happen to be a problem of only my UI?

**Comment by hansva** [comment]
giving slightly more space by default might not be a bad idea for that Action.
But once changed dialog sizes are remembered by the UI
