### ISSUE TITLE
[Feature Request]:  Change the Execution Information icon

### ISSUE THREAD

**Issue by simonaubertbd** [apache/hop#3464]
### What would you like to happen?

As of today, it's the icon used everywhere for a geographic site.

![image](https://github.com/apache/hop/assets/46959192/c6402fbb-0165-47a3-b081-04769532f043)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
Here are 2 proposals

![execution-2](https://github.com/apache/hop/assets/39568358/eb6a6956-8ada-4be9-b965-6b33f9cf6db6)
![execution-1](https://github.com/apache/hop/assets/39568358/7199813f-5783-449e-aa2f-91ce23628671)

**Comment by smalos** [comment]
Alternatively, opt for a play symbol such as [this](https://commons.wikimedia.org/wiki/File:Play_symbol.png) or a comparable alternative.
