### ISSUE TITLE
[Feature Request]:  "Edit" the tool should be faster to use : open it on first click

### ISSUE THREAD

**Issue by simonaubertbd** [apache/hop#3465]
### What would you like to happen?

I would like to access faster to the edit tool window : I have to do one click on the tool and then another click on the edit button. I'm not exactly sure of the solution but the UI should reflect the most common thing a user do.

Best regards,

Simon

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
You can click on the name of a transform to directly open the edit window. In the next release we have changed it to a hyperlink to make this feature more clear.

**Comment by simonaubertbd** [comment]
Hello @hansva  Thanks, I feel somehow idiot now 😆  On the different tools I use, the result of clicking the name or the icon is the same.

By the way, don't you thing the window we get when clicking on the icon could be reduced ? It looks really huge on my screen. 
Best regards,
Simon
