### ISSUE TITLE
[Bug]: Error while opening zip file created by Zip file action

### ISSUE THREAD

**Issue by pradoshsahoo2021** [apache/hop#3472]
### Apache Hop version?

2.6

### Java version?

jdk11

### Operating system

Linux

### What happened?

In my workflow I used the Zip file action to zip a file. But when I am trying to unzip it I am getting below error. Anything changed with Zip file transform? I am using Hop 2.6.

Error:
Archive: file1.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive
[students - Sheet1.csv](https://github.com/apache/hop/files/13530300/students.-.Sheet1.csv)
[test.zip](https://github.com/apache/hop/files/13530301/test.zip)
[TEST_ZIP_FILE.zip](https://github.com/apache/hop/files/13530314/TEST_ZIP_FILE.zip)

### Issue Priority

Priority: 2

### Issue Component

Component: Workflows

**Comment by bamaer** [comment]
confirmed
