### ISSUE TITLE
[Bug]: Simple evaluation Action Success conditions do not match the online documentation

### ISSUE THREAD

**Issue by Mattang-Dan** [apache/hop#3487]
### Apache Hop version?

2.8

### Java version?

openjdk 11.0.19 2023-04-18 LTS OpenJDK Runtime Environment Microsoft-7621296 (build 11.0.19+7-LTS) OpenJDK 64-Bit Server VM Microsoft-7621296 (build 11.0.19+7-LTS, mixed mode)

### Operating system

Windows

### What happened?

The Simple evaluation Action Success conditions do not match the online documentation. There are 11 options online, but only 8 in the drop down list, and some are different.
![SimpleEvaluationAction](https://github.com/apache/hop/assets/100213981/02b0e97d-e8cf-4006-a720-c58656b2619e)

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation, Component: Hop Gui

**Comment by nadment** [comment]
All conditions are available with the STRING type; for the NUMBER type, there is less choice, but this is deliberate.

**Comment by nadment** [comment]
Close as this is not a bug
