### ISSUE TITLE
[Bug]: Pushing commits to remote fails. Got stuck in a loop while entering username and password

### ISSUE THREAD

**Issue by ericsanchezstratebi** [apache/hop#3492]
### Apache Hop version?

2.7

### Java version?

11.0.18

### Operating system

Windows

### What happened?

<when trying to push commits to repo, I get prompted to enter Git username and password, but nothing happens I get asked again for my username and password and get stuck in a loop. pls fix it

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
which git service are you using?

**Comment by ericsanchezstratebi** [comment]
github

De: Hans Van Akelyen ***@***.***>
Enviado el: lunes, 11 de diciembre de 2023 14:50
Para: apache/hop ***@***.***>
CC: Eric Sánchez Tamayo ***@***.***>; Author ***@***.***>
Asunto: Re: [apache/hop] [Bug]: Pushing commits to remote fails. Got stuck in a loop while entering username and password (Issue #3492)

CORREO EXTERNO, ten cuidado con los enlaces y archivos adjuntos.

which git service are you using?

**Comment by ericsanchezstratebi** [comment]
github

**Comment by hansva** [comment]
We will improve the documentation but this is probably caused by using your regular password and not a personal access token. There are other tickets to improve the UI and this will be taken into account.
