### ISSUE TITLE
[Bug]: help button no longer works in 2.7.0

### ISSUE THREAD

**Issue by enricomariam42** [apache/hop#3493]
### Apache Hop version?

2.7.0

### Java version?

openjdk 11.0.9.1 2020-11-04

### Operating system

Linux

### What happened?

help button no longer works. 
Looks like 2.7.0->latest redirect is missing
E.g. https://hop.apache.org/manual/2.7.0/pipeline/transforms/dummy.html results in :
`The requested URL was not found on this server.`

### Issue Priority

Priority: 1

### Issue Component

Component: Documentation
Component: Website

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
should be fixed now.
