### ISSUE TITLE
[Feature Request]: Text input transform : Offer option to define what TEXT should represent null values.

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#3509]
### What would you like to happen?

Many file import and export utilities allow people to define characteristics of their files, like delimiters and how NULL should be represented.  What I propose is adding this feature to the Text Input transform so if someone exported a file where in certain fields a word of their choosing is the only token present, that would be interpreted as a NULL.

Today, the workaround requires taking the field as a String, since the values for "NULL" string text could conflict with say, a Date Time or Integer, etc.   Then one has to use "Null if" on the String columns, then a Select to straighten out metadata.   That is a lot of overhead that could have been prevented by simply allowing someone to specify a token for null right at import.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
Hi Brandon,

This is what the "Null if" column does in the fields section of the text file input.
I just tested it on a simple string field and it works as expected.

**Comment by usbrandon** [comment]
Wow.... 10 years and I never knew that...  now I know...
