### ISSUE TITLE
[Feature Request]: Oracle databases do support prepared statement metadata retrieval

### ISSUE THREAD

**Issue by bcolas** [apache/hop#3515]
### What would you like to happen?

As Oracle database have supported Prepared Statement Metadata Retrieval since 11g
Could you please proceed to the following change in plugins/databases/oracle/src/main/java/org/apache/hop/databases/oracle/OracleDatabaseMeta.java ?

Modify isSupportsPreparedStatementMetadataRetrieval method as :
`public boolean isSupportsPreparedStatementMetadataRetrieval() {
    return true;
  }`

The impact on performance is huge (15 years of experience with PDI)

### Issue Priority

Priority: 2

### Issue Component

Component: Database

**Comment by hansva** [comment]
.take-issue
