### ISSUE TITLE
[Feature Request]: Simple Mapping Transform UI Dialog can automatically populate output target field name 

### ISSUE THREAD

**Issue by joebo** [apache/hop#3529]
### What would you like to happen?

It would be convenient for the simple mapping transform to automatically populate the column "fieldname to target transform" when Get Fields is clicked. This is especially helpful on transforms with many outputs

![image](https://github.com/apache/hop/assets/151573/e83864a8-2811-44c7-adcb-f5c08a3a3929)

I've implemented this in my fork as: https://github.com/joebo/hop/commit/9283a93dd810e0bb2a45d578c29e0f1581e05786

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by joebo** [comment]
I'm happy to .take-issue and submit a PR if there is a consensus

**Comment by sramazzina** [comment]
Sounds a good improvement to me. I suggest to add a "Get fields" button as in other transforms instead of automatically populating it without any interaction from the user.

**Comment by joebo** [comment]
> Sounds a good improvement to me. I suggest to add a "Get fields" button as in other transforms instead of automatically populating it without any interaction from the user.

Thanks sramazzina, fortunately there is already a "Get Fields" button, however it only populates the first column in my screenshot above. The proposed feature would populate the 2nd column as well so the user does not need to type it in. Without a field name in the 2nd column, the resulting output fields have no column name. A more invasive change would be to default to the "mapping transform name" (1st column) if the 2nd column is blank, however I am recommending the simple UI change instead.

**Comment by hansva** [comment]
The simple UI change sounds great! would love a pull request for that!

**Comment by hansva** [comment]
.take-issue
