### ISSUE TITLE
STRING OPERATIONS (INITCAP) DON'T WORK [Bug]: 

### ISSUE THREAD

**Issue by jonatachampanflowinvest** [apache/hop#3538]
### Apache Hop version?

2.7.0 (2023-11-17 12.19.09)

### Java version?

java version "17.0.7" 2023-04-18 LTS

### Operating system

Windows

### What happened?

The option 'InitCap' don't work, for example: COMÉRCIO > Comércio.
![bug_hop](https://github.com/apache/hop/assets/151850972/1bf50422-fb42-45c5-876a-ac6b07ed38da)

### Issue Priority

Priority: 3

### Issue Component

Component: Pipelines

**Comment by openinbigdata** [comment]
Following

**Comment by openinbigdata** [comment]
Following

**Comment by nadment** [comment]
It's a funny way of working, but you'll have to put it in lower case first beacuse only the first character of each word is changed.
It would have been more logical to convert the rest of each word to lower case at the same time.

![image](https://github.com/apache/hop/assets/39568358/0a92db99-152f-4a1a-b767-9a139a418deb)

**Comment by jonatachampanflowinvest** [comment]
Hummm okay, it really works!! Thanks.

**Comment by nadment** [comment]
Should we close the request or change the logic?

**Comment by hansva** [comment]
I suggest changing the logic and adding the lower when doing initcap

**Comment by jonatachampanflowinvest** [comment]
I prefer the logic of 'Pentaho' but it's okay to work that way.

**Comment by hansva** [comment]
I am pretty sure that logic will not have changed and is the same

**Comment by nadment** [comment]
If I modify the behavior, it will also apply to the "initCap" JavaScript function. I think this is good.
