### ISSUE TITLE
[Bug]: Step Table Input does not bring data in the date column

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#3544]
### Apache Hop version?

2.3 and 2.6

### Java version?

11

### Operating system

Windows

### What happened?

Hello.

Sorry for my English, I'm using Google Translate.

I want to report a BUG where Step Table Input is not bringing data from a date column.

I tested the following scenarios:

One connection using what is called a db_link and another direct connection.

By connecting to db_link, the data is read seamlessly.

With direct connection, the step does not bring the column data.

It was tested on versions 2.3 and 2.6

Conection with db_link
![image](https://github.com/apache/hop/assets/70301866/4ccf902e-6abe-4556-9c0a-b40d92c8b141)

Direct Conection
![image](https://github.com/apache/hop/assets/70301866/73da8f3e-3e0d-4a2e-aa52-9da370113fe9)

Tks

### Issue Priority

Priority: 2

### Issue Component

Component: Actions

**Comment by hansva** [comment]
What is the database type?
Is the support timestamp option enabled in the advanced tab of the database connection?

**Comment by pauloricardoferreira** [comment]
Not enabled

![image](https://github.com/apache/hop/assets/70301866/79de2987-5355-4133-9ef5-4c7bca07fce1)

Is it necessary to leave it enabled?

**Comment by hansva** [comment]
If the database supports it (I don't know which database type you are using) enable "supports the boolean data type" and "supports the timestamp data type"

**Comment by pauloricardoferreira** [comment]
I am using Oracle Data Base

**Comment by hansva** [comment]
Then I would turn on those options.
you might also want to add the following to the options tab oracle.jdbc.mapDateToTimestamp=false

https://hop.apache.org/manual/latest/database/databases/oracle.html

**Comment by pauloricardoferreira** [comment]
OK.

I will carry out the tests and publish the results in this issue.

Thanks

**Comment by hansva** [comment]
Normally we turn that on by default on more recent versions of Hop (if you make a new connection).
Good idea to maybe add an other hint in the documentation as this issue does come up from time to time.
