### ISSUE TITLE
Error - Check DB - NullPointerException - Database with Variables - Hop Server

### ISSUE THREAD

**Issue by mathsteen** [apache/hop#3551]
### Apache Hop version?

2.7

### Java version?

11

### Operating system

Linux

### What happened?

Hello!
Good afternoon,

I have a problem when running a simple Workflow via Hop Server where a database is checked that is set to environment variables and is returning: NullPointerException

I will attach the worfkflow and the airflow dag log and the prints.

Remembering that locally it works normally.

Thanks!

Version Airflow 2.8.

Log Dag:
[dag_id=hop_teste_run_id=scheduled__2024-01-16T17_20_00+00_00_task_id=hop_teste_attempt=1.log](https://github.com/apache/hop/files/13954817/dag_id.hop_teste_run_id.scheduled__2024-01-16T17_20_00%2B00_00_task_id.hop_teste_attempt.1.log)

WorkFlow
[teste.txt](https://github.com/apache/hop/files/13954855/teste.txt)

### Issue Priority

Priority: 3

### Issue Component

Component: Database, Component: Hop Server

**Comment by hansva** [comment]
it's a bit difficult to see from this log.
But I think you have not added the metadata needed to run this project.
Database connections are stored inside the project metadata folder if those are not available on the server you will get this error.

you can take a look at our [airflow how-to guide ](https://hop.apache.org//manual/latest/how-to-guides/run-hop-in-apache-airflow.html#_what_is_apache_airflow)

FYI to set the metadata folder on the server you need to edit the server-config.xml and add it to the metadata_folder section. But I would not use Hop Server for airflow use-cases as it does not really have added value.

**Comment by mathsteen** [comment]
Docker:

![image](https://github.com/apache/hop/assets/116126871/02aa5402-3812-4199-8092-b886409770d0)

**Comment by pauloricardoferreira** [comment]
I'm also having the same problem.

**Comment by pauloricardoferreira** [comment]
Cases:

Requesting the Webserver to run through Hop Gui was successful.

It was even possible to read the data from the container as shown in the image below

![image](https://github.com/apache/hop/assets/70301866/7a05759a-31a4-49f9-bf99-9eb818b13125)

**Comment by pauloricardoferreira** [comment]
Sorry.

The problem occurred because the Airflow Plugin needed a file called metadata.json which is obtained by exporting through the Apache Hop interface.

It's possible to make this the default.

Create this file in the project folder automatically for each change made to the project?

Tks

**Comment by mathsteen** [comment]
Sorry for the inconvenience,

We found the problem, as mentioned above!

Thank you very much!

**Comment by nadment** [comment]
So this request can be closed?

**Comment by pauloricardoferreira** [comment]
yes
