### ISSUE TITLE
[Bug]: In calculator transform when press enter, close dialog box Select the calculation type

### ISSUE THREAD

**Issue by openinbigdata** [apache/hop#3555]
### Apache Hop version?

2.7

### Java version?

java version "11.0.18" 2023-01-17 LTS

### Operating system

Windows

### What happened?

Once the mouse cursor is inside the filter field of the Select the calculation type window, when pressing the enter key to filter the searched text, this window closes. We can only filter by clicking on the Refresh selection icon

The same problem happens on both Windows and MacOS

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui, Component: Transforms

**Comment by openinbigdata** [comment]
The same error happens trying to filter in Get system info transformation

**Comment by nadment** [comment]
Good catch, this is a general bug in the EnterSelectionDialog class.
