### ISSUE TITLE
[Task]: Check the step Calculator

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#3557]
### What needs to happen?

I can't tell if it's a BUG.

When I select the Value type as Timestemp, the step calculator does not allow me to select the mask

Java Version: 11
Hop Version: 2.7

![image](https://github.com/apache/hop/assets/70301866/1fac67f8-489a-49e8-82f2-68ee82c60a1a)

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by nadment** [comment]
This is a bug for all transformations that use a format column with the TIMESTAMP type, so we should propose a format like for the DATE type. Good catch !

**Comment by pauloricardoferreira** [comment]
Tks
