### ISSUE TITLE
[Bug]: Exclude Regular Expression in Text file input not work

### ISSUE THREAD

**Issue by openinbigdata** [apache/hop#3583]
### Apache Hop version?

2.7

### Java version?

java version "11.0.18" 2023-01-17 LTS

### Operating system

Windows

### What happened?

The option Exclude Regular Expression in File tab of Text File Input transform not work and not persiste when press OK button 

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by ribeiro-rogerio** [comment]
I'll keep an eye on this update

**Comment by openinbigdata** [comment]
This is not an error, but rather the filling logic was done incorrectly. The File or directory, Regular expression and Exclude regular expression fields need to be filled in and when you click on the Add button, this information goes to the Selected files grid
