### ISSUE TITLE
[Bug]: Transform "Generate random value" Unexpected error.  ERROR: java.lang.NullPointerException

### ISSUE THREAD

**Issue by qmolla** [apache/hop#3592]
### Apache Hop version?

2.7.0

### Java version?

openjdk version "11.0.18" 2023-01-17 LTS (windows) 

### Operating system

Windows

### What happened?

Transform **Generate random value** for types  _**Random string**_, _**Random integer**_ and _**Random number**_  gives us an unexpected error. 

2024/01/30 14:24:31 - Generate random value.0 - ERROR: Unexpected error
2024/01/30 14:24:31 - Generate random value.0 - ERROR: java.lang.NullPointerException
2024/01/30 14:24:31 - Generate random value.0 - 	at org.apache.hop.pipeline.transforms.randomvalue.RandomValue.getRandomValue(RandomValue.java:67)

![image](https://github.com/apache/hop/assets/15668226/526eaa1d-af48-4a4d-a0cc-cbf85b9e628f)

Same Error running pipeline on ubuntu server 20.04  ( hop 2.7.0  openjdk version "11.0.21" 2023-10-17)

The same pipeline on hop 2.6 runs wihtout error.

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by nadment** [comment]
The random generation transformation needs to have rows as input, but an NPE exception is not correct.
