### ISSUE TITLE
Question - Paginated API

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#3594]
Hello.

I'm trying to extract data from an API, where the next page is a token.

I carried out the LOOP process according to the documentation, but the LOOP does not end.

What should I do?

There is a cache or cookie system in hop, just like there is in the browser.

Thanks

**Comment by bamaer** [comment]
https://hop.apache.org/manual/latest/how-to-guides/loops-in-apache-hop.html

check the Repeat and End Repeat actions, but please keep the issues for feature request, bug reports etc. 
We have the [chat](https://chat.project-hop.org) and [mailing lists](https://hop.apache.org/community/mailing-list/) for discussions and general questions
