### ISSUE TITLE
[Feature Request]: switching JVM LTS Version from 11 to 17/21 

### ISSUE THREAD

**Issue by seltner** [apache/hop#3605]
### What would you like to happen?

Have you already planned a change from LTS JVM java11 to java17 or java21  ?

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui, Component: Hop Run

**Comment by hansva** [comment]
Yes, we will start moving to Java 17 soon.
some experimental test builds have already been done and the code compiles but tests are failing.
