### ISSUE TITLE
[Bug]: Save dialog looses project's context

### ISSUE THREAD

**Issue by sramazzina** [apache/hop#3609]
### Apache Hop version?

2.8.0-SNAPSHOT

### Java version?

openjdk 11

### Operating system

Linux

### What happened?

When you change project , if you tray to save a pipeline or a job the save dialog always refers to the previous project you came from.

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
If you disable the global bookmarks in your settings it will be project aware.
