### ISSUE TITLE
[Feature Request]: File Explorer Refresh

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#3619]
### What would you like to happen?

I would like to propose improvements to the File Explorer component.

When a file is changed or deleted, it is necessary to Refresh so that it is updated in the GUI.

1 - Add Auto-refresh for any changes

2 - If any folder is open as in the image, after refresh it will maintain the current state of the view.

![image](https://github.com/apache/hop/assets/70301866/d5abdd88-078b-4a6b-bf6f-9b4efcedbdbf)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
I tried adding listeners to the file system, but these are unpredictable.
Changes made:
- When switching from the pipeline perspective to the file explorer perspective a refresh is triggered
  - When creating new pipelines this will make them show up
- When doing a git Pull the explorer is also refreshed to show the new state
