### ISSUE TITLE
[Bug]: Export linked resources does not work when using remote pipeline engine

### ISSUE THREAD

**Issue by hansva** [apache/hop#3623]
### Apache Hop version?

2.8.0-SNAPSHOT

### Java version?

11

### Operating system

macOS

### What happened?

When using the remote pipeline engine and enabling "export linked resources" the endpoint registerPipeline is called and not registerPackage

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Server

**Comment by harrisward** [comment]
Was looking into this issue with Brandon and Bart. Attached a sample where if the main workflow is run then all is golden but if the sub pipeline is run the execution fails
[dummy-data.hpl.zip](https://github.com/apache/hop/files/14336841/dummy-data.hpl.zip)

**Comment by hansva** [comment]
I noticed last week that when you turn on export resources to server on a remote pipeline configuration. It actually doesn't do that. It sends a single pipeline and not a bundle. I'll take a look at it in one of the next days as I am also working around this area atm.

**Comment by usbrandon** [comment]
Thank you Hans.
