### ISSUE TITLE
[Bug]: Translation website https://translate.project-hop.org/ is unavailable

### ISSUE THREAD

**Issue by jefersonnavarro** [apache/hop#3639]
### Apache Hop version?

all

### Java version?

all

### Operating system

Other

### What happened?

Translation website https://translate.project-hop.org/ is unavailable. Error 502 Bad Gateway
nginx/1.18.0 (Ubuntu)

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue

yep, that one is my fault I'll try and get it back asap

**Comment by jblum66** [comment]
Error 504 again. Web site is no more available today.
