### ISSUE TITLE
[Bug]: Excel File input unable to read calculated cell

### ISSUE THREAD

**Issue by kenvang** [apache/hop#3670]
### Apache Hop version?

2.7.0

### Java version?

JDK-17

### Operating system

Windows

### What happened?

The Excel File Input transform when assigned an excel file and with the default parameters (the fields and field types the transform recommends), whenever the transform arrives at a specific row/field (look at example) the transform gives a HopCelValue exception: Cannot convert field "" from cell on sheet 1, row 68, column 5:, unsupported type Number formula with value: 34002.227. This same exception is also triggered when the troublesome fields are read as a string.
[[Bug] Excel File input unable to read calculated cell.zip](https://github.com/apache/hop/files/14401692/Bug.Excel.File.input.unable.to.read.calculated.cell.zip)

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by sramazzina** [comment]
Hi @kenvang. First of all, because jdk 17 is not yet currently supported by Hop, can you please make a try with jdk 11? 

Thanks for your cooperation
