### ISSUE TITLE
[Feature Request]: Show spaces in lables in the UI instead of %20.  The encoded spaces really look ugly.

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#3674]
### What would you like to happen?

![image](https://github.com/apache/hop/assets/1233654/d57dc4c3-a996-4319-b79c-a4d9230b6e06)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
The bug seems to occur when saving a pipeline for the first time. Then when you reopen it, there's no %20%.

**Comment by nadment** [comment]
The bug comes from the HopGuiFileReplaceHomeVariable class
