### ISSUE TITLE
[Bug]: Step Selected Values ​​Date Format

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#3681]
### Apache Hop version?

2.7 and 2.8

### Java version?

11

### Operating system

Windows

### What happened?

I noticed a strange body in Step Selected Values.

The Pipeline receives a DateTime, example: 2024-01-01 23:59:59, and with Step Selected Values ​​it should convert it to date 2024-01-01.

Conversion is not occurring.

Would this be the same behavior as Step?

![image](https://github.com/apache/hop/assets/70301866/5a35fbe7-9ce7-4da1-b00f-64e53f68460e)

![image](https://github.com/apache/hop/assets/70301866/8e9e0a0d-979a-4666-ab06-d5bb1a407243)

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by hansva** [comment]
If the original type is already a date there is no conversion happening, the only change that's happening is we only show the data formatted in the requested format mask. but behind the scenes, it's still a java date containing all the information.

If you want to strip the time you can either convert to a string, or use an other transform (formula) to set the time to 0 hours

**Comment by pauloricardoferreira** [comment]
I converted it to String yyyy-mm-dd and then to Date it reset the time.

tks
