### ISSUE TITLE
[Bug]: Bulk load into MSSQL

### ISSUE THREAD

**Issue by alexismorison95** [apache/hop#3693]
### Apache Hop version?

2.7.0

### Java version?

11.0.13

### Operating system

Windows

### What happened?

When i use the component Bulk load into MSSQL in a SQL Server database Apache HOP show me this error: "Bulk load into MSSQL - ERROR: Target database [MyDB] is not a MSSQL Database!".

![image](https://github.com/apache/hop/assets/43044860/8d471a34-1f83-4e5a-a6dd-8978adfa4f43)

I'm using SQL Server 2019.

Thanks!

### Issue Priority

Priority: 2

### Issue Component

Component: Database, Component: Hop Gui

**Comment by nadment** [comment]
The plugin checks if the connection is "MS SQL Server", but ignores "MS SQL Server (Native)". I can make a PR to support the 2 connection types, but I can't test it.

**Comment by hansva** [comment]
@alexismorison95 , can you test the changes @nadment made, I also don't have access to an environment to test this.
