### ISSUE TITLE
[Bug]: macOS HOP Client GUI suddenly blank

### ISSUE THREAD

**Issue by b-thiswatch** [apache/hop#3696]
### Apache Hop version?

2.7.0 and older

### Java version?

openjdk version "11.0.22" 2024-01-16

### Operating system

macOS

### What happened?

I am not exactly sure what caused this, but my HOP GUI is blank now. I was using 2.5.0 and also tried the latest 2.7.0, but it's blank.

<img width="1936" alt="Screenshot 2024-03-05 at 20 55 02" src="https://github.com/apache/hop/assets/106271647/f9bc28d7-a3f8-4884-877b-5f76ac2b9e52">

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
Hi, this is probably related to https://github.com/apache/hop/issues/3604
There seems to be a problem with the recent Adopt/Temurin Java builds and SWT.

I currently use the Azul JDK on my system to get around the problem.

**Comment by b-thiswatch** [comment]
thanks @hansva,

it was an udpate of openjdk@11 then. trying out hop-web docker container now :)
