### ISSUE TITLE
[Bug]: Parameters/variables grids do not reliably delete rows

### ISSUE THREAD

**Issue by davemc50** [apache/hop#3712]
### Apache Hop version?

2.7

### Java version?

11.0.02

### Operating system

Linux

### What happened?

Create some rows in a properties dialog, like properties/variables to set, in the desktop gui on linux, in the pipeline or workflow editor.

Press the rubbish bin button to delete a row

Either the wrong row gets deleted (the one above or below), or the next field right's deleted value persists over the top of the retained row.  Doesn't happen all the time, but often enough that every delete needs to be treated with caution.

There are some grid refresh events that seem to happen, like the cached grid contents is unaware of the delete, and repopulates the gird with stale values. Could also be that the grid doesn't have proper row ids or sequence id's in the background, and is getting muddled about which row should be deleted.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
can confirm that you have to make sure you have a line selected and are not in a field.
When you are in a field the delete is not acting the way it's supposed to
