### ISSUE TITLE
[Bug]: Select Values Meta-data tab "get fields to change" not working correctly

### ISSUE THREAD

**Issue by campen** [apache/hop#3721]
### Apache Hop version?

2.8

### Java version?

11.0.22

### Operating system

macOS, Linux

### What happened?

In Select Values, when I navigate the the Meta-data tab and select "Get fields to change"

Two things are not working...

1. The data type is not being populated after pressing the get fields to change, but field length is populated in most cases. 
2. Date fields are given a field length of 7

Expected behavior: data type and field lengths/formats should be populated based on prior stream metadata.

### Issue Priority

Priority: 2

### Issue Component

Component: Transforms

**Comment by nadment** [comment]
1. The data type is not being populated after pressing the get fields.
> Bug confirmed, easy to fix

2. Date fields have a length of 7
> I don't think this is a bug, it depends on the input fields in the stream.

**Comment by campen** [comment]
I guess the field length of 7 was confusing as the data type was not being populated. I agree with your assessment. Dave CampenOn Mar 14, 2024, at 3:42 PM, Nicolas Adment ***@***.***> wrote:﻿

The data type is not being populated after pressing the get fields.


Bug confirmed, easy to fix


Date fields have a length of 7


I don't think this is a bug, it depends on the input fields in the stream.
