### ISSUE TITLE
[Bug]: Since 2.8, "Zip file" doesn't allow for conditional outgoing hops, only unconditional

### ISSUE THREAD

**Issue by gertwieland** [apache/hop#3735]
### Apache Hop version?

2.8

### Java version?

openjdk 11.0.21 2023-10-17

### Operating system

Windows

### What happened?

Transform "Zip file" does not allow for conditional outgoing hops (green, orange), but only for unconditional (white circle).
This breaks pipelines where conditional hops were used.

Screenshot shows an old pipeline which is not running now.

<img width="297" alt="image" src="https://github.com/apache/hop/assets/51762835/47210bc9-eeb9-4fc5-a66a-b180363735fe">

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Gui, Component: Transforms

**Comment by gertwieland** [comment]
To reproduce, simply put a hop between "Zip file" and any other transform (eg a dummy). Try to make the hop conditional.

**Comment by bamaer** [comment]
confirmed
