### ISSUE TITLE
[Bug]: help button no longer works in 2.8.0

### ISSUE THREAD

**Issue by gutknecht** [apache/hop#3749]
### Apache Hop version?

2.8.0

### Java version?

17.0.1 2021-10-19 LTS

### Operating system

macOS

### What happened?

Help button goes to wrong url

Example:
https://hop.apache.org/manual/2.8.0/pipeline/transforms/groupby.html. -> Not found
Should be: https://hop.apache.org/manual/latest/pipeline/transforms/groupby.html

Maybe was already fixed in issue [3493](https://github.com/apache/hop/issues/3493), but did not make it into the release of 2.8?

### Issue Priority

Priority: 3

### Issue Component

Component: Website

**Comment by hansva** [comment]
.take-issue

You are right I forgot a step during the release process! Thanks for the ticket!

**Comment by hansva** [comment]
should be resolved now
