### ISSUE TITLE
[Bug]: demo is down

### ISSUE THREAD

**Issue by simonaubertbd** [apache/hop#3763]
### Apache Hop version?

2.8

### Java version?

N/A

### Operating system

Other

### What happened?

Hello all,

Both demos are down :
http://demo.hop.apache.org/ui
http://demo.hop.apache.org:8080/ui
`no healthy upstream`
![image](https://github.com/apache/hop/assets/46959192/21756bc2-7104-467e-8ae1-37d8c4dbbcba)

### Issue Priority

Priority: 3

### Issue Component

Component: Website

**Comment by hansva** [comment]
Correct they have been shut down, are they still referenced on the site somewhere?

**Comment by simonaubertbd** [comment]
@hansva  I don't know, the url were in my bookmarks. Are they replaced or something or just something you don't think necessary anymore?

**Comment by hansva** [comment]
low number of visits, high cost, and some security concerns made us shut them down for now.
