### ISSUE TITLE
[Bug]: Synchronize after merge

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#3767]
### Apache Hop version?

2.7 and 2.8

### Java version?

11

### Operating system

Windows

### What happened?

For some reason, after making some changes to the step, when clicking on the last field, it changes the Table Field name to N.

It happened a few times

![image](https://github.com/apache/hop/assets/70301866/faf6a609-2afb-4c33-9d33-e4d8392b1b69)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by nadment** [comment]
Appears similar to issue #3712
