### ISSUE TITLE
[Bug]: Fix HOP_PLATFORM_RUNTIME=Server in hop-server.bat

### ISSUE THREAD

**Issue by nadment** [apache/hop#3773]
### Apache Hop version?

2.8.0-SNAPSHOT

### Java version?

Java 11

### Operating system

Windows

### What happened?

Fix HOP_PLATFORM_RUNTIME=Server in hop-server.bat 

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Server

**Comment by hansva** [comment]
does this actually change anything? I mean code/functionality wise?

**Comment by nadment** [comment]
I just discovered this error in the BAT by accident, when I was looking for the relevant attributes for OpenTelementry.

I'm not sure, maybe disable double buffering when generating the graph image on a Windows server.

// Do double buffering to prevent flickering on Windows
boolean needsDoubleBuffering = Const.isWindows() && "GUI".equalsIgnoreCase(Const.getHopPlatformRuntime());
