### ISSUE TITLE
[Feature Request]: Support CrateDB data sources

### ISSUE THREAD

**Issue by xdelox** [apache/hop#3790]
### What would you like to happen?

We'd like to add this new type of data source, in order to write via the native JDBC driver and take advantage of its customisation from PostgreSQL JDBC driver.

### Issue Priority

Priority: 3

### Issue Component

Component: Database

**Comment by hlcianfagna** [comment]
Just for reference, there is this quick tutorial https://community.cratedb.com/t/using-apache-hop-with-cratedb/1754 on how to use the standard PostgreSQL driver with Apache Hop to read from and write to CrateDB.

**Comment by bamaer** [comment]
cool! thanks for sharing, @hlcianfagna!

**Comment by hansva** [comment]
done by #3791
