### ISSUE TITLE
[Task]:  Updating dependencies

### ISSUE THREAD

**Issue by KBoersch** [apache/hop#3793]
### What needs to happen?

Here is our most recent trivy-scan from hop 2.8.0.

Quite a good progress, I would say :)

[Trivy-report-hop-280.xlsx](https://github.com/apache/hop/files/14905740/Trivy-report-hop-280.xlsx)

### Issue Priority

Priority: 3

### Issue Component

Component: Other

**Comment by hansva** [comment]
The never ending struggle...
There is no ticket for it yet but we have this task nagging in the back of our head to have a daily report of trivy and docker scout somewhere.

**Comment by hansva** [comment]
.take-issue
