### ISSUE TITLE
[Bug]: Hop GUI - problem in deleting rows from parameter grids

### ISSUE THREAD

**Issue by dave-csc** [apache/hop#3801]
### Apache Hop version?

2.8.0

### Java version?

openjdk version "21.0.2" 2024-01-16

### Operating system

Linux

### What happened?

Setup any transform or action that can be parametrized with a grid (e.g. Fake data, Pipeline executor, Write to log).

When you delete a row from the grid, the value in the same column from the next row is selected: then if you type ENTER, the value in the first column is changed or deleted.

Using Ubuntu 22.04.4 LTS on VirtualBox for Windows

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
This should be resolved in the latest builds https://github.com/apache/hop/pull/3787
You can test this by downloading a [development build]([here](https://repository.apache.org/content/repositories/snapshots/org/apache/hop/hop-client/2.9.0-SNAPSHOT/))

**Comment by pauloricardoferreira** [comment]
OK.

I will carry out the tests and post the results.

**Comment by dave-csc** [comment]
Hello,

I was trying similar tests on the newly released version **2.9.0** of Hop and the component Set Variables, and this happens:
- fill the table using "Get fields" and then select a cell in the row to delete and delete it
- the corresponding cell in the same row stays selected and shows the text that was included in the deleted row
- if you type ENTER, this text replaces the content of the first cell (as described above). If it's a combo box it can assume a value that's not among the possible choices
- if you type ESC, no change is performed if the selected cell is a normal text field, but it is if the selected cell is a combo box

So the issue is not yet resolved... 😢

**Comment by hansva** [comment]
.take-issue
