### ISSUE TITLE
[Feature Request]: Rest Transform Timeout

### ISSUE THREAD

**Issue by marwari8** [apache/hop#3811]
### What would you like to happen?

**Observed**
Currently calling a rest transform that takes too much time will quicky abort the process due to a hardcoded timeout value.
the timeout is currently hardcooded in ApacheHop, Bart Maerens confirmed on Mon 26/02/2024 20:28 that this is not yet possible (thanks for the quick confirmation)

**Expected**
Allow to specify a timeout in the rest transform. 
maybe as a quick and dirty (interim) solution : allow to set a global parameter for all rest transform (you will not need to change the UI)

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui, Component: Hop Server, Component: Hop Web

**Comment by nadment** [comment]
I'm going to add two timeout possibilities, for the connection and for reading data.
![image](https://github.com/apache/hop/assets/39568358/a09759e3-2e25-41e7-95a3-899e79583165)

**Comment by hansva** [comment]
@nadment maybe we should add an indicator to the label. is that timeout in seconds? milliseconds?

**Comment by nadment** [comment]
I've added the indication and updated the document too.
