### ISSUE TITLE
[Bug]: Changing the field a changing sequence depends on crashes the app.

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#3815]
### Apache Hop version?

2.8-GA

### Java version?

11

### Operating system

Windows

### What happened?

I expected when there is not perfect alignment to what field should be used to receive an error and not crash the application.  

You can reproduce this error by configuring your pipeline to use a "Changing Sequence" transform and designate an existing column to change the output sequence based upon changes to that field.  

Then change that field to something that does not exist in the stream and click run.  Hop will hang indefinitely.  It just should throw an error, stop the transform and let the user continue working.

ms.fieldschangesequence.FieldsChangeSequenceField@ab5f359] in the input stream!
org.apache.hop.core.exception.HopException:
Can not find field [org.apache.hop.pipeline.transforms.fieldschangesequence.FieldsChangeSequenceField@ab5f359] in the input stream!

        at org.apache.hop.pipeline.transforms.fieldschangesequence.FieldsChangeSequence.processRow(FieldsChangeSequence.java:75)
        at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
        at java.base/java.lang.Thread.run(Thread.java:840)
2024/04/16 11:54:02 - Add value fields changing sequence.0 - ERROR: Unexpected error
2024/04/16 11:54:02 - Add value fields changing sequence.0 - ERROR: org.apache.hop.core.exception.HopException:
2024/04/16 11:54:02 - Add value fields changing sequence.0 - Can not find field [org.apache.hop.pipeline.transforms.fieldschangesequence.FieldsChangeSequenceField@ab5f359] in the input stream!
2024/04/16 11:54:02 - Add value fields changing sequence.0 -
2024/04/16 11:54:02 - Add value fields changing sequence.0 -    at org.apache.hop.pipeline.transforms.fieldschangesequence.FieldsChangeSequence.processRow(FieldsChangeSequence.java:75)
2024/04/16 11:54:02 - Add value fields changing sequence.0 -    at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by gertwieland** [comment]
I wholeheartedly support this. 
Probably related to [ticket 3655 ](https://github.com/apache/hop/issues/3655)

**Comment by gertwieland** [comment]
<img width="796" alt="image" src="https://github.com/apache/hop/assets/51762835/06dc7a11-84eb-4ddb-a815-ba23cc1291ec">

**Comment by bamaer** [comment]
tried to reproduce this on Linux and Mac, but Hop Gui keeps working correctly after the error. I'll see if I can test this on Windows one of these days too.

**Comment by nadment** [comment]
Works on Windows too, but the error message should be improved with the field name:

**AS IS:** Can not find field [org.apache.hop.pipeline.transforms.fieldschangesequence.FieldsChangeSequenceField@337aaa] in the input stream!

**TO BE:** Can not find field 'fieldname' in the input stream!

**Comment by shlxue** [comment]
> I wholeheartedly support this. 
> Probably related to [ticket 3655 ](https://github.com/apache/hop/issues/3655)

Fixed #3655
