### ISSUE TITLE
[Feature Request]: Connection to Remote Repository

### ISSUE THREAD

**Issue by st-lee1** [apache/hop#3817]
### What would you like to happen?

Kettle/PDI provides a feature called 'Pentaho Repository' that supports a connection to a remote server (such as EC2) from a local GUI tool. It was very useful to me when modifying pipelines, workflows, and adjusting batch schedules on my local computer

I expected the 'Hop Server' to provide benefits like that, but the options were too simplified.
How can I access the remote server directory and make modifications at local computer?
If such features are not available, I really hope they will be added.
![image](https://github.com/apache/hop/assets/166348600/29f0e8d3-39f1-42cb-8e4a-a97ed71a7c73)
![image](https://github.com/apache/hop/assets/166348600/fbba4f4c-4a41-4f0b-a3fb-c056b4b00491)
![image](https://github.com/apache/hop/assets/166348600/8f2b1a9f-372d-4130-9bc7-45b631000c62)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui, Component: Hop Server, Component: Hop Web

**Comment by bamaer** [comment]
the remote repository is/was only available in the Pentaho Enterprise Edition afaik. 
as an alternative, you use a git repository and check in/out on your local machine and a remote server.

**Comment by st-lee1** [comment]
I have been able to use the remote repository smoothly in the Pentaho Community Edition version, and I am still using it now. Ultimately, is the Git repository the only alternative in Apache Hop?

**Comment by pauloricardoferreira** [comment]
> taho Com

yes
