### ISSUE TITLE
[Feature Request]: Synchronize After Merge  - specify connection through variables

### ISSUE THREAD

**Issue by sramazzina** [apache/hop#3839]
### What would you like to happen?

Give the possibility to specify connection through variables

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by nadment** [comment]
Same as #3797

**Comment by sramazzina** [comment]
@nadment you are right. I close this as duplicate

**Comment by sramazzina** [comment]
Duplicate  of https://github.com/apache/hop/issues/3797
