### ISSUE TITLE
[Bug]: Incorrect help url from Workflow Run dialog.

### ISSUE THREAD

**Issue by Oen1997** [apache/hop#3854]
### Apache Hop version?

2.8

### Java version?

11

### Operating system

Windows

### What happened?

![image](https://github.com/apache/hop/assets/210065/3887fe85-4c0f-438e-bb9a-95382cc27cac)

Incorrect link used:
https://hop.apache.org/manual/latest/manual/latest/workflow/run-debug-workflow.html
Must be:
https://hop.apache.org/manual/latest/workflow/run-debug-workflow.html

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue
