### ISSUE TITLE
[Feature Request]: Error log transform information

### ISSUE THREAD

**Issue by Akira74** [apache/hop#3865]
### What would you like to happen?

Hop Version 2.8.0
In the error log, I see that there was an Error, but I do not see, in what transform the error was (Name). When there was an error in a Sub Pipeline, I also do not the the name of the pipeline. Nearly impossible to find the issue within big workflows without that information. 
Is this a general setting within Hop that has to be set or could this be handled within every transformation. 
Also the row number would be quite interesting when the data type error happened.

![2024-04-25 14_16_30-Hop](https://github.com/apache/hop/assets/22960994/d42451cc-96bc-49f8-af93-d88bbc2754b0)

### Issue Priority

Priority: 2

### Issue Component

Component: Pipelines

**Comment by hansva** [comment]
The second error you see is not coming from a transform.
This error is thrown by the execution information plugin which can't handle Geometry datatype.
These errors are non blocking, you can get rid of them by removing the execution information location from your pipeline run configuration.
