### ISSUE TITLE
[Bug]: An error occurs when using "Split JSON after n rows" in json output

### ISSUE THREAD

**Issue by bykhovets** [apache/hop#3871]
### Apache Hop version?

2.7

### Java version?

20.0.2

### Operating system

Windows

### What happened?

An error occurs when using "Split JSON after n rows" in json output:

024/04/26 14:13:14 - JSON Output.0 - ERROR: Unexpected error
2024/04/26 14:13:14 - JSON Output.0 - ERROR: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
2024/04/26 14:13:14 - JSON Output.0 - 	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
2024/04/26 14:13:14 - JSON Output.0 - 	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
2024/04/26 14:13:14 - JSON Output.0 - 	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
2024/04/26 14:13:14 - JSON Output.0 - 	at java.base/java.util.Objects.checkIndex(Objects.java:385)
2024/04/26 14:13:14 - JSON Output.0 - 	at java.base/java.util.ArrayList.get(ArrayList.java:427)
2024/04/26 14:13:14 - JSON Output.0 - 	at org.apache.hop.pipeline.transforms.jsonoutputenhanced.JsonOutput.serializeJson(JsonOutput.java:423)
2024/04/26 14:13:14 - JSON Output.0 - 	at org.apache.hop.pipeline.transforms.jsonoutputenhanced.JsonOutput.manageRowItems(JsonOutput.java:281)
2024/04/26 14:13:14 - JSON Output.0 - 	at org.apache.hop.pipeline.transforms.jsonoutputenhanced.JsonOutput.processRow(JsonOutput.java:122)
2024/04/26 14:13:14 - JSON Output.0 - 	at org.apache.hop.pipeline.transform.RunThread.run(RunThread.java:55)
2024/04/26 14:13:14 - JSON Output.0 - 	at java.base/java.lang.Thread.run(Thread.java:1623)

### Issue Priority

Priority: 1

### Issue Component

Component: Pipelines, Component: Other

**Comment by bamaer** [comment]
.take-issue
