### ISSUE TITLE
[Bug]: "Unique rows (HashSet)" has a bug and drops records

### ISSUE THREAD

**Issue by gertwieland** [apache/hop#3908]
### Apache Hop version?

2.8

### Java version?

openjdk version "11.0.21" 2023-10-17

### Operating system

Windows

### What happened?

"Unique rows (HashSet)" seems to drop records even if they only appear once.
Steps to reproduce the error:

Generate 60k records, then add a sequence and one column with random fake data.

Then calculate a SHA256 checksum over it. Since it includes the sequence number from 1 - 60k, those checksums must be all unique.

But still, the "Unique rows (HashSet)" seems to consider one row a duplicate, and only returns 59,999 records.

Test pipeline attached
[Unique_Hash_Faulty.zip](https://github.com/apache/hop/files/15210985/Unique_Hash_Faulty.zip)

<img width="1110" alt="image" src="https://github.com/apache/hop/assets/51762835/91d8528c-449d-476f-8a8e-11b4a61f7e62">

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by DAJGIT** [comment]
I could reproduce this case after several runs.
Trying to catch the duplicate record found this option: Compare using stored row values
![image](https://github.com/apache/hop/assets/25872532/e8a5ff07-b6ac-4579-a3c7-243de4d20f7a)
It seems this solves this case.

**Comment by DAJGIT** [comment]
Keep diving looking for a repoduction path and here it is:
![image](https://github.com/apache/hop/assets/25872532/83855e3e-60cc-4adc-ae41-a693aa78e760)

[Unique_Hash_Faulty_Sample.zip](https://github.com/apache/hop/files/15222987/Unique_Hash_Faulty_Sample.zip)

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
I have taken a look, and indeed it is what it is. the way we do it is use `Arrays.deepHashCode` to calculate the hash and it seems this one will likely start giving collisions after only 75K rows. I'll turn on the "Compare using stored value" as default option.

**Comment by hansva** [comment]
I made that option the default and added a warning to the docs on possible collisions
