### ISSUE TITLE
[Bug]: Formula Transfrom fails with NoSuchMethodError

### ISSUE THREAD

**Issue by MalkmusT** [apache/hop#3914]
### Apache Hop version?

2.8

### Java version?

openjdk version "17.0.9" 2023-10-17 LTS

### Operating system

Windows

### What happened?

We recently tested the new release version 2.8 and found that the "Formula" transformation throws a "NoSuchMethodError".
when linking two string variables.

A small test example is shown in the following image.

![grafik](https://github.com/apache/hop/assets/12440584/83c246aa-6cb3-4f2e-a47b-e35815a16232)

On request i can provide the corresponding pipeline file.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by bamaer** [comment]
can't reproduce (with Java 11), please attach your own reproduction path.

[3914-formula-concatenate.hpl.txt](https://github.com/apache/hop/files/15257675/3914-formula-concatenate.hpl.txt)

**Comment by MalkmusT** [comment]
thanks @bamaer for the reply. 

Your example fails on my system with the same Error massage.
Looks like we have a problem within our custom libs.
