### ISSUE TITLE
[Bug]: pipeline not marked as modified after onlu change in field mapping in Table Output

### ISSUE THREAD

**Issue by lgit-it** [apache/hop#3922]
### Apache Hop version?

2.8

### Java version?

jdk-11.0.22

### Operating system

Windows

### What happened?

To reproduce the problem:
- open a pipeline, 
- change some mapping in Table Output hop and press ok
you will see that the pipe is not marked "to save" ( floppy still gray)  
The pipeline is ok, but is not autosaved / it's impossible to save, so you have to make some other change to be able to save the modified version.

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
cannot reproduce, I tried changing the fields, the connection, schema/table name they all triggered that the pipeline was changed
