### ISSUE TITLE
[Bug]: Documentation error - Creating system variables via Hop GUI

### ISSUE THREAD

**Issue by dave-csc** [apache/hop#3943]
### Apache Hop version?

2.8.0

### Java version?

openjdk version "21.0.2" 2024-01-16

### Operating system

Linux

### What happened?

The following documentation page explains how to create system variables in Hop GUI:
https://hop.apache.org/manual/latest/variables.html#_system_properties

However, there is no menu toolbar on the Hop GUI window, neither there is a similar command on the Hop icon menu

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation, Component: Hop Gui

**Comment by bamaer** [comment]
confirmed, that screenshot is outdated. 
FYI, the menu bar can be re-enabled from the configuration perspective -> Look & Feel -> uncheck 'Hide the menu bar', and the system variables have moved to the last tab in the configuration perspective.

**Comment by dave-csc** [comment]
Hello, I noticed that documentation has been updated for version 2.9 :)

There is still an error regarding the position in the hop-config.json file where the new variables are saved: in the file there is no section `"systemProperties"`, but new variables are added in the `"variables"` section like this:

```
{
  "variables" : [ {
  ...
  }, {
    "name" : "MY_SYSTEM_PROPERTY",
    "value" : "SomeValue",
    "description" : "My new system property/variable"
  } ], 
  ...
}

```
