### ISSUE TITLE
[Bug]: The pipelines are duplicated

### ISSUE THREAD

**Issue by maghibus** [apache/hop#3954]
### Apache Hop version?

2.8.0

### Java version?

11

### Operating system

Docker

### What happened?

I'm deploying a pipeline to a remote server, however the pipeline is duplicated n times and doesn't run

![image](https://github.com/apache/hop/assets/21333465/8de44d4c-1a6a-4537-8365-3f3b04288bff)
![image](https://github.com/apache/hop/assets/21333465/7afe46aa-f7de-4ea7-a568-16f592daa84f)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Server

**Comment by Matt87s** [comment]
The problem concerned an incorrect configuration of the "Run Configuration" parameter which instead of being set as local was set as remote, creating a loop
![image](https://github.com/apache/hop/assets/57292358/4b107006-0ab9-4770-adb2-a578e11cce68)

**Comment by maghibus** [comment]
thanks @Matt87s for the reply.
