### ISSUE TITLE
[Task]: Issue with Maven Builds: Assembly Creation Error and Rat Check Failure

### ISSUE THREAD

**Issue by dsanderbi** [apache/hop#3986]
### What needs to happen?

OS: Windows 11
Maven: 3.6.3
Java: OpenJDK 17.0.11

**It should be checked why Maven Builds fail on Windows OS**.

The following behavior occurs on Windows 11:

Executing
`mvn clean install -pl :hop-assemblies-samples -am`
results in _"Failed to create assembly: Error creating assembly archive samples: archive cannot be empty"._

Executing
`mvn clean install -pl :hop-transform-textfile -am apache-rat:check`
results in a failure during the Rat check.
This is triggered by an **empty** file generated during the execution of **hop-transform-textfile**.
The file gets stored here : _\hop\plugins\transforms\textfile\textFileOutput.txt_

NOTE: also the execution of "hop-plugins-misc-git" will fail on Windows, but this is a known issue, as mentioned by @nadment

### Issue Priority

Priority: 2

### Issue Component

Component: Other

**Comment by nadment** [comment]
I create a separate issue for tests failures in hop-plugins-misc-git  #3994
