### ISSUE TITLE
[Task]: Weblate is not referenced anywhere on the site

### ISSUE THREAD

**Issue by nadment** [apache/hop#3998]
### What needs to happen?

Weblate is not referenced anywhere on the site, so we should write a short paragraph explaining why. 

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by hansva** [comment]
this page should be changed to instruct on how to use weblate
https://hop.apache.org/community/contribution-guides/translation-contribution-guide/

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
duplicate of #2217
