### ISSUE TITLE
[Bug]: Issue with hop-assemblies-samples

### ISSUE THREAD

**Issue by dsanderbi** [apache/hop#4001]
### Apache Hop version?

2.10.0-SNAPSHOT

### Java version?

openjdk version 17.0.11

### Operating system

Windows 

See also, #3986

### What happened?

When you execute 
`mvn clean install -pl :hop-assemblies-samples -am`
you get the following error:

_[INFO] --- maven-assembly-plugin:3.1.0:single (assembly_package) @ hop-plugins ---
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Hop Orchestration Platform 2.10.0-SNAPSHOT:
[INFO]
[INFO] Hop Orchestration Platform ......................... SUCCESS [  3.340 s]
[INFO] Hop Plugins ........................................ FAILURE [  0.340 s]
[INFO] Hop Assemblies ..................................... SKIPPED
[INFO] Hop Assemblies Samples ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  4.800 s
[INFO] Finished at: 2024-05-31T15:55:49Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-assembly-plugin:3.1.0:single (assembly_package) on project hop-plugins: Failed to create assembly: Error creating assembly archive samples: archive cannot be empty -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :hop-plugins_

### Issue Priority

Priority: 2

### Issue Component

Component: Other

**Comment by sramazzina** [comment]
@dsanderbi is this issue related to Hop the samples project?

**Comment by dsanderbi** [comment]
> @dsanderbi is this issue related to the Hop samples project?

I don't understand the questrion. Which Hop Samples Project do you mean?
This ticket is related to the Maven build problem, see #3986

**Comment by nadment** [comment]
Can you try building the plugins first: **hop\plugins\pom.xml** 

This will prepare and group the samples for each plugin like this:
![image](https://github.com/apache/hop/assets/39568358/598dfa1c-716b-4383-8a08-f1bad4479dac)

**Comment by dsanderbi** [comment]
That was the solution, thanks.
