### ISSUE TITLE
[Task]:  Update Documentation contribution guide

### ISSUE THREAD

**Issue by dsanderbi** [apache/hop#4003]
### What needs to happen?

Update documentation contribution page: https://hop.apache.org/community/contribution-guides/documentation-contribution-guide/#doc-types

1. The video is blocked
2. In the section "Work on the documentation directly from the Hop website" add, where it mentions contributing through the edit button, that the snapshot version from the dropdown menu should be used.
4. In the section "Submit your Contribution" change base fork from master to main.

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by bamaer** [comment]
.take-issue

https://github.com/apache/hop-website/pull/224/commits/eda698ff7ea05311ca97d2d03f3beb4e22957d43
