### ISSUE TITLE
[Feature Request]: Move files in File Explorer

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#4018]
### What would you like to happen?

It would be awesome to be able to move files around in Hop's File Explorer.

In addition to Move, there could also be some form of tracking where if the file was moved, the hop could change the path where the Pipeline/Worflow is being referenced.

![image](https://github.com/apache/hop/assets/70301866/11e2b87c-1b1c-418f-8a6a-49a8a80f735a)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
Similar to #2437

**Comment by hansva** [comment]
moving files has been added, automatically updating references is a bit harder to do as we don't really know yet where paths are being used. so maybe that can be split to a different feature request
