### ISSUE TITLE
[Bug]: Filter Rows - BigNumber

### ISSUE THREAD

**Issue by pauloricardoferreira** [apache/hop#4020]
### Apache Hop version?

2.9

### Java version?

11

### Operating system

Windows

### What happened?

Hello, sorry for my English, I'm using Google Translate.

I encountered the error below when trying to filter with the BigNumber format in the "Filter rows" Transform

After the error occurs, it is only possible to change the parameter:
Deleting the step and reconfiguring or choosing the Filter by Field option and then returning to value.

![image](https://github.com/apache/hop/assets/70301866/6d4ee60f-a78f-48f9-b77b-60d813c1040e)

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
.take-issue
