### ISSUE TITLE
[Feature Request]: Explore Database > need to scale in size on Windows to make them usable.

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#4061]
### What would you like to happen?

Everyone in Windows runs with 4k monitors these days, even on laptops with a single screen.  Some of the widgets need to scale to even be usable, like on the Database Explorer.
![image](https://github.com/apache/hop/assets/1233654/b32da2b9-a1e1-4ff2-b893-cdf9af5894e3)
It would also be great if we could increase the size of the icons on the side menus.
![image](https://github.com/apache/hop/assets/1233654/63ec5141-14a1-4a41-9bc4-5bd331a93ad0)

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
Did you change the global zoom level like I suggested in chat?

**Comment by hansva** [comment]
No response from author, if the problem still persists after the suggestions feel free to reopen
