### ISSUE TITLE
[Bug]: While Saving a New Pipeline, HOP GUI Appends the Previously Opened Pipeline Names

### ISSUE THREAD

**Issue by kirana-ks** [apache/hop#4073]
### Apache Hop version?

2.9.0

### Java version?

11

### Operating system

Windows

### What happened?

**Installation details**:-
Download and extract the apache-hop-client-2.9.0.zip file from the official page: https://hop.apache.org/download/
[apache-hop-client-2.9.0.zip](https://www.apache.org/dyn/closer.cgi?filename=hop/2.9.0/apache-hop-client-2.9.0.zip&action=download)

**Java Version:-** 11

**Reproduction Steps:-**

1. Open HOP GUI using hop-gui.bat.
2. Open any existing Pipeline.
3. Now try to Create a New Pipeline and click the Save button.
4. While saving a New Pipeline, the Hop GUI tool considers the names of all the opened Pipeline names. 

**Example:** 
- Test1.hpl file is an existing file that is opened in the HOP GUI tool.
- Create a New pipeline and Save it as Test2.hpl. During this process, the HOP GUI will append the previously opened file names along with the new name.

**Refer to the attached screenshots:** 
![Apache HOP - Filename Issue 2](https://github.com/apache/hop/assets/31061958/46ed5cb5-67cb-48dc-af62-6dbf4a76e679)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
Cannot reproduce on MacOs, @nadment could you check?

**Comment by nadment** [comment]
Yes, I can confirm that this bug exists in Windows. I'll try to catch it.
