### ISSUE TITLE
[Bug]: "simple mapping(sub-pipeline)" transform output  fieldname is not updated

### ISSUE THREAD

**Issue by petertsneg** [apache/hop#4076]
### Apache Hop version?

2.9

### Java version?

11

### Operating system

Windows

### What happened?

![IssueB01](https://github.com/apache/hop/assets/82127495/fd1870a4-587c-4e0a-9658-622a4b8915b2)
![IssueB02](https://github.com/apache/hop/assets/82127495/b25e22ca-2750-40ce-b3a4-3af4f0b173b1)

mapping.hpl & main.hp file
[simpleMapping.zip](https://github.com/user-attachments/files/15907194/simpleMapping.zip)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui, Component: Transforms

**Comment by hansva** [comment]
should be fixed with #3529 feel free to re-test using a 2.10 build.
you can get it from [here](https://repository.apache.org/content/repositories/snapshots/org/apache/hop/hop-client/2.10.0-SNAPSHOT/) (does require Java 17)

**Comment by petertsneg** [comment]
The test results are the same

![IssueD01](https://github.com/apache/hop/assets/82127495/702194ca-1a2a-46c4-acc2-e5b2588ee9a9)

**Comment by petertsneg** [comment]
It is suspected that itemId2 is replaced by itemId

![IssueE01](https://github.com/apache/hop/assets/82127495/fa325221-2994-4f33-bac2-280d2cb1205e)
![IssueE02](https://github.com/apache/hop/assets/82127495/b673a897-7353-4b45-ada8-c9bbe1ed0811)
