### ISSUE TITLE
[Bug]: "simple mapping(sub-pipeline)" transform [Input] Mapping Error  and [output] Get Fields Error

### ISSUE THREAD

**Issue by petertsneg** [apache/hop#4077]
### Apache Hop version?

2.9

### Java version?

11

### Operating system

Windows

### What happened?

Reproduction Steps:
Open the Simple Mapping editing window for the second time
Click Mapping on Input tab
![IssueC01](https://github.com/apache/hop/assets/82127495/bc6b7204-f532-4c94-be86-aecc7d9d7632)

Click Mapping on Output tab
![IssueC02](https://github.com/apache/hop/assets/82127495/25e5a975-83aa-4520-832a-5b9d7a0626eb)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui, Component: Transforms

**Comment by hansva** [comment]
should be fixed with #3529 feel free to re-test using a 2.10 build.
you can get it from [here](https://repository.apache.org/content/repositories/snapshots/org/apache/hop/hop-client/2.10.0-SNAPSHOT/) (does require Java 17)

**Comment by petertsneg** [comment]
The test confirmed that there is no problem, thank you
