### ISSUE TITLE
[Bug]: HOP GUI - Repeatedly Prompting to enter GitHub Credentials

### ISSUE THREAD

**Issue by kirana-ks** [apache/hop#4078]
### Apache Hop version?

2.9.0

### Java version?

11

### Operating system

Windows

### What happened?

**Installation details:-**
Download and extract the apache-hop-client-2.9.0.zip file from the official page: https://hop.apache.org/download/
[apache-hop-client-2.9.0.zip](https://www.apache.org/dyn/closer.cgi?filename=hop/2.9.0/apache-hop-client-2.9.0.zip&action=download) and Run the HOP-GUI.bat file to start the HOP application.

**Java Version:-** 11

**Reproduction Steps:-**

1. Open HOP GUI using hop-gui.bat.
2. Open any existing Pipeline.
3. Goto File Explorer (Ctrl + Shift + E) and click on Git Push. 
4. HOP GUI will prompt you to enter the GitHub credentials. Enter the credentials and Click Ok button. 
5. HOP GUI continuously prompts to enter the Git credentials multiple times and doesn't display an error message or allow to proceed to the next steps (Note I'm entering a valid credentials).

![GiTHub Issue 1](https://github.com/apache/hop/assets/31061958/db3d52e8-ee27-4c57-930f-976ba8f58ffb)

![GiTHub Issue 2](https://github.com/apache/hop/assets/31061958/d3bc1ef5-c165-40f7-bff4-7564daf815fb)

**Note:**

1. GitHub Plugin is already installed in the Path: apache-hop-client-2.9.0\hop\plugins\misc\git
2. .git/config is also created in the Project directory. ( Created using "git clone" on Windows CMD)
3. FYI, I can push and pull the code files via Git Client using Windows CMD. However, via HOP GUI unable to do it since the application Is repeatedly asking me to enter the Git credentials without an error message.

**I have referred to the following articles regarding this configuration:** 
https://hop.apache.org/manual/latest/hop-gui/hop-gui-git.html
https://hop.apache.org/manual/latest/hop-gui/perspective-file-explorer.html

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
We will improve the documentation but this is probably caused by using your regular password and not a personal access token. There are other tickets to improve the UI and this will be taken into account.
