### ISSUE TITLE
[Bug]: Action AS400Command has a bad dependency to the JT400 library

### ISSUE THREAD

**Issue by nadment** [apache/hop#4085]
### Apache Hop version?

2.9.0

### Java version?

Java 11

### Operating system

Windows

### What happened?

The JT400 library has been moved to the lib/jdbc folder, but it seems that the actions don't know how to load libraries from this folder.

The file dependencies.xml is linked to the old lib folder:

<dependencies>
    <folder>../../databases/as400/lib</folder>
</dependencies>

One solution would be to create a tech/as400 plugin that brings together the database and the action with the library within it.

Workaround : put the JT400 library in the "\plugins\actions\as400command\lib" folder

### Issue Priority

Priority: 3

### Issue Component

Component: Actions

**Comment by hansva** [comment]
you can add the " isIncludeJdbcDrivers = true" to the transform or action annotation and it will add the folder to the classpath of that plugin.

**Comment by hansva** [comment]
or a classloadergroup should do the trick too.
https://github.com/apache/hop/blob/5bce820bdb2277f3082cc41b03533476a13dfe80/plugins/transforms/pgbulkloader/src/main/java/org/apache/hop/pipeline/transforms/pgbulkloader/PGBulkLoaderMeta.java#L44

**Comment by nadment** [comment]
Not resolved

**Comment by nadment** [comment]
Finally it's ok
