### ISSUE TITLE
[Bug]: Multiway merge join, delete button does not work properly

### ISSUE THREAD

**Issue by pptr3** [apache/hop#4091]
### Apache Hop version?

2.9.0

### Java version?

openjdk 11.0.23 2024-04-16 OpenJDK Runtime Environment (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1) OpenJDK 64-Bit Server VM (build 11.0.23+9-post-Ubuntu-1ubuntu122.04.1, mixed mode, sharing)

### Operating system

Linux

### What happened?

When using the Transform component "Multiway merge join", the selection of the keys in the drop-down "Join Keys" is buggy. In particular, when I select a field to be removed, that field is kept and not removed while the others are removed instead.

Steps to reproduce:
- I have two Table Input (Table input 1 and Table input 2) and I want to perform the INNER join between these two tables on the field "codice fiscale":
![Screenshot from 2024-06-26 20-17-55](https://github.com/apache/hop/assets/30435694/92801c3a-45be-4ace-9068-8c70dfeed378)

- Connect with a Hop Table input 1 and Table input 2 to the Multiway merge join:
![Screenshot from 2024-06-26 20-21-37](https://github.com/apache/hop/assets/30435694/5e89b347-5abb-42a7-bc89-a52fe141ae4a)

- Open the Multiway merge join and select "Table input 1" in the drop-down "Input transform 1" and select "Table input 2" in the drop-down "Input transform 2" with "Join Type" as "INNER":
![Screenshot from 2024-06-26 20-33-21](https://github.com/apache/hop/assets/30435694/484dc0dc-7f6d-4a6f-8203-50eece927680)

- Now click on both "Select Keys" buttons and then click on "Get key fields" and then click on "OK":
![Screenshot from 2024-06-26 20-24-55](https://github.com/apache/hop/assets/30435694/c8bd2e56-7eda-4fa9-bb37-713e4a4b7925)
![Screenshot from 2024-06-26 20-25-38](https://github.com/apache/hop/assets/30435694/cb2ec0c2-23a6-4c54-98ef-af5605dca293)
- After that, we are in this situation where in "Join Keys" we have all the columns of  Table input 1 and Table input 2: 
![Screenshot from 2024-06-26 20-26-54](https://github.com/apache/hop/assets/30435694/425b6907-b1af-47c6-9c33-af7e0f714cc6)
- However, I want to perform the join on only the field "codice_fiscale", therefore I click on "Select Keys" again to select just that field:
![Screenshot from 2024-06-26 20-27-45](https://github.com/apache/hop/assets/30435694/4cf79b08-2b56-4765-8eab-023d44dbcab2)

- Now the abnormal behaviour happens: since I want to remove all the fields but "codice_fiscale", I select another field (the field "nome" in this case) and I press the "delete" button I am indicating with the pointer:
![Screenshot from 2024-06-26 20-29-41](https://github.com/apache/hop/assets/30435694/967cf2fc-0f62-43e8-b541-1d79d6bc4339)
- When I click that button, this happens:
![Screenshot from 2024-06-26 20-30-22](https://github.com/apache/hop/assets/30435694/3132a9a1-21a7-44e7-a423-14ac468f1f07)
- Namely, the field "cognome" which was under the field "nome" is getting deleted instead. I am expecting the field "nome" to be deleted.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by bamaer** [comment]
@pptr3 I could reproduce this on Arch Linux + KDE Plasma 6, but not on MacOS. 
the issue only occurs when you have the field name selected, not when the entire row is selected (click on the row number instead of the field). 
I understand this is inconvenient, but selecting the entire row is an easy workaround. I'm afraid this is a bug in SWT (the UI library we use in Hop Gui) on Linux, so not something we can control.

**Comment by pptr3** [comment]
@bamaer yeah, you are right.

**Comment by bamaer** [comment]
ok, thanks for the confirmation. closing this issue.
