### ISSUE TITLE
[Feature Request]: Log table options in Workflow Properties Tab

### ISSUE THREAD

**Issue by kirana-ks** [apache/hop#4141]
### What would you like to happen?

For monitoring and maintenance, It would be nice to have the ability to capture the Workflow execution details into a log table from Apache HOP. 

An equivalent of  "_Job Log table_", "_Step Entry Log Table_" and "_Logging channel Log Table_" setting from the PDI Job Properties tab. 
![Job Properties](https://github.com/user-attachments/assets/7122d936-8e90-450a-89c6-3aabcb3e1572)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
This has been implemented using the pipeline and workflow log. This will contain all the information which you can then send to a database table.
