### ISSUE TITLE
[Bug]: Error hop changed in normal hop while is disabled

### ISSUE THREAD

**Issue by liosc** [apache/hop#4157]
### Apache Hop version?

2.9.0

### Java version?

Eclipse Adoptium\jdk-11.0.22.7-hotspot

### Operating system

Windows

### What happened?

Entering transform error setup while the error hop is disabled, changed the error hop in normal hop.
Steps to reproduce the error:
1. Disable the error hop
2. Enter transform error setup
3. Press OK
Even if you enable back the hop, it will remain a normal hop (no more error hop as it was). That's dangerous because if you don't notice the misbehavior, the becoming of the hop to a normal one instead of an error one, could lead to fatal or sneaky errors.
[Error_hop_setup_while_disabled_GUI_problem.zip](https://github.com/user-attachments/files/16360255/Error_hop_setup_while_disabled_GUI_problem.zip)

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
Bug confirmed, we should also change the design of error handling disabled.

BAD
![image](https://github.com/user-attachments/assets/7fb53332-ecfb-4cd6-b9ea-d4a3e687c209)

GOOD
![image](https://github.com/user-attachments/assets/f8cd25d1-94df-4f5b-bfc3-ba50d8e64025)
