### ISSUE TITLE
[Feature Request]: Project and environment on Asynchronous Web Service of Hop Server

### ISSUE THREAD

**Issue by transformandodados** [apache/hop#4166]
### What would you like to happen?

As a developer and deployer of Apache Hop, I need to define the "project" and "environment" to run Workflow Asynchronous Web Service on the Hop Server.

### Issue Priority

Priority: 2

### Issue Component

Component: API, Component: Hop Gui, Component: Hop Server

**Comment by hansva** [comment]
You can start hop server using the -e (environment) or -j (project) flags
