### ISSUE TITLE
[Bug]: Execution information location 'Runs your pipelines locally with the standard local Hop pipeline engine' could not be found in the metadata

### ISSUE THREAD

**Issue by ManuSodre** [apache/hop#4215]
### Apache Hop version?

2.8.0 (2024-02-28 03.31.08)

### Java version?

22.0.1

### Operating system

Windows

### What happened?

When I run a pipeline, it is giving me this error described in the log below. How can I resolve it?

2024/08/12 16:32:38 - Hop - Projects enabled
2024/08/12 16:32:38 - Hop - Enabling project : 'MotorPJE'
2024/08/12 18:15:11 - Hop - Starting workflow
2024/08/12 18:15:11 - carga_completa - Start of workflow execution
2024/08/12 18:15:11 - carga_completa - Starting action [ddl.hpl]
2024/08/12 18:15:11 - ddl.hpl - Using run configuration [local]
2024/08/12 18:15:11 - ddl - Executing this pipeline using the Local Pipeline Engine with run configuration 'local'
2024/08/12 18:15:11 - ddl - Execution started for pipeline [ddl]
2024/08/12 18:15:11 - ddl - **ERROR: Execution information location 'Runs your pipelines locally with the standard local Hop pipeline engine' could not be found in the metadata**
2024/08/12 18:15:12 - ddl.0 - Finished reading query, closing connection.
2024/08/12 18:15:12 - ddl.0 - Finished processing (I=0, O=0, R=0, W=1, U=0, E=0)
2024/08/12 18:15:12 - ddl - Pipeline duration : 0.071 seconds [  0.071" ]
2024/08/12 18:15:12 - ddl - Execution finished on a local pipeline engine with run configuration 'local'

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
In your local pipeline/workflow run configuration clear out the "execution information location" and that Error will go away.
It does not block your workflow or pipeline from running it just gives that message. Not an actual P1 issue.
