### ISSUE TITLE
[Bug]: Oracle connection with TNS alias

### ISSUE THREAD

**Issue by pahervin** [apache/hop#4225]
### Apache Hop version?

2.8

### Java version?

openJdk 11.0.2

### Operating system

Windows

### What happened?

In the Metadata tab, set a Relational Database Connection

1. Set the Connection name
2. Set the Connection type : Oracle
3. Use the default provided Driver
4. Set the Username and the Password
5. Set the connection URL with the ojbdc alias syntax : jdbc:oracle:thin:@my_alias
6. In Options tab, set JDBC option : oracle.net.tns_admin=my_path_to_tnsnames.ora_directory
7. Set leave empty the other fields
8. Check the TNS_ADMIN environnement variable is properly set
9. Click on the Test button

The connection attempt produce an exception.
This connection URL is used successfully with other java tools (sqldevelopper, Talend).

1. Change the Connection URL :  jdbc:oracle:thin:@my_alias?TNS_ADMIN=my_path_to_tnsnames.ora_directory
2.  Click again on the Test button

The connection attempt produce an exception again.

1. Change the Connection URL : jdbc:oracle:thin:@my_hostname:1521:my_SID
2. Click again on the Test button

The connection is established successfully.

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
I connected successfully using this method with a JDBC 19 driver and using the manual url. Apache Hop does not pass options in the url for Oracle.

![image](https://github.com/user-attachments/assets/8cbb1fa5-8a02-4b64-a16a-60d260f06a37)

This connection method is not in the Hop documentation, it should be added.

**Comment by nadment** [comment]
I don't know, maybe it's changed since this implementation was made.

```
  /**
   * Oracle doesn't support options in the URL, we need to put these in a Properties object at
   * connection time...
   */
  @Override
  public boolean isSupportsOptionsInURL() {
    return false;
  }
```

**Comment by hansva** [comment]
Ok, guess this might need some further investigation then. Might have changed from old drivers. Might be that some do have to be in the URL and other don't ...

**Comment by nadment** [comment]
I haven't found any indication that it supports parameters in the url.
https://www.oracle.com/database/technologies/faq-jdbc.html

**Comment by hansva** [comment]
Let's close this one. The original problem has been handled.
We could create a feature request to add extra fields to the dialog to support TNS names. But it will not be part of this bug.
