### ISSUE TITLE
[Bug]: wrong Icons and names when drag and drop tabs in hop-gui

### ISSUE THREAD

**Issue by tlue** [apache/hop#4254]
### Apache Hop version?

2.9.0

### Java version?

jdk-11.0.24+8

### Operating system

Windows

### What happened?

When moving tabs in hop-gui the icons can get wrong as well as text inside the tab
![grafik](https://github.com/user-attachments/assets/85d7afdd-102b-4bee-904a-5f3168e3ee14)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
related to #4211

**Comment by tlue** [comment]
Thanks @hansva - so I think we can close this one as it is a duplicate of #4211 
sorry for the unnecessary filing.

**Comment by nadment** [comment]
duplicate
