### ISSUE TITLE
[Bug]: database field definitions for integer with length = 0 are not created as integer

### ISSUE THREAD

**Issue by rramthun** [apache/hop#4268]
### Apache Hop version?

2.9

### Java version?

17

### Operating system

Linux

### What happened?

There is a logical mistake in the conditions of several implementations of getFieldDefinition() from Interface org.apache.hop.core.database.IDatabase. This leads to Integer fields being generated as a different data type, usually double precision float, when no length is set. Looks like the code section containing this bug has been copy&pasted to many different database implementations inside Hop.

This bug affects components "down the line", compare e.g. #4174 

### Issue Priority

Priority: 2

### Issue Component

Component: Database

**Comment by rramthun** [comment]
.take-issue

**Comment by rramthun** [comment]
@hansva The code handling the creation of integer and floating point fields seems inconsistent between different database systems in Hop.

If I am going to touch these code paths, I would try to make this more consistent.

My suggestion is:
everything with a length > 18 -> Decimal type or, if not available, largest of the Floating types
Integer type, precision = 0 -> one of the Integer types
Integer type, precision > 0 -> one of the Integer types (effectively ignore the precision...)
Floating point type, precision = 0 -> Decimal type or, if not available, one of the Integer types
Floating point type, precision > 0 -> Decimal type or, if not available, one of the Floating types


What do you think?

**Comment by hansva** [comment]
that sounds right.
I have looked at PostgreSqlDatabaseMeta and length 0 is indeed a case that is not handled correctly.
