### ISSUE TITLE
[Bug]: Microsoft Excel Writer action: Auto Size Columns function is not working

### ISSUE THREAD

**Issue by mmoz77** [apache/hop#4272]
### Apache Hop version?

2.9.0

### Java version?

11

### Operating system

Windows

### What happened?

Using Microsoft Excel Writer action, I have noticed that the Auto Size Columns function is not working.
I've checked the option Auto Size Columns in the Content tab (first image), but the excel output doesn't autosize columns (second one). 
The same job in Pentaho produces an autosized excel sheet.
![image](https://github.com/user-attachments/assets/9ff80740-e172-4364-acbd-d08673ddb969)
![image](https://github.com/user-attachments/assets/6f2e980c-8408-4e78-ad76-235a32050006)

### Issue Priority

Priority: 3

### Issue Component

Component: Actions, Component: Transforms

**Comment by nadment** [comment]
We can try to upgrade Apache POI 5.2.4 to 5.3.0 because of the bug below:
https://bz.apache.org/bugzilla/show_bug.cgi?id=68094

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
I cannot reproduce the issue, might be because I am not on Windows.
After reading https://github.com/apache/poi/pull/541 the update should fix the widths in most cases but there are still some edge cases.
