### ISSUE TITLE
[Task]: provide more context about logo vs icon in the tech docs

### ISSUE THREAD

**Issue by bamaer** [apache/hop#4284]
### What needs to happen?

- add context for logo vs icons in the tech manual
- move the default logo colors to the top 

https://hop.apache.org/tech-manual/latest/hop-logo-and-icons.html

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by DeadBoySmile** [comment]
try this
https://gofile.io/d/yMHabA
select the desired compiler in the installer

**Comment by bamaer** [comment]
.take-issue
