### ISSUE TITLE
[Bug]: HOP-WEB - Error in file picker when HOP_CONFIG_FOLDER is changed from default value ${CATALINA_HOME}/webapps/hop/config

### ISSUE THREAD

**Issue by gustavosaquino** [apache/hop#4315]
### Apache Hop version?

2.9

### Java version?

JDK 11

### Operating system

Linux

### What happened?

When the docker image is configured to start with a value for HOP_CONFIG_FOLDER different from the image default, HOP Web starts normally, but when trying to use the file picker of main toolbar or any workflow or transformation plugin, the following error is presented:

`GUI - ERROR: Unable to call method menuFileOpen in class org.apache.hop.ui.hopgui.HopGui : null`
`GUI - ERROR: java.lang.reflect.InvocationTargetException`
`GUI -     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)`
`GUI -     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)`
`GUI -     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)`
`GUI -     at java.base/java.lang.reflect.Method.invoke(Method.java:566)`
`GUI -     at org.apache.hop.ui.core.gui.BaseGuiWidgets.lambda$getListener$1(BaseGuiWidgets.java:213)`
`GUI -     at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:109)`
`GUI -     at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:687)`
`GUI -     at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:594)`
`GUI -     at org.eclipse.swt.widgets.Display.executeNextEvent(Display.java:1216)`
`GUI -     at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1197)`
`GUI -     at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1180)`
`GUI -     at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1172)`
`GUI -     at org.eclipse.rap.rwt.application.AbstractEntryPoint.createUI(AbstractEntryPoint.java:69)`
`GUI -     at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:177)`
`GUI -     at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:290)`
`GUI -     at java.base/java.lang.Thread.run(Thread.java:829)`
`GUI -     at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:107)`
`GUI - Caused by: java.lang.NoSuchMethodError: 'void org.eclipse.swt.widgets.FileDialog.setFilterNames(java.lang.String[])'`
`GUI -     at org.apache.hop.ui.core.dialog.NativeFileDialog.setFilterNames(NativeFileDialog.java:42)`
`GUI -     at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:245)`
`GUI -     at org.apache.hop.ui.core.dialog.BaseDialog.presentFileDialog(BaseDialog.java:122)`
`GUI -     at org.apache.hop.ui.hopgui.delegates.HopGuiFileDelegate.fileOpen(HopGuiFileDelegate.java:80)`
`GUI -     at org.apache.hop.ui.hopgui.HopGui.menuFileOpen(HopGui.java:708)`
`GUI -     ... 17 more`

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Web

**Comment by gustavosaquino** [comment]
I verified that failure happens when the HOP_USE_NATIVE_FILE_DIALOG variable is set to 'Y'. I'm not completely sure about that, but I believe the variable should be ignored in this case.

**Comment by hansva** [comment]
setting that variable in a web browser context does not make sense
