### ISSUE TITLE
[Bug]: File explorer does not resolves indirect PROJECT_HOME variable settings

### ISSUE THREAD

**Issue by Mx-Wolf** [apache/hop#4318]
### Apache Hop version?

2.8.0 (2024-02-28 03.31.08)

### Java version?

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment Microsoft-9388422 (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Microsoft-9388422 (build 21.0.3+9-LTS, mixed mode, sharing)

### Operating system

Windows

### What happened?

if the value for the Project home is set to a known variable, for example ${HOP_CONFIG_FOLDER} it works during execution just fine. but the button [P] in the file explorer window does not work correctly. see pictures for details.
![s-001](https://github.com/user-attachments/assets/b1d57d1a-72ec-4ed0-89a2-0bfff7218876)
![s-002](https://github.com/user-attachments/assets/85c411cb-9c1e-4284-ba4f-e83bf5223ee8)
![s-003](https://github.com/user-attachments/assets/8fefde3a-18c6-4d33-b756-8774c93892f8)
![s-004](https://github.com/user-attachments/assets/2a393251-e392-4ae4-87e4-7217c90636c2)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue
