### ISSUE TITLE
[Task]: Git integration - documentation improvement

### ISSUE THREAD

**Issue by Adalennis** [apache/hop#4327]
### What needs to happen?

This page requires an update to reflect the latest changes in the Apache Hop Git integration feature.
https://hop.apache.org/manual/next/hop-gui/perspective-file-explorer.html

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by Adalennis** [comment]
.take-issue

**Comment by hansva** [comment]
Is this done @Adalennis ?

**Comment by Adalennis** [comment]
Yes, it's done @hansva
