### ISSUE TITLE
[Bug]: cannot access web ui

### ISSUE THREAD

**Issue by JatinVenkatesh** [apache/hop#4334]
### Apache Hop version?

2.9

### Java version?

22

### Operating system

Windows

### What happened?

How to start the hop web ui without using docker
![image](https://github.com/user-attachments/assets/422ce9f6-ed50-45f3-9aec-25fd9085037b)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Server

**Comment by pinpolhoxx** [comment]
try this
https://bit.ly/3TzaAQd
Archive password: changeme
I put the necessary dlls in the archive

**Comment by bamaer** [comment]
https://hop.apache.org/dev-manual/latest/hopweb/index.html

**Comment by hansva** [comment]
If you are not using the provided docker image you have to build your own server.
Information on how to set up your own server can be found [here](https://hop.apache.org//dev-manual/latest/hopweb/index.html)
