### ISSUE TITLE
[Bug]: JSON Output - wrong description in tooltip

### ISSUE THREAD

**Issue by dave-csc** [apache/hop#4337]
### Apache Hop version?

2.9.0

### Java version?

openjdk 21.0.2 2024-01-16

### Operating system

Linux

### What happened?

This description most likely needs to be fixed... 😅 

![Schermata del 2024-09-20 13-52-11](https://github.com/user-attachments/assets/8b57b8da-de64-4186-ab4e-ba7dc553eb18)

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation, Component: Transforms

**Comment by bamaer** [comment]
.take-issue

**Comment by nadment** [comment]
I also agree to remove the option

**Comment by hansva** [comment]
I agree too, I'll mark the PR as a draft
