### ISSUE TITLE
[Bug]: Missing English translations

### ISSUE THREAD

**Issue by shilin-da** [apache/hop#4403]
### Apache Hop version?

2.10.0

### Java version?

17.0.11

### Operating system

Linux

### What happened?

1. Open *Select the item to create* window via *File → New* menu or *New* toolbar button.
2. See `i18n::xxxxx` instead of names and descriptions:
![Screenshot_20241009-122915](https://github.com/user-attachments/assets/0d55e819-0738-484f-baa9-a40c8ac324ac)

### Issue Priority

Priority: 2

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue
