### ISSUE TITLE
[Bug]: field "actionLoggingText" in workflow-logging is always empty

### ISSUE THREAD

**Issue by gmitter-ef** [apache/hop#4419]
### Apache Hop version?

2.10.0

### Java version?

openjdk version "17.0.12" 2024-07-16
OpenJDK Runtime Environment OpenLogic-OpenJDK (build 17.0.12+7-adhoc..jdk17u)
OpenJDK 64-Bit Server VM OpenLogic-OpenJDK (build 17.0.12+7-adhoc..jdk17u, mixed mode, sharing)

### Operating system

Windows 10 Enterprise 22H2

### What happened?

When analyzing the output of "config/projects/samples/reflection/workflow-log-example.hpl", after starting "generate-fake-books.hwf" it occurred that the stream field "actionLoggingText" is empty. The field "actionName", however, contains values.

As it seems to be the analogous field to the pipeline-logging's "transformLoggingText", which also contains values, I believe it to be a bug.

### Issue Priority

Priority: 2

### Issue Component

Component: Pipelines, Component: Samples, Component: Transforms

**Comment by hansva** [comment]
.take-issue
