### ISSUE TITLE
[Task]: Bump up Snowflake JDBC to 3.19, and DuckDB to 1.1.1

### ISSUE THREAD

**Issue by usbrandon** [apache/hop#4430]
### What needs to happen?

Updating the POMs to pick up the latest stable drivers for Snowflake 3.19 and DuckDB 1.1.1.

### Issue Priority

Priority: 3

### Issue Component

Component: Database

**Comment by hansva** [comment]
Our DuckDB integration test is no longer working.
And the same workflow on my local environment also hangs. Also tested with the new 1.1.2 release and same issue.

Reverted the driver back to 1.0.0 for stability
