### ISSUE TITLE
[Bug]: Fields tab in Text File Output transform (UI Bug)

### ISSUE THREAD

**Issue by Adalennis** [apache/hop#4436]
### Apache Hop version?

2.10

### Java version?

java version 21.0.2

### Operating system

macOS

### What happened?

**Steps to reproduce:**
1. Open a pipeline in Apache Hop.
2. Add or edit a Text File Output transform.
3. Navigate to the Fields tab where a large list of fields is displayed (use a large list of fields).
4. Reduce the size of the popup window (shrink the window).
5. Attempt to scroll through the list of fields.
6. Notice that the white background below the buttons disappears, causing the buttons to float over the fields list.

**Expected behavior:**
The buttons at the bottom should remain on a fixed white background and not overlap with the fields list when scrolling.

**Actual behavior:**
The white background under the buttons disappears when scrolling, leaving the buttons floating over the fields list, which reduces the clarity of the interface.

**System information:**
Operating System: macOS
Version: macOS Sonoma version 14.5
Java Version: 21.0.2
Apache Hop Version: 2.10

Screenshot:
<img width="1080" alt="Screenshot 2024-10-16 at 10 34 18" src="https://github.com/user-attachments/assets/d5dcf148-2264-4ab5-b30b-a0c40fa3c6ca">

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by nadment** [comment]
With the Windows operating system it's okay, the problem is specific to MacOS?

![image](https://github.com/user-attachments/assets/89225f0a-1034-4ae4-9630-469687b25cf4)

**Comment by nadment** [comment]
With the Windows operating system it's okay, the problem is specific to MacOS?

![image](https://github.com/user-attachments/assets/7aa48c4b-0ca9-4a4f-9133-388153d02de2)
