### ISSUE TITLE
[Bug]: Crash in some tasks.

### ISSUE THREAD

**Issue by feliperafaelbarbosa** [apache/hop#4451]
### Apache Hop version?

2.9.0 and 2.10.0

### Java version?

openjdk 21.0.5 2024-10-15 LTS

### Operating system

Linux

### What happened?

When I try to open the Apache Hop actions window, the message in the attached image appears, and my Apache Hop does not open the window to "view output." Could you help me solve this issue? Thank you for your attention.

I use SO Debian Bookworm with KDE Plasm and Wayland.

![Screenshot_20241019_134044](https://github.com/user-attachments/assets/409a8a35-3235-42ed-8191-f9cd43cc4f9a)

![Screenshot_20241019_134203](https://github.com/user-attachments/assets/2e632061-1e3a-40d5-9efe-213ceaecee1c)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by feliperafaelbarbosa** [comment]
> Try using java 11 for hop 2.9 or java 17 for hop 2.10

I do this...

**Comment by bamaer** [comment]
can you try on X.org instead of Wayland and see if you still have the same issue?

**Comment by feliperafaelbarbosa** [comment]
> can you try on X.org instead of Wayland and see if you still have the same issue?

Solved, the problem is in incompatibility with Wayland. thank you my friends!!

**Comment by feliperafaelbarbosa** [comment]
> can you try on X.org instead of Wayland and see if you still have the same issue?

Solved, the problem is in incompatibility with Wayland. thank you my friends!!
