### ISSUE TITLE
[Task]: Document how Pipelines using Merge Join can run into deadlock

### ISSUE THREAD

**Issue by Adalennis** [apache/hop#4514]
### What needs to happen?

- Create how-to guide "Avoiding deadlocks with the Merge Join transform".
- Link from the Merge Join transform page.
- Update navigation.

See https://github.com/apache/hop/issues/3740

### Issue Priority

Priority: 3

### Issue Component

Component: Documentation

**Comment by Adalennis** [comment]
.take-issue

**Comment by zf18634362654** [comment]
I also found that if there are two upstream transforms, they use the getFromRowset method. If two identical getFromRowset transforms appear, the pipeline will hang when the data reaches 20000 rows.
![image](https://github.com/user-attachments/assets/b491742a-6a07-4089-b564-15b0f4d9a7d4)

**Comment by hansva** [comment]
This has been covered by #3740.
This is valid with almost all transforms, we work in a micro-batch with buffered rows. if the buffers get filed without a way to push rows down the stream it will deadlock.
Documentation has been added https://hop.apache.org/manual/next/how-to-guides/avoiding-deadlocks-when-using-stream-lookup.html
