### ISSUE TITLE
[Bug]: file explorer perspective hides all folders named metadata, not just the project metadata folder

### ISSUE THREAD

**Issue by bamaer** [apache/hop#4515]
### Apache Hop version?

SNAPSHOT-20241103

### Java version?

openjdk version "17.0.11" 2024-04-16 LTS

### Operating system

macOS

### What happened?

when reading data from a platform's metadata API, I tried to create a project subfolder "metadata" to store the workflows and pipelines that read from this API. 
The file explorer perspective recognizes this "metadata" folder as THE project's metadata folder and (incorrectly) hides it. 
Only the `${HOP_METADATA_FOLDER}` should be hidden. 

### Issue Priority

Priority: 3

### Issue Component

Component: CLI

**Comment by hansva** [comment]
.take-issue
