### ISSUE TITLE
[Bug]: Text file input font size difference + UI zoom 150%

### ISSUE THREAD

**Issue by Adalennis** [apache/hop#4526]
### Apache Hop version?

SNAPSHOT-2024-10-29

### Java version?

java version 21.0.2

### Operating system

macOS

### What happened?

<img width="1307" alt="Screenshot 2024-11-06 at 11 25 33" src="https://github.com/user-attachments/assets/777777f7-14e9-4f49-95a8-2cf969e1b246">

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue
