### ISSUE TITLE
[Bug]: File Explorer - bug in renaming files

### ISSUE THREAD

**Issue by dave-csc** [apache/hop#4541]
### Apache Hop version?

2.10.0

### Java version?

17.0.2

### Operating system

Linux

### What happened?

**Steps to reproduce:**
1. Close a pipeline you have currently open
2. Go to the File Explorer in Hop GUI and rename the pipeline
3. Re-open the renamed pipeline from File Explorer: the pipeline has been correctly renamed on the file system, but you'll get an error saying that a pipeline with the previous filename can't be opened

**Workaround:** you need to close and restart Hop GUI to make the renamed pipeline openable again

_**Marked as P1 for regression:** issue is not present on version 2.9.0_

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
.take-issue
