### ISSUE TITLE
[Bug]: Excel input transform

### ISSUE THREAD

**Issue by mocoxk** [apache/hop#4555]
### Apache Hop version?

2.10.0

### Java version?

openjdk version "17.0.12" 2024-07-16 LTS

### Operating system

Linux

### What happened?

Error with Excel input. I have a pipeline that generates an Excel XLSX file and in another pipeline I use it as input data, but it is not being read correctly. I have the same pipeline in Pentaho and if I use that file as input in my Hop pipeline, it reads it correctly. So I'm not sure if the problem is with the Excel input or the output that is generating the XLSX file.

excel data
![Screenshot 2024-11-11 102126](https://github.com/user-attachments/assets/1042fe69-be37-4c11-a470-cf15ff0efde4)
![Screenshot 2024-11-11 102201](https://github.com/user-attachments/assets/04518803-cecc-447a-9c40-2bdfdbb2ddbb)

excel read from transform correct
![Screenshot 2024-11-11 102011](https://github.com/user-attachments/assets/2d603a80-a612-4223-940e-7ffbbbf13416)

excel read from transform with problem
![Screenshot 2024-11-11 101947](https://github.com/user-attachments/assets/dffccc46-3623-4715-9363-bae32d020ec8)

In the last image, you can see that the data is being duplicated and the values in column A are being displayed in column E, which is not correct. This error only occurs if I use the XLSX file generated with Apache Hop, if I use the one generated with Pentaho, it works correctly.

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
These are not the same values. It's column A +1
Could you provide a sample Excel file that produces this error or sample pipelines to generate the issue?
Note: use a zip file to attach the files to this issue as GitHub blocks a lot of file types.

**Comment by mocoxk** [comment]
I have attached the pipeline that generates the Excel file, and the Excel file generated by Hop and by PDI.

[samples.zip](https://github.com/user-attachments/files/17704512/samples.zip)

**Comment by mocoxk** [comment]
I have tried to replicate the error but now it has been working well, perhaps my MongoDB source data had some special characters that generated those jumps in the Excel input.

**Comment by mocoxk** [comment]
Thank you, for now I will close it and I will be checking if a similar error appears to me again.
