### ISSUE TITLE
[Bug]: Apache Hop GUI 2.10 fails with UnsatisfiedLinkError in Windows 2016 - likely related to SWT issue https://github.com/eclipse-platform/eclipse.platform.swt/issues/1500

### ISSUE THREAD

**Issue by krishnasdfw** [apache/hop#4573]
### Apache Hop version?

2.10

### Java version?

17.0.12

### Operating system

Windows

### What happened?

When starting Apache Hop GUI 2.10 with hop-gui.bat on Windows 2016 server based VDI, it failed with java.lang.UnsatisfiedLinkError.  With many error messages looking for swt-win32.dll and swt.dll before failing with a last message :  "The specified procedure could not be found" on swt-win32-4966r5.dll unpacked to .swt folder under the user home c:\users\<uid>\.swt\lib\wins32\x86_64 folder. That dll is unpacked and exists.

Likely this issue is caused by underlying eclipse SWT platform documented here:
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1500

In Windows 11 this works fine and I also see many additional dll(s) unpacked which I don't see in windows 2016, however in many enterprise desktop environments, they are built on WIndows 10 or WIndows 2016 server still. It will be helpful to get Apache Hop GUI working in those operating systems.

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Gui

**Comment by bamaer** [comment]
this is indeed caused by the issue you referred to. this is an SWT issue that we don't control and can't fix on Windows Server 2016.

**Comment by krishnasdfw** [comment]
Thanks. Work around may be, we could develop whatever supported using 2.9 version GUI and run it in 2.10 environment for the sake of JDK 17 support added in 2.10.  Many times Hop pipelines/ workflows may run embedded in other environments like Spring Boot whose latest versions have end of life and support only JDK 17 upwards. Thanks for the response.
