### ISSUE TITLE
[Bug]: Write to log (transform) - Unable to select specified fields to log

### ISSUE THREAD

**Issue by dave-csc** [apache/hop#4577]
### Apache Hop version?

2.10.0

### Java version?

17.0.2

### Operating system

Linux

### What happened?

Add a Write to log transform in a pipeline.

In version 2.10.0, you cannot specify directly the fields you want to log, unless you press the button Get fields and then remove the unnecessary ones.

In version 2.9.0, you can choose the fields you want to log without workarounds.

**_Marked as P1 for regression_**

### Issue Priority

Priority: 1

### Issue Component

Component: Hop Gui, Component: Transforms

**Comment by bamaer** [comment]
.take-issue

**Comment by shlxue** [comment]
Maybe it should be updated itemCount in TableView.removeAll method

**Comment by hansva** [comment]
I'll review both fixes because now we have 2 PR's for this issue.
