### ISSUE TITLE
[Bug]: Regex evaluation - wrong results

### ISSUE THREAD

**Issue by dave-csc** [apache/hop#4585]
### Apache Hop version?

2.10.0

### Java version?

17.0.2

### Operating system

Linux

### What happened?

The **Regex evaluation** transform seems to evaluate correctly a regular expression only if this matches the entire input field, and not part of it.

Example 1:
- Input field: `THIS IS A TITLE <PROCESSING_TAG>`
- Regex 1: `.*<(.*)>` -> returns correctly a match for the whole string and the group `PROCESSING_TAG`
- Regex 2: `<(.*)>` -> returns no match, should instead match the string `<PROCESSING_TAG>` and the group `PROCESSING_TAG`

Example 2:
- Input field: `RSSMRA70A01H501X`
- Regex 1: `[A-Z]{6}.*` -> return correctly a match for the whole string
- Regex 2: `[A-Z]{6}` -> returns no match, should instead match the first 6 letters `RSSMRA`

### Issue Priority

Priority: 3

### Issue Component

Component: Transforms

**Comment by hansva** [comment]
I am not sure what the ask here is. It's definitely not a bug.
What is the goal you are trying to achieve @dave-csc ?

The best way I have found to evaluate Java regex is the following site.
https://www.regexplanet.com/advanced/java/index.html

When I use your first example with the second regex we get the following result.
![image](https://github.com/user-attachments/assets/1344e9dd-bcca-4388-bef0-0c88c3e273aa)

What we check on in the transform is the "Matches()" result and if requested we return the group.

**Comment by hansva** [comment]
Correct, I think the documentation could use some improvements.
In this case the transform is an evaluation, and the assumption is that it evaluates the whole field. The same way as a filter would behave. I think the original mistake was to add capture groups to this transform. It would have been cleaner to have a **Regex Extract** transform or something similar.

Another option would be to add an option to the transform to use find(). an option like "allow partial matches" or something like that.

**Comment by hansva** [comment]
It seems our website build has been failing, https://ci-builds.apache.org/job/Hop/job/Hop-website/job/main/
I'll try and figure out what is going wrong

**Comment by hansva** [comment]
All is back in working order now.
