### ISSUE TITLE
[Bug]: Variable selection not inserting into SQL text in Table Input transform

### ISSUE THREAD

**Issue by Adalennis** [apache/hop#4591]
### Apache Hop version?

SNAPSHOT-2024-11-15

### Java version?

java version 21.0.2

### Operating system

macOS

### What happened?

In the Table Input transform, when using Ctrl + Space to open the variables list, selecting and double-clicking a variable does not insert it into the SQL text as expected.

**Steps to reproduce:**
1. Open the Table Input transform in Hop GUI.
2. Click into the SQL editor.
3. Press Ctrl + Space to display the list of variables.
4. Select a variable from the list.
5. Double-click on the selected variable.
6. Observe that the variable is not inserted into the SQL text.

**Expected behavior:**
Double-clicking on a variable in the Ctrl + Space variable list should automatically insert it into the SQL text.

**Actual behavior:**
The variable is not inserted into the SQL text, requiring manual entry.

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by dave-csc** [comment]
Hi @Adalennis, it's probably a more general problem, check also #3783

**Comment by Adalennis** [comment]
Got it @dave-csc, thanks
