### ISSUE TITLE
[Bug]: Help button in 2.11.0 

### ISSUE THREAD

**Issue by rdubois-mel** [apache/hop#4704]
### Apache Hop version?

2.11.0

### Java version?

21

### Operating system

Windows

### What happened?

The _Help_ button in each transformation sends to a 404 page.
Example: 
https://hop.apache.org/manual/2.11.0/pipeline/transforms/rowgenerator.html
The valid link is:
https://hop.apache.org/manual/latest/pipeline/transforms/rowgenerator.html

Is it possible to resolve this issue on the server side? 

Thanks

### Issue Priority

Priority: 2

### Issue Component

Component: Website

**Comment by hansva** [comment]
.take-issue

**Comment by hansva** [comment]
Thank you for reporting this, a small step was forgotten during the release process.
