### ISSUE TITLE
[Bug]: Unable to open a metadata in the metatada perspective

### ISSUE THREAD

**Issue by nadment** [apache/hop#4712]
### Apache Hop version?

2.12.0-SNAPSHOT

### Java version?

Java 17

### Operating system

Windows

### What happened?

A Windows-specific problem, I suspect the commit below replaces File.sperataror
https://github.com/apache/hop/commit/4353eaeed32d17865a7be3d3a3053a77ca99175b#diff-3587a5c51df4777939018df14083ee3d30e1de57cd94e110516f4328021795a4R546

HopException: 
Error loading metadata object '/Hop/config/projects/samples/metadata/pipeline-run-configuration/local.json' from file 'config/projects/samples/metadata\pipeline-run-configuration//Hop/config/projects/samples/metadata/pipeline-run-configuration/local.json.json'

org.apache.commons.vfs2.FileNotFoundException: Could not read from "file:///C:/Hop/config/projects/samples/metadata/pipeline-run-configuration/Hop/config/projects/samples/metadata/pipeline-run-configuration/local.json.json" because it is not a file.
Could not read from "file:///C:/Hop/config/projects/samples/metadata/pipeline-run-configuration/Hop/config/projects/samples/metadata/pipeline-run-configuration/local.json.json" because it is not a file.

Could not read from "file:///C:/Hop/config/projects/samples/metadata/pipeline-run-configuration/Hop/config/projects/samples/metadata/pipeline-run-configuration/local.json.json" because it is not a file.

Root cause: FileNotFoundException: C:\Hop\config\projects\samples\metadata\pipeline-run-configuration\Hop\config\projects\samples\metadata\pipeline-run-configuration\local.json.json (Le chemin d’accès spécifié est introuvable)

### Issue Priority

Priority: 3

### Issue Component

Component: Hop Gui

**Comment by hansva** [comment]
I caused that, sorry about that.

.take-issue

**Comment by hansva** [comment]
should be resolved
